<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="shop">
	<p>
	   <a class="btn" title="<?php _e('Add Category'); ?>" href="<?php echo $this->url('', array('controller' => 'category', 'action' => 'update')); ?>"><i class="icon-folder-open"></i> <?php _e('Add Category'); ?></a>
	</p>
	<h3><?php _e('List of products'); ?></h3>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('Title'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($list as $category) { ?>
		<?php
		if($category['status'] == 1) {
			$labelIdClass = 'label-success';	
		} else {
			$labelIdClass = 'label-warning';	
		}	
		?>
		<tr>
			<td><span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($category['id']); ?></span></td>
			<td><?php echo $this->escape($category['title']); ?></td>
			<td>
				<a class="btn" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('action' => 'update', 'id' => $category['id'])); ?>"><i class="icon-edit"></i> <?php _e('Edit'); ?></a>
			</td>
		</tr>
		<?php } ?>
	</table>
</div>