<?php

// Set script
$script
        = <<<'EOT'
$("#grid-data").bootgrid({
    ajax: true,
    post: function () {
        return {
            id: "%d"
        };
    },
    searchSettings: {
        delay: 1000,
        characters: 3
    },
    url: "%s",
    formatters: {
        "link": function(column, row) {
            return '<a target="_blank" class="btn btn-primary btn-sm" href="'+ row.edit_url +'"><i class="fa fa-edit"></i> %s</a> <a target="_blank" class="btn btn-success btn-sm" href="' + row.view_url + '"><i class="fa fa-eye"></i> %s</a>';
        }
    },
    statusMappings: {
        1: "success",
        2: "warning",
        3: "warning",
        4: "warning",
        5: "danger",
    },
    rowCount : [25, 50, 100, 250, 500],
    labels: {
        all: "%s",
        infos: "%s",
        loading: "%s",
        noResults: "%s",
        refresh: "%s",
        search: "%s",
    },
    keepSelection: true,
    templates: bs4Fix(),
});
function bs4Fix() {
    // Fix for BS4, https://github.com/rstaib/jquery-bootgrid/issues/403
    return {
        // pagination: '{{ctx.text}}'
        // paginationButton: "btn-info btn-sm",
        paginationItem: "<li class=\"page-item {{ctx.css}}\"><a data-page=\"{{ctx.page}}\" class=\"page-link btn-info btn-sm {{css.paginationButton}}\">{{ctx.text}}</a></li>"
    };
}
EOT;
$script = sprintf(
    $script,
    uniqid('category-list-'),
    Pi::url(
        $this->url(
            '', [
            'controller' => 'category',
            'action'     => 'ajax',
            'type'       => $type,
        ]
        )
    ),
    __('Edit'),
    __('View'),
    __('All'),
    __('{{ctx.start}} to {{ctx.end}} of {{ctx.total}} entries'),
    __('Loading...'),
    __('No results found!'),
    __('refresh'),
    __('search')
);
// Load header
$this->jQuery();
$this->js(
    [
        $this->assetModule('js/jquery.bootgrid.min.js'),
        $this->assetModule('js/jquery.bootgrid.fa.min.js'),
    ]
);
$this->css(
    [
        $this->assetModule('css/admin.css'),
        $this->assetModule('css/jquery.bootgrid.min.css'),
    ]
);
$this->footScript()->appendScript($script);
?>
<div class="clearfix">
    <?php if ($count > 0) { ?>
        <h1><?php _e('List of Categores'); ?></h1>
        <table id="grid-data" class="table table-striped table-bordered table-sm">
            <thead>
            <tr>
                <th data-column-id="id" data-type="numeric"><?php _e('ID'); ?></th>
                <th data-column-id="title"><?php _e('Title'); ?></th>
                <th data-column-id="display_order" data-type="numeric"><?php _e('Display order'); ?></th>
                <th data-column-id="link" data-formatter="link" data-sortable="false"><?php _e('Action'); ?></th>
            </tr>
            </thead>
        </table>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <?php _e('Please build new category or brand'); ?>
        </div>
    <?php } ?>
</div>