<?php
    $this->css($this->assetModule('css/admin.css'));
?>
<div class="clearfix">
	<?php $navLocation = 1; ?>
	<?php include $this->template('admin/checkout_nav'); ?>
	<p>
	   <a class="btn btn-primary" title="<?php _e('Add Location'); ?>" href="<?php echo $this->url('', array('controller' => 'checkout', 'action' => 'locationUpdate')); ?>"><i class="fa fa-folder-open"></i> <?php _e('Add Location'); ?></a>
	</p>
	<h3><?php _e('List of Location'); ?></h3>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('Title'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($list as $location) { ?>
		<?php
		if($location['status'] == 1) {
			$labelIdClass = 'label-success';	
		} else {
			$labelIdClass = 'label-warning';	
		}	
		?>
		<tr>
			<td><span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($location['id']); ?></span></td>
			<td><?php echo $this->escape($location['title']); ?></td>
			<td>
				<a class="btn btn-primary" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('action' => 'locationUpdate', 'id' => $location['id'])); ?>"><i class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
			</td>
		</tr>
		<?php } ?>
	</table>
</div>	
