<?php
    $this->css($this->assetModule('css/admin.css'));
?>
<div class="shop">
	<?php $navIndex = 1; ?>
	<?php include $this->template('admin/checkout_nav'); ?>
	<h3><?php _e('Manage checkout options'); ?></h3>
	<p><?php _e('On this part, you can manage checkout options, select payment method and add user location and delivery system, For manage this levels and options you can check and manage this parts'); ?></p>
	<ul>
		<li><?php _e('Check order settings on module configurations'); ?></li>
		<li><?php _e('Add delivery methods and select payment options for each method'); ?></li>
		<li><?php _e('Add locations and set delivery methods for each location'); ?></li>
	</ul>
</div>