<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <p>
        <a class="btn btn-primary" title="<?php _e('Add discount'); ?>"
           href="<?php echo $this->url('', array('controller' => 'discount', 'action' => 'update')); ?>"><i
                class="fa fa-folder-open"></i> <?php _e('Add discount'); ?></a>
    </p>
    <h3><?php _e('List of discounts'); ?></h3>
    <?php if (!empty($list)) { ?>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Title'); ?></th>
                <th><?php _e('Role'); ?></th>
                <th><?php _e('Percent'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list as $discount) { ?>
                <?php
                if ($discount['status'] == 1) {
                    $labelIdClass = 'label-success';
                } else {
                    $labelIdClass = 'label-warning';
                }
                ?>
                <tr>
                    <td><span
                            class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($discount['id']); ?></span>
                    </td>
                    <td><?php echo $this->escape($discount['title']); ?></td>
                    <td><?php echo $this->escape($discount['role']); ?></td>
                    <td><?php echo $this->escape($discount['percent']); ?></td>
                    <td>
                        <a class="btn btn-primary btn-xs" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', array('action' => 'update', 'id' => $discount['id'])); ?>"><i
                                class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                    </td>
                </tr>
            <?php } ?>
        </table>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <?php _e('You still do not add any discount, use add discount button for add new one'); ?>
        </div>
    <?php } ?>
</div>