<?php 
    $this->bootstrap();
    $this->css($this->assetModule('script/system-ui.css'));
    $this->css($this->assetModule('css/admin.css'));
    $this->jQuery();
    $this->backbone();
?>
<div id="js-order" class="shop">
    <?php include $this->templateComponent('form'); ?>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
            <th><?php _e('Code'); ?></th>
			<th><?php _e('Customer'); ?></th>
			<th><?php _e('Status'); ?> ( <?php _e('Order'); ?> / <?php _e('Payment'); ?> / <?php _e('Delivery'); ?> )</th>
			<th><?php _e('Total price'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($list as $order) { ?>
		<tr 
            data-id="<?php echo $this->escape($order['id']); ?>" 
            data-order="<?php echo $this->escape($order['url_update_order']); ?>" 
            data-payment="<?php echo $this->escape($order['url_update_payment']); ?>" 
            data-delivery="<?php echo $this->escape($order['url_update_delivery']); ?>"
        >
			<td><?php echo $this->escape($order['id']); ?></td>
            <td><?php echo $this->escape($order['code']); ?></td>
			<td>
				<?php echo $this->escape($order['first_name']); ?> 
				<?php echo $this->escape($order['last_name']); ?> 
				<span class="label label-info">
					<?php echo $this->escape($order['user']['identity']); ?> 
					( <?php echo $this->escape($order['user']['name']); ?> ) 
				</span>
			</td>
			<td>
				<span id="update-order-<?php echo $this->escape($order['id']); ?>" class="update-order btn <?php echo $this->escape($order['orderClass']); ?> "><?php echo $this->escape($order['orderTitle']); ?></span>
				<span id="update-payment-<?php echo $this->escape($order['id']); ?>" class="update-payment btn <?php echo $this->escape($order['paymentClass']); ?> "><?php echo $this->escape($order['paymentTitle']); ?></span>
				<span id="update-delivery-<?php echo $this->escape($order['id']); ?>" class="update-delivery btn <?php echo $this->escape($order['deliveryClass']); ?> "><?php echo $this->escape($order['deliveryTitle']); ?></span>
			</td>
			<td><?php echo $this->escape($order['total_price']); ?></td>
			<td>
				<a class="btn btn-primary" title="<?php _e('View'); ?>" href="<?php echo $this->escape($order['url_view']); ?>" target="_blank"><?php _e('View'); ?></a>
                <button type="button" class="btn btn-info" data-toggle="modal" data-target="#info-view-<?php echo $this->escape($order['id']); ?>"><i class="fa fa-eye-open fa fa-white"></i> <?php _e('Details'); ?></button>
				<div id="info-view-<?php echo $this->escape($order['id']); ?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        			<div class="modal-header">
            			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        				<h3 id="myModalLabel"><?php echo sprintf('Order %s', $this->escape($order['id'])); ?></h3>
        			</div>
        			<div class="modal-body">
        				<h4><?php _e('Customer'); ?></h4>
        				<ul class="clearfix list-unstyled">
        					<li class="col-md-3"><strong><?php _e('Order Name'); ?></strong> : <?php echo $this->escape($order['first_name']); ?> <?php echo $this->escape($order['last_name']); ?></li>
        					<li class="col-md-3"><strong><?php _e('User Name'); ?></strong> : <?php echo $this->escape($order['user']['identity']); ?> ( <?php echo $this->escape($order['user']['name']); ?> ) 
								<span class="label label-info">
									<?php echo $this->escape($order['user']['id']); ?> 
								</span></li>
        					<li class="col-md-3"><strong><?php _e('Order Email'); ?></strong> : <?php echo $this->escape($order['email']); ?></li>
        					<li class="col-md-3"><strong><?php _e('Email'); ?></strong> : <?php echo $this->escape($order['user']['email']); ?></li>
        					<li class="col-md-3"><strong><?php _e('Phone'); ?></strong> : <?php echo $this->escape($order['phone']); ?></li>
        					<li class="col-md-3"><strong><?php _e('Mobile'); ?></strong> : <?php echo $this->escape($order['mobile']); ?></li>
        					<li class="col-md-3"><strong><?php _e('Company'); ?></strong> : <?php echo $this->escape($order['company']); ?></li>
        					<li class="col-md-3"><strong><?php _e('Country'); ?></strong> : <?php echo $this->escape($order['country']); ?></li>
        					<li class="col-md-3"><strong><?php _e('City'); ?></strong> : <?php echo $this->escape($order['city']); ?></li>
        					<li class="col-md-3"><strong><?php _e('Zip ode'); ?></strong> : <?php echo $this->escape($order['zip_code']); ?></li>
        					<li class="col-md-6"><strong><?php _e('Address'); ?></strong> : <?php echo $this->escape($order['address']); ?></li>
        				</ul>
        				<h4><?php _e('Order'); ?></h4>
        				<ul class="clearfix list-unstyled">
        					<li class="col-md-4"><strong><?php _e('Status'); ?></strong> : <span class="label <?php echo $this->escape($order['orderClass']); ?> "><?php echo $this->escape($order['orderTitle']); ?></span></li>
        					<li class="col-md-4"><strong><?php _e('Time create'); ?></strong> : <?php echo $this->escape($order['time_create_view']); ?></li>
        					<li class="col-md-4"><strong><?php _e('Time finish'); ?></strong> : <?php echo $this->escape($order['time_finish_view']); ?></li>
        				</ul>
        				<h4><?php _e('Payment'); ?></h4>
        				<ul class="clearfix list-unstyled">
        					<li class="col-md-2"><strong><?php _e('Status'); ?></strong> : <span class="label <?php echo $this->escape($order['paymentClass']); ?> "><?php echo $this->escape($order['paymentTitle']); ?></span></li>
        					<li class="col-md-4"><strong><?php _e('Time'); ?></strong> : <?php echo $this->escape($order['time_payment_view']); ?></li>
        					<li class="col-md-2"><strong><?php _e('Method'); ?></strong> : <?php echo $this->escape($order['payment_method']); ?></li>
        					<li class="col-md-4"><strong><?php _e('Adapter'); ?></strong> : <?php echo $this->escape($order['payment_adapter']); ?></li>
        				</ul>
        				<h4><?php _e('Delivery'); ?></h4>
        				<ul class="clearfix list-unstyled">
        					<li class="col-md-4"><strong><?php _e('Status'); ?></strong> : <span class="label <?php echo $this->escape($order['deliveryClass']); ?> "><?php echo $this->escape($order['deliveryTitle']); ?></span></li>
        					<li class="col-md-4"><strong><?php _e('Time'); ?></strong> : <?php echo $this->escape($order['time_delivery_view']); ?></li>
         					<li class="col-md-3"><strong><?php _e('Method'); ?></strong> : </li>
         					<li class="col-md-3"><strong><?php _e('Packing'); ?></strong> : </li>
        				</ul>
        				<h4><?php _e('Price'); ?></h4>
        				<ul class="clearfix list-unstyled">
        					<li class="col-md-3"><strong><?php _e('Price'); ?></strong> : <?php echo $this->escape($order['product_price_view']); ?></li>
        					<li class="col-md-3"><strong><?php _e('Discount'); ?></strong> : <?php echo $this->escape($order['discount_price_view']); ?></li>
         					<li class="col-md-3"><strong><?php _e('Shipping'); ?></strong> : <?php echo $this->escape($order['shipping_price_view']); ?></li>
         					<li class="col-md-3"><strong><?php _e('Packing'); ?></strong> : <?php echo $this->escape($order['packing_price_view']); ?></li>
         					<li class="col-md-3"><strong><?php _e('Total'); ?></strong> : <?php echo $this->escape($order['total_price_view']); ?></li>
         					<li class="col-md-3"><strong><?php _e('Paid'); ?></strong> : <?php echo $this->escape($order['paid_price_view']); ?></li>
        				</ul>
        			</div>
        			<div class="modal-footer clearfix">
        				<div class="pull-right">
        					<button class="btn btn-primary" data-dismiss="modal" aria-hidden="true"><?php _e('Close'); ?></button>
        				</div>
        				<div class="pull-left">
        					<a class="btn btn-primary" title="<?php _e('View'); ?>" href="<?php echo $this->escape($order['url_view']); ?>" target="_blank"><?php _e('View'); ?></a>
        					<a class="btn btn-primary" title="<?php _e('Edit'); ?>" href="<?php echo $this->escape($order['url_edit']); ?>" target="_blank"><?php _e('Edit'); ?></a>
        					<a class="btn btn-primary" title="<?php _e('Print'); ?>" href="<?php echo $this->escape($order['url_print']); ?>" target="_blank"><?php _e('Print'); ?></a>
        				</div>
        			</div>
    			</div>
			</td>
		</tr>
		<?php } ?>
	</table>
	<div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
</div>
<script>
(function($) {
    var page = {
        el: $('#js-order'),
        modal: $('<div class="modal hide fade">').appendTo(document.body),
        $: function(selector) {
            return this.el.find(selector);
        },
        init: function() {
            _.bindAll(this);
            this.$('.update-order').click(this.orderAction);
            this.$('.update-payment').click(this.paymentAction);
            this.$('.update-delivery').click(this.deliveryAction);
        },
        orderAction: function(e) {
            var p = $(e.target).parents('tr'),
                self =this;
            $.get(p.attr('data-order')).done(function(res) {
                self.modal.html(res).modal('show');
                formModule.success = function(res) {
                    var d = res.data;
                    self.modal.html(res).modal('hide');
                    $('#update-order-' + p.attr('data-id')).attr('class', 'update-order btn ' + d.orderClass).html(d.orderTitle);
                };
            });
        },
        paymentAction: function(e) {
            var p = $(e.target).parents('tr'),
                self =this;
            $.get(p.attr('data-payment')).done(function(res) {
                self.modal.html(res).modal('show');
                formModule.success = function(res) {
                    var d = res.data;
                    self.modal.html(res).modal('hide');
                    $('#update-payment-' + p.attr('data-id')).attr('class', 'update-payment btn ' + d.paymentClass).html(d.paymentTitle);
                };
            });
        },
        deliveryAction: function(e) {
            var p = $(e.target).parents('tr'),
                self =this;
            $.get(p.attr('data-delivery')).done(function(res) {
                self.modal.html(res).modal('show');
                formModule.success = function(res) {
                    var d = res.data;
                    self.modal.html(res).modal('hide');
                    $('#update-delivery-' + p.attr('data-id')).attr('class', 'update-delivery btn ' + d.deliveryClass).html(d.deliveryTitle);
                };
            });
        },
    }
    page.init();
})(jQuery)
</script>