<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <?php if ($confirm == 1) { ?>
        <div class="progress progress-striped active">
            <div class="progress-bar" role="progressbar" aria-valuenow="<?php echo $percent; ?>" aria-valuemin="0"
                 aria-valuemax="100" style="width: <?php echo $percent; ?>%">
                <?php echo $percent; ?> % Complete
            </div>
        </div>
        <pre><?php print_r($info); ?></pre>
    <?php if (!empty($nextUrl)) { ?>
        <script>
            window.setTimeout(function () {
                window.location.href = '<?php echo $nextUrl; ?>';
            }, 1000);
        </script>
    <?php } ?>
    <?php } else { ?>
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#priceModal">
            <?php _e('Confirm'); ?>
        </button>
        <div class="modal fade" id="priceModal" tabindex="-1" role="dialog" aria-labelledby="priceModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="<?php _e('Close'); ?>">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title" id="priceModalLabel"><?php _e('Sync price'); ?></h4>
                    </div>
                    <div class="modal-body">
                        <?php _e(
                            'For start sync product price, please confirm this form, after start we should wait to finish sync all products , it take some min, please dont close this page before finish sync'
                        ); ?>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary"
                                data-dismiss="modal"><?php _e('Close'); ?></button>
                        <a href="<?php echo $nextUrl; ?>" class="btn btn-primary"><?php _e('Confirm'); ?></a>
                    </div>
                </div>
            </div>
        </div>
        <script>
            $(document).ready(function () {
                $('#priceModal').modal('show');
            });
        </script>
    <?php } ?>
</div>