<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <div class="well">
        <h3><?php _e('How this part work?'); ?></h3>
        <p><?php _e('Price system, help you to manage your product price and kep product price update'); ?></p>
        <ul>
            <li><strong><?php _e('Price update'); ?></strong> : <?php _e('Select category ( main category ) and update all products on that category'); ?></li>
            <li><strong><?php _e('Price sync'); ?></strong> : <?php _e('Sync min price on `product` and `link` tables, after click this part start automatically, us this part just if needed'); ?></li>
            <li><strong><?php _e('Price log'); ?></strong> : <?php _e('Change price log for selected product, you need set product ID and see log'); ?></li>
        </ul>
    </div>
</div>