<?php
$this->css(array(
    $this->assetModule('css/admin.css'),
    $this->assetModule('script/system-ui.css', 'system'),
));
$this->jQuery();
$this->backbone();
$this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div id="js-product" class="clearfix">
    <div class="admin-header clearfix well well-sm">
        <div class="col-md-4">
            <div class="nav">
                <div class="btn-group">
                    <a class="btn btn-success" title="<?php _e('Add product'); ?>"
                       href="<?php echo $this->url('', array('controller' => 'product', 'action' => 'update')); ?>"><i
                            class="fa fa-folder-open"></i> <?php _e('Add product'); ?></a>
                </div>
                <div class="btn-group">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-eye"></i> <?php _e('View'); ?> <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        <li><a title="<?php _e('All products'); ?>"
                               href="<?php echo $this->url('', array('controller' => 'product', 'action' => 'index')); ?>"><i
                                    class="fa fa-file"></i> <?php _e('All products'); ?></a></li>
                        <li><a title="<?php _e('Published'); ?>"
                               href="<?php echo $this->url('', array('controller' => 'product', 'action' => 'index', 'status' => '1')); ?>"><i
                                    class="fa fa-file"></i> <?php _e('Published'); ?></a></li>
                        <li><a title="<?php _e('Pending review'); ?>"
                               href="<?php echo $this->url('', array('controller' => 'product', 'action' => 'index', 'status' => '2')); ?>"><i
                                    class="fa fa-file"></i> <?php _e('Pending review'); ?></a></li>
                        <li><a title="<?php _e('Draft'); ?>"
                               href="<?php echo $this->url('', array('controller' => 'product', 'action' => 'index', 'status' => '3')); ?>"><i
                                    class="fa fa-file"></i> <?php _e('Draft'); ?></a></li>
                        <li><a title="<?php _e('Private'); ?>"
                               href="<?php echo $this->url('', array('controller' => 'product', 'action' => 'index', 'status' => '4')); ?>"><i
                                    class="fa fa-file"></i> <?php _e('Private'); ?></a></li>
                        <li><a title="<?php _e('Trash'); ?>"
                               href="<?php echo $this->url('', array('controller' => 'product', 'action' => 'index', 'status' => '5')); ?>"><i
                                    class="fa fa-file"></i> <?php _e('Trash'); ?></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <?php echo $this->form($form, 'inline'); ?>
        </div>
    </div>
    <h3><?php _e('List of product'); ?></h3>
    <table id="product-list" class="table table-striped table-bordered table-condensed">
        <tr>
            <th class="col-md-6"><?php _e('Title'); ?></th>
            <th class="col-md-2"><?php _e('Action'); ?></th>
            <th class="col-md-4"><?php _e('Min price'); ?></th>
        </tr>
        <?php foreach ($list as $product) { ?>
            <?php
            if ($product['status'] == 1) {
                $labelIdClass = 'label-success';
            } else {
                $labelIdClass = 'label-warning';
            }
            ?>
            <tr data-id="<?php echo $this->escape($product['id']); ?>"
                data-price="<?php echo Pi::url($this->url('', array('action' => 'price', 'id' => $product['id']))); ?>"
                <?php if ($product['recommended'] == 1) { ?>
                    data-recommended="<?php echo Pi::url($this->url('', array('action' => 'recommend', 'id' => $product['id'], 'recommended' => '0'))); ?>"
                <?php } else { ?>
                    data-recommended="<?php echo Pi::url($this->url('', array('action' => 'recommend', 'id' => $product['id'], 'recommended' => '1'))); ?>"
                <?php } ?>
                >
                <td class="product-ajax">
                        <span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($product['id']); ?></span>
                    <?php if ($product['recommended'] == 1) { ?>
                        <button id="button-<?php echo $product['id']; ?>" type="button" class="btn btn-link product-recommend" data-toggle="button">
                            <i class="fa fa-heart"></i>
                        </button>
                    <?php } else { ?>
                        <button id="button-<?php echo $product['id']; ?>" type="button" class="btn btn-link product-recommend" data-toggle="button">
                            <i class="fa fa-heart-o"></i>
                        </button>
                    <?php } ?>
                    <?php echo $this->escape($product['title']); ?>
                    <?php if (!empty($product['subtitle'])) { ?> ( <?php echo $this->escape($product['subtitle']); ?> )<?php } ?>
                    <?php if ($product['sold'] > 0) { ?> ( <?php _e('Sold'); ?> : <?php echo $this->escape(_number($product['sold'])); ?> )<?php } ?>
                </td>
                <td>
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary btn-xs dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-edit"></i> <?php _e('Manage'); ?> <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><a title="<?php _e('Edit basic information'); ?>"
                                   href="<?php echo $this->url('', array('action' => 'update', 'id' => $product['id'])); ?>"><i
                                        class="fa fa-edit"></i> <?php _e('Edit basic information'); ?></a></li>
                            <li><a title="<?php _e('Edit additional information'); ?>"
                                   href="<?php echo $this->url('', array('action' => 'additional', 'id' => $product['id'])); ?>"><i
                                        class="fa fa-edit"></i> <?php _e('Edit additional information'); ?></a></li>
                            <li><a title="<?php _e('Attach files'); ?>"
                                   href="<?php echo $this->url('', array('controller' => 'attach', 'action' => 'add', 'id' => $product['id'])); ?>"><i
                                        class="fa fa-edit"></i> <?php _e('Attach files'); ?></a></li>
                            <li><a title="<?php _e('Related products'); ?>"
                                   href="<?php echo $this->url('', array('action' => 'related', 'id' => $product['id'])); ?>"><i
                                        class="fa fa-edit"></i> <?php _e('Related products'); ?></a></li>
                        </ul>
                    </div>
                    <?php if ($product['status'] == 1) { ?>
                        <a class="btn btn-success btn-xs" title="<?php _e('View'); ?>"
                           href="<?php echo $product['productUrl']; ?>" target="_blank"><i
                                class="fa fa-eye"></i> <?php _e('View'); ?></a>
                    <?php } ?>
                </td>
                <td>
                    <ul class="list-inline">
                        <li class="col-md-6 product-price-<?php echo $this->escape($product['id']); ?>">
                            <?php echo $product['price_view']; ?>
                        </li>
                        <li class="col-md-6">
                            <button type="button" class="btn btn-primary btn-xs product-price">
                                <?php _e('Update price and stock'); ?>
                            </button>
                        </li>
                    </ul>
                </td>
            </tr>
        <?php } ?>
    </table>
    <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
    <p>
        <span class="label label-success"><?php _e('Published'); ?></span>
        <span class="label label-warning"><?php _e('Pending review'); ?></span>
        <span class="label label-danger"><?php _e('Trash'); ?></span>
    </p>
</div>
<script>
    (function ($) {
        var page = {
            el: $('#js-product'),
            modal: $('<div class="modal fade">').appendTo(document.body),
            $: function (selector) {
                return this.el.find(selector);
            },
            init: function () {
                _.bindAll(this);
                this.$('.product-recommend').click(this.productRecommendAction);
                this.$('.product-price').click(this.productPriceAction);
            },
            productRecommendAction: function (e) {
                alert($(this).attr("data-recommended"));
                var p = $(e.target).parents('tr'),
                    self = this;
                systemMessage.wait("<?php _e('Recommended in process'); ?>");
                $.getJSON($(this).attr("data-recommended")).done(function (result) {
                    if (result.ajaxstatus == 1) {
                        if (result.recommended == 1) {
                            var buttonClass = 'fa fa-heart';
                        }
                        if (result.recommended == 0) {
                            var buttonClass = 'fa fa-heart-o';
                        }
                        $('#button-' + result.id + ' i').attr('class', buttonClass);
                        systemMessage.succ(result.message);
                    } else {
                        systemMessage.fail(result.message);
                    }
                });
            },
            productPriceAction: function (e) {
                var p = $(e.target).parents('tr'),
                    self = this;
                $.get(p.attr('data-price')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('.product-price-' + p.attr('data-id')).html(d.price);
                    };
                });
            },
        }
        page.init();
    })(jQuery)
</script>