<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="shop">
	<ul class="nav nav-tabs">
		<li class="active"><a title="<?php _e('List'); ?>" href="<?php echo $this->url('', array('controller' => 'product', 'action' => 'index')); ?>"><?php _e('List'); ?></a></li>
		<li><a title="<?php _e('Attributes'); ?>" href="<?php echo $this->url('', array('controller' => 'product', 'action' => 'attribute')); ?>"><?php _e('Attributes'); ?></a></li>
    	<li><a title="<?php _e('Property'); ?>" href="<?php echo $this->url('', array('controller' => 'product', 'action' => 'property')); ?>"><?php _e('Property'); ?></a></li>
    	<li><a title="<?php _e('Extra'); ?>" href="<?php echo $this->url('', array('controller' => 'product', 'action' => 'extra')); ?>"><?php _e('Extra'); ?></a></li>
    </ul>
	<p>
	   <a class="btn" title="<?php _e('Add product'); ?>" href="<?php echo $this->url('', array('controller' => 'product', 'action' => 'update')); ?>"><i class="icon-folder-open"></i> <?php _e('Add product'); ?></a>
	</p>
	<h3><?php _e('List of product'); ?></h3>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('Title'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($list as $product) { ?>
		<?php
		if($product['status'] == 1) {
			$labelIdClass = 'label-success';	
		} else {
			$labelIdClass = 'label-warning';	
		}	
		?>
		<tr>
			<td><span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($product['id']); ?></span></td>
			<td><?php echo $this->escape($product['title']); ?></td>
			<td>
				<a class="btn" title="<?php _e('Attach'); ?>" href="<?php echo $this->url('', array('action' => 'attach', 'id' => $product['id'])); ?>"><i class="icon-edit"></i> <?php _e('Attach'); ?></a>
				<a class="btn" title="<?php _e('Related'); ?>" href="<?php echo $this->url('', array('action' => 'related', 'id' => $product['id'])); ?>"><i class="icon-edit"></i> <?php _e('Related'); ?></a>
				<a class="btn" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('action' => 'update', 'id' => $product['id'])); ?>"><i class="icon-edit"></i> <?php _e('Edit'); ?></a>
			</td>
		</tr>
		<?php } ?>
	</table>
</div>