<?php
$this->css(array(
    $this->assetModule('css/admin.css'),
    $this->assetModule('script/system-ui.css', 'system'),
));
$this->jQuery();
$this->backbone();
$this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div id="js-product" class="clearfix">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingForm">
                <h4 class="panel-title">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseForm" aria-expanded="false" aria-controls="collapseForm">
                        <i class="fa fa-plus"></i> <?php _e('Filter products'); ?>
                    </a>
                </h4>
            </div>
            <div id="collapseForm" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingForm">
                <div class="panel-body">
                    <?php echo $this->form($form); ?>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix row order-header">
        <div class="col-xs-6">
            <h3><?php _e('List of product'); ?></h3>
        </div>
        <div class="col-xs-6 text-right">
            <a class="btn btn-success" title="<?php _e('Add product'); ?>"
               href="<?php echo $this->url('', array('controller' => 'product', 'action' => 'update')); ?>"><i
                        class="fa fa-folder-open"></i> <?php _e('Add product'); ?></a>
        </div>
    </div>

    <?php if (!empty($list)) { ?>
        <table id="product-list" class="table table-striped table-bordered table-condensed">
            <tr>
                <th class="col-md-6"><?php _e('Title'); ?></th>
                <th class="col-md-3"><?php _e('Action'); ?></th>
                <th class="col-md-3"><?php _e('Min price'); ?></th>
            </tr>
            <?php foreach ($list as $product) { ?>
                <?php if ($product['status'] == 1) {
                    $labelIdClass = 'label-success';
                } elseif ($product['status'] == 5) {
                    $labelIdClass = 'label-danger';
                } else {
                    $labelIdClass = 'label-warning';
                } ?>
                <tr data-id="<?php echo $this->escape($product['id']); ?>"
                    data-price="<?php echo Pi::url($this->url('', array('action' => 'price', 'id' => $product['id']))); ?>"
                    <?php if ($product['recommended'] == 1) { ?>
                        data-recommended="<?php echo Pi::url($this->url('', array('action' => 'recommend', 'id' => $product['id'], 'recommended' => '0'))); ?>"
                    <?php } else { ?>
                        data-recommended="<?php echo Pi::url($this->url('', array('action' => 'recommend', 'id' => $product['id'], 'recommended' => '1'))); ?>"
                    <?php } ?>
                >
                    <td class="product-ajax">
                        <span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($product['id']); ?></span>
                        <?php if ($product['recommended'] == 1) { ?>
                            <button id="button-<?php echo $product['id']; ?>" type="button" class="btn btn-link product-recommend" data-toggle="button">
                                <i class="fa fa-heart"></i>
                            </button>
                        <?php } else { ?>
                            <button id="button-<?php echo $product['id']; ?>" type="button" class="btn btn-link product-recommend" data-toggle="button">
                                <i class="fa fa-heart-o"></i>
                            </button>
                        <?php } ?>
                        <?php echo $this->escape($product['title']); ?>
                        <?php if (!empty($product['subtitle'])) { ?> ( <?php echo $this->escape($product['subtitle']); ?> )<?php } ?>
                        <?php if ($product['sold'] > 0) { ?> ( <?php _e('Sold'); ?> : <?php echo $this->escape(_number($product['sold'])); ?> )<?php } ?>
                        <?php if ($product['hits'] > 0) { ?> ( <?php _e('View'); ?> : <?php echo $this->escape(_number($product['hits'])); ?> )<?php } ?>
                    </td>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-primary btn-xs dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-edit"></i> <?php _e('Manage'); ?> <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a title="<?php _e('Edit basic information'); ?>"
                                       href="<?php echo $this->url('', array('action' => 'update', 'id' => $product['id'])); ?>"><i
                                                class="fa fa-edit"></i> <?php _e('Edit basic information'); ?></a></li>
                                <li><a title="<?php _e('Edit additional information'); ?>"
                                       href="<?php echo $this->url('', array('action' => 'additional', 'id' => $product['id'])); ?>"><i
                                                class="fa fa-edit"></i> <?php _e('Edit additional information'); ?></a></li>
                                <li><a title="<?php _e('Attach files'); ?>"
                                       href="<?php echo $this->url('', array('controller' => 'attach', 'action' => 'add', 'id' => $product['id'])); ?>"><i
                                                class="fa fa-edit"></i> <?php _e('Attach files'); ?></a></li>
                                <li><a title="<?php _e('Related products'); ?>"
                                       href="<?php echo $this->url('', array('action' => 'related', 'id' => $product['id'])); ?>"><i
                                                class="fa fa-edit"></i> <?php _e('Related products'); ?></a></li>
                                <?php if ($config['serial_active']) { ?>
                                    <li><a title="<?php _e('Manage serial number'); ?>"
                                           href="<?php echo $this->url('', array('action' => 'serial', 'id' => $product['id'])); ?>"><i
                                                    class="fa fa-edit"></i> <?php _e('Manage serial number'); ?></a></li>
                                <?php } ?>
                            </ul>
                        </div>
                        <?php if ($product['status'] == 1) { ?>
                            <a class="btn btn-success btn-xs" title="<?php _e('View'); ?>"
                               href="<?php echo $product['productUrl']; ?>" target="_blank"><i
                                        class="fa fa-eye"></i> <?php _e('View'); ?></a>
                        <?php } ?>
                        <?php if ($product['status'] != 5) { ?>
                            <a class="btn btn-danger btn-xs" title="<?php _e('Delete'); ?>" href="<?php echo $this->url('', array('action' => 'delete', 'id' => $product['id'])); ?>" onclick="return confirm('<?php echo _a('Are you sure to delete this product?'); ?>')">
                                <i class="fa fa-trash"></i>  <?php _e('Delete'); ?>
                            </a>
                        <?php } ?>
                    </td>
                    <td>
                        <ul class="list-inline clearfix">
                            <li class="product-price-<?php echo $this->escape($product['id']); ?>">
                                <?php echo $product['price_view']; ?>
                            </li>
                            <li class="pull-right">
                                <button type="button" class="btn btn-primary btn-xs product-price">
                                    <?php _e('Update'); ?>
                                </button>
                            </li>
                        </ul>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <div class="paginator">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
        </div>
        <p>
            <span class="label label-success"><?php _e('Published'); ?></span>
            <span class="label label-warning"><?php _e('Pending review'); ?></span>
            <span class="label label-danger"><?php _e('Trash'); ?></span>
        </p>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <?php _e('Product list is empty, perhaps you still didn\'t add any product or your selected filter didn\'t have any result'); ?>
        </div>
    <?php } ?>
</div>
<script>
    (function ($) {
        var page = {
            el: $('#js-product'),
            modal: $('<div class="modal fade">').appendTo(document.body),
            $: function (selector) {
                return this.el.find(selector);
            },
            init: function () {
                _.bindAll(this);
                this.$('.product-recommend').click(this.productRecommendAction);
                this.$('.product-price').click(this.productPriceAction);
            },
            productRecommendAction: function (e) {
                var p = $(e.target).parents('tr'),
                    self = this;
                systemMessage.wait("<?php _e('Recommended in process'); ?>");
                $.getJSON(p.attr("data-recommended")).done(function (result) {
                    if (result.ajaxstatus == 1) {
                        if (result.recommended == 1) {
                            var buttonClass = 'fa fa-heart';
                        }
                        if (result.recommended == 0) {
                            var buttonClass = 'fa fa-heart-o';
                        }
                        $('#button-' + result.id + ' i').attr('class', buttonClass);
                        systemMessage.succ(result.message);
                    } else {
                        systemMessage.fail(result.message);
                    }
                });
            },
            productPriceAction: function (e) {
                var p = $(e.target).parents('tr'),
                    self = this;
                $.get(p.attr('data-price')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('.product-price-' + p.attr('data-id')).html(d.price);
                    };
                });
            },
        }
        page.init();
    })(jQuery)
</script>