<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="news">
	<p>
	   <a class="btn" title="<?php _e('Add Spotlight'); ?>" href="<?php echo $this->url('', array('action' => 'spotlightUpdate')); ?>"><i class="icon-user"></i> <?php _e('Add Spotlight'); ?></a>
	</p>
	<h3><?php _e('List of spotlights'); ?></h3>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('Product'); ?></th>
			<th><?php _e('Show in'); ?></th>
			<th><?php _e('Publish'); ?></th>
			<th><?php _e('Expire'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($spotlights as $spotlight) { ?>
		<tr>
			<td><?php echo $this->escape($spotlight['id']); ?></td>
			<td><?php echo $this->escape($spotlight['productTitle']); ?></a></td>
			<td><?php echo $this->escape($spotlight['categoryTitle']); ?></td>
			<td><?php echo $this->escape($spotlight['time_publish']); ?></td>
			<td><?php echo $this->escape($spotlight['time_expire']); ?></td>
			<td>
				<a class="btn" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('action' => 'spotlightUpdate', 'id' => $spotlight['id'])); ?>"><i class="icon-edit"></i> <?php _e('Edit'); ?></a>
				<a class="btn" title="<?php _e('Delete'); ?>" href="<?php echo $this->url('', array('action' => 'spotlightDelete', 'id' => $spotlight['id'])); ?>"><i class="icon-trash"></i> <?php _e('Delete'); ?></a>
			</td>
		</tr>
		<?php } ?>
	</table>
</div>