<?php
$this->css([
    $this->assetModule('css/admin.css'),
    $this->assetModule('script/system-ui.css', 'system'),
]);
$this->jQuery();
$this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div class="clearfix" id="product-list">
    <?php if ($nav['type'] == 'edit') { ?>
        <div class="well well-sm">
            <ul class="nav nav-pills">
                <li<?php if ($nav['page'] == 'update') {
                    echo ' class="active"';
                } ?>>
                    <a href="<?php echo $this->url('', ['controller' => 'product', 'action' => 'update', 'id' => $product['id']]); ?>"><?php _e('Edit basic information'); ?></a>
                </li>
                <li<?php if ($nav['page'] == 'additional') {
                    echo ' class="active"';
                } ?>>
                    <a href="<?php echo $this->url('', ['controller' => 'product', 'action' => 'additional', 'id' => $product['id']]); ?>"><?php _e('Edit additional information'); ?></a>
                </li>
                <li<?php if ($nav['page'] == 'attach') {
                    echo ' class="active"';
                } ?>>
                    <a href="<?php echo $this->url('', ['controller' => 'attach', 'action' => 'add', 'id' => $product['id']]); ?>"><?php _e('Attach files'); ?></a>
                </li>
                <li<?php if ($nav['page'] == 'related') {
                    echo ' class="active"';
                } ?>>
                    <a href="<?php echo $this->url('', ['controller' => 'product', 'action' => 'related', 'id' => $product['id']]); ?>"><?php _e('Related products'); ?></a>
                </li>
                <li class="active pull-right"><a target="_blank"
                                                 href="<?php echo $product['productUrl']; ?>"><?php _e('View'); ?></a>
                </li>
            </ul>
        </div>
    <?php } ?>
    <h3><?php echo $product['title']; ?></h3>
    <p><?php _e('You can manage product related here, remove related productes or find new product by search system and add them to related'); ?></p>
    <?php if (!empty($related_list)) { ?>
        <h4><?php _e('List of related products'); ?></h4>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Title'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($related_list as $list) { ?>
                <tr id="product-<?php echo $list['id']; ?>">
                    <td><?php echo $this->escape($list['id']); ?></td>
                    <td><?php echo $this->escape($list['title']); ?></td>
                    <td>
                        <button id="button-<?php echo $list['id']; ?>" type="button" class="btn btn-danger"
                                data-toggle="button"
                                data-link="<?php echo $this->url('', ['action' => 'relatedAjax', 'product_id' => $product['id'], 'product_related' => $list['id'], 'related' => '0']); ?>">
                            <i class="fa fa-ok fa fa-white"></i> <?php _e('Remove'); ?></button>
                    </td>
                </tr>
            <?php } ?>
        </table>
    <?php } ?>
    <?php if (!empty($product_list)) { ?>
        <h4><?php _e('Search result'); ?></h4>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Title'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($product_list as $list) { ?>
                <tr id="product-<?php echo $list['id']; ?>">
                    <td><?php echo $this->escape($list['id']); ?></td>
                    <td><?php echo $this->escape($list['title']); ?></td>
                    <td>
                        <button id="button-<?php echo $list['id']; ?>" type="button" class="btn btn-success"
                                data-toggle="button"
                                data-link="<?php echo $this->url('', ['action' => 'relatedAjax', 'product_id' => $product['id'], 'product_related' => $list['id'], 'related' => '1']); ?>">
                            <i class="fa fa-ok fa fa-white"></i> <?php _e('Add'); ?></button>
                    </td>
                </tr>
            <?php } ?>
        </table>
    <?php } ?>
    <h4><?php _e('Search form'); ?></h4>
    <?php include $this->templateComponent('forms'); ?>
</div>
<script type="text/javascript">
    (function ($) {
        $("#product-list").on("click", "button", function () {
            systemMessage.wait("<?php _e('Related product in process'); ?>");
            $.getJSON($(this).attr("data-link")).done(function (result) {
                if (result.ajaxstatus == 1) {
                    if (result.relatedstatus == 1) {
                        //$('#product-' + result.id).slideUp('fast');
                    }
                    if (result.relatedstatus == 2) {
                        //$('#product-' + result.id).slideUp('fast');
                    }
                    systemMessage.succ(result.message);
                } else {
                    systemMessage.fail(result.message);
                }
            });
        });
    })(jQuery)
</script>