<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <table class="table table-striped table-bordered table-condensed">
        <tr>
            <th><?php _e('Title'); ?></th>
            <th><?php _e('Number'); ?></th>
        </tr>
        <tr>
            <td><?php _e('Total number'); ?></td>
            <td><?php echo $this->escape($count['all']); ?></td>
        </tr>
        <tr>
            <td><?php _e('Checked number'); ?></td>
            <td><?php echo $this->escape($count['checked']); ?></td>
        </tr>
        <tr>
            <td><?php _e('Not checked number'); ?></td>
            <td><?php echo $this->escape($count['notChecked']); ?></td>
        </tr>
    </table>

    <form class="form-inline text-right" method="post">
        <div class="form-group">
            <label><?php _e('Count of new serial numbers : '); ?></label>
            <input class="form-control" type="text" placeholder="<?php echo $config['serial_count']; ?>" disabled>
        </div>
        <button type="submit" class="btn btn-success"><?php _e('Generate'); ?></button>
    </form>
</div>