<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="shop">
	<?php $navAttribute = 1; ?>
	<?php include $this->template('admin/product_nav'); ?>
	<h3><?php echo $this->escape($title); ?></h3>
	<div class="alert alert-error">
		<button data-dismiss="alert" class="close" type="button">×</button>
		<?php echo $this->escape($message); ?>
	</div>
	<script>$(".alert").alert();</script>
</div>