<ul class="nav nav-pills well well-sm">
	<li<?php if (isset($navList) && $navList) { ?> class="active"<?php } ?>><a title="<?php _e('List'); ?>" href="<?php echo $this->url('', array('controller' => 'product', 'action' => 'index')); ?>"><?php _e('List'); ?></a></li>
	<li<?php if (isset($navSpecial) && $navSpecial) { ?> class="active"<?php } ?>><a title="<?php _e('Special'); ?>" href="<?php echo $this->url('', array('controller' => 'product', 'action' => 'special')); ?>"><?php _e('Special'); ?></a></li>
</ul>