<?php $this->css($this->assetModule('css/admin.css')); ?> 
<div class="shop">
	<?php $navList = 1; ?>
	<?php include $this->template('admin/product_nav'); ?>
	<h2><?php echo $this->escape($title); ?></h2>
	<?php if(isset($user) && !empty($user)) { ?>
	<div class="review-user">
		<?php echo sprintf(__('This review added by %s'), $user['name']); ?>
	</div>
	<?php } ?> 
	<?php include $this->templateComponent('form'); ?>
</div>