<?php
$this->css(array(
    $this->assetModule('css/admin.css'),
    $this->assetModule('script/system-ui.css', 'system'),
));
$this->jQuery();
$this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div id="product-form" class="clearfix">
    <h3><?php echo $this->escape($title); ?></h3>
    <?php echo $this->form($form); ?>
</div>
<script type="text/javascript">
    (function($){
        $("#product-form").on("click",".img-remove",function(){
            systemMessage.wait("<?php _e('Remove image product in process'); ?>");
            $.getJSON($(this).attr("data-link")).done(function(result){
                if(result.status==1){
                    systemMessage.succ(result.message);
                }else{
                    systemMessage.fail(result.message);
                }
            });
        });
    })(jQuery)
</script>
<script type="text/javascript">
    $(document).ready(function() {
        var max_fields      = 30; //maximum input boxes allowed
        var wrapper         = $("#product-form .property-color-list"); //Fields wrapper
        var add_button      = $(".add_property_color"); //Add button ID
        var x = 1; //initlal text box count
        $(add_button).click(function(e){ //on add input button click
            e.preventDefault();
            if(x < max_fields){ //max input box allowed
                x++; //text box increment
                $(wrapper).append('<div class="col-sm-12 js-form-element"><span class="col-sm-8">Color<input class="form-control" type="text" name="property_color['+ x +'][color]"/></span><span class="col-sm-3">Number<input class="form-control" type="text" name="property_color['+ x +'][number]"/></span><a href="#" class="remove_property_color col-sm-1 btn btn-link btn-xs"><i class="fa fa-trash"></i></a></div>'); //add input box
            }
        });
        $(wrapper).on("click",".remove_property_color", function(e){ //user click on remove text
            e.preventDefault(); $(this).parent('div').remove(); x--;
        })
    });
</script>
<script type="text/javascript">
    $(document).ready(function() {
        var max_fields      = 30; //maximum input boxes allowed
        var wrapper         = $("#product-form .property-warranty-list"); //Fields wrapper
        var add_button      = $(".add_property_warranty"); //Add button ID
        var x = 1; //initlal text box count
        $(add_button).click(function(e){ //on add input button click
            e.preventDefault();
            if(x < max_fields){ //max input box allowed
                x++; //text box increment
                $(wrapper).append('<div class="col-sm-12 js-form-element"><span class="col-sm-11"><input class="form-control" type="text" name="property_warranty[]"/></span><a href="#" class="remove_property_warranty col-sm-1 btn btn-link btn-xs"><i class="fa fa-trash"></i></a></div>'); //add input box
            }
        });
        $(wrapper).on("click",".remove_property_warranty", function(e){ //user click on remove text
            e.preventDefault(); $(this).parent('div').remove(); x--;
        })
    });
</script>