<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <p>
        <a class="btn btn-primary" title="<?php _e('Add promotion'); ?>"
           href="<?php echo $this->url('', array('controller' => 'promotion', 'action' => 'update')); ?>"><i
                class="fa fa-folder-open"></i> <?php _e('Add promotion'); ?></a>
    </p>
    <h3><?php _e('List of promotions'); ?></h3>
    <?php if (!empty($list)) { ?>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Title'); ?></th>
                <th><?php _e('Code'); ?></th>
                <th><?php _e('Used'); ?></th>
                <th><?php _e('Type'); ?></th>
                <th><?php _e('Time'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list as $promotion) { ?>
                <?php
                if ($promotion['status'] == 1) {
                    $labelIdClass = 'label-success';
                } elseif ($promotion['status'] == 2) {
                    $labelIdClass = 'label-warning';
                } elseif ($promotion['status'] == 3) {
                    $labelIdClass = 'label-warning';
                } elseif ($promotion['status'] == 4) {
                    $labelIdClass = 'label-warning';
                } elseif ($promotion['status'] == 5) {
                    $labelIdClass = 'label-danger';
                }
                ?>
                <tr<?php if ($promotion['isExpire']) { echo ' class="danger"'; } ?>>
                    <td><span
                            class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($promotion['id']); ?></span>
                    </td>
                    <td><?php echo $this->escape($promotion['title']); ?></td>
                    <td><?php echo $this->escape($promotion['code']); ?></td>
                    <td><?php echo $this->escape($promotion['used']); ?></td>
                    <td><?php switch ($promotion['type']) {
                            case 'percent':
                                echo sprintf('%s ( %s )', __('Percent'), $promotion['percent']);
                                break;

                            case 'price':
                                echo sprintf('%s ( %s )', __('Price'), Pi::api('api', 'shop')->viewPrice($promotion['price']));
                                break;
                        } ?></td>
                    <td><?php echo $this->escape($promotion['time']); ?></td>
                    <td>
                        <a class="btn btn-primary btn-xs" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', array('action' => 'update', 'id' => $promotion['id'])); ?>"><i
                                class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                    </td>
                </tr>
            <?php } ?>
        </table>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <?php _e('You still do not add any promotion code, use add promotion button for add new one'); ?>
        </div>
    <?php } ?>
</div>