<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <p>
        <a class="btn btn-primary" title="<?php _e('Add property'); ?>"
           href="<?php echo $this->url('', ['controller' => 'property', 'action' => 'update']); ?>"><i
                    class="fa fa-folder-open"></i> <?php _e('Add property'); ?></a>
    </p>

    <h3><?php _e('List of properties'); ?></h3>
    <table class="table table-striped table-bordered table-sm">
        <tr>
            <th><?php _e('ID'); ?></th>
            <th><?php _e('Title'); ?></th>
            <th><?php _e('Influence price'); ?></th>
            <th><?php _e('Influence stock'); ?></th>
            <th><?php _e('Action'); ?></th>
        </tr>
        <?php foreach ($list as $property) { ?>
            <?php if ($property['status'] == 1) {
                $labelIdClass = 'label-success';
            } else {
                $labelIdClass = 'label-warning';
            } ?>
            <tr>
                <td><span
                            class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($property['id']); ?></span>
                </td>
                <td><?php echo $this->escape($property['title']); ?></td>
                <td>
                    <?php if ($property['influence_price'] == 1) { ?>
                        <span class="badge badge-success"><?php _e('Yes'); ?></span>
                    <?php } else { ?>
                        <span class="badge badge-warning"><?php _e('No'); ?></span>
                    <?php } ?>
                </td>
                <td>
                    <?php if ($property['influence_stock'] == 1) { ?>
                        <span class="badge badge-success"><?php _e('Yes'); ?></span>
                    <?php } else { ?>
                        <span class="badge badge-warning"><?php _e('No'); ?></span>
                    <?php } ?>
                </td>
                <td>
                    <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                       href="<?php echo $this->url('', ['action' => 'update', 'id' => $property['id']]); ?>"><i
                                class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                </td>
            </tr>
        <?php } ?>
    </table>
</div>