<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <div class="btn-group">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">
            <?php _e('Add sale'); ?>
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <li><a title="<?php _e('Product sale'); ?>"
                   href="<?php echo $this->url('', ['action' => 'update', 'part' => 'product']); ?>"><i
                            class="fa fa-user"></i> <?php _e('Product sale'); ?></a></li>
            <li><a title="<?php _e('Category sale'); ?>"
                   href="<?php echo $this->url('', ['action' => 'update', 'part' => 'category']); ?>"><i
                            class="fa fa-user"></i> <?php _e('Category sale'); ?></a></li>
        </ul>
    </div>
    <h3><?php _e('List of sales products'); ?></h3>
    <?php if (!empty($sales['product'])) { ?>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Product'); ?></th>
                <th><?php _e('Time'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($sales['product'] as $sale) { ?>
                <?php
                if ($sale['status'] == 1) {
                    $labelIdClass = 'label-success';
                } elseif ($sale['status'] == 2) {
                    $labelIdClass = 'label-warning';
                } elseif ($sale['status'] == 3) {
                    $labelIdClass = 'label-warning';
                } elseif ($sale['status'] == 4) {
                    $labelIdClass = 'label-warning';
                } elseif ($sale['status'] == 5) {
                    $labelIdClass = 'label-danger';
                }
                ?>
                <tr<?php if ($sale['isExpire']) {
                    echo ' class="danger"';
                } ?>>
                    <td>
                        <span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($sale['id']); ?></span>
                    </td>
                    <td><?php echo $this->escape($sale['productInfo']['title']); ?>
                        (<?php echo $this->escape($sale['product']); ?>)
                    </td>
                    <td><?php echo $this->escape($sale['time']); ?></td>
                    <td>
                        <?php if ($sale['productInfo']['status'] == 1) { ?>
                            <a class="btn btn-success btn-xs" title="<?php _e('View'); ?>"
                               href="<?php echo $this->escape($sale['productInfo']['productUrl']); ?>"
                               target="_blank"><i
                                        class="fa fa-eye"></i> <?php _e('View'); ?></a>
                        <?php } ?>
                        <a class="btn btn-primary btn-xs" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', ['action' => 'update', 'id' => $sale['id'], 'part' => $sale['type']]); ?>"><i
                                    class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                        <a class="btn btn-danger btn-xs" title="<?php _e('Delete'); ?>"
                           href="<?php echo $this->url('', ['action' => 'delete', 'id' => $sale['id']]); ?>"><i
                                    class="fa fa-trash"></i> <?php _e('Delete'); ?></a>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <p>
            <span class="label label-success"><?php _e('Published'); ?></span>
            <span class="label label-warning"><?php _e('Pending review'); ?></span>
            <span class="label label-warning"><?php _e('Draft'); ?></span>
            <span class="label label-warning"><?php _e('Private'); ?></span>
            <span class="label label-danger"><?php _e('Trash'); ?></span>
        </p>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <?php _e('You still do not add any product to sale system, use add sale button for add new product'); ?>
        </div>
    <?php } ?>
    <h3><?php _e('List of sales categories'); ?></h3>
    <?php if (!empty($sales['category'])) { ?>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Product'); ?></th>
                <th><?php _e('Time'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($sales['category'] as $sale) { ?>
                <?php
                if ($sale['status'] == 1) {
                    $labelIdClass = 'label-success';
                } elseif ($sale['status'] == 2) {
                    $labelIdClass = 'label-warning';
                } elseif ($sale['status'] == 3) {
                    $labelIdClass = 'label-warning';
                } elseif ($sale['status'] == 4) {
                    $labelIdClass = 'label-warning';
                } elseif ($sale['status'] == 5) {
                    $labelIdClass = 'label-danger';
                }
                ?>
                <tr<?php if ($sale['isExpire']) {
                    echo ' class="danger"';
                } ?>>
                    <td>
                        <span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($sale['id']); ?></span>
                    </td>
                    <td><?php echo $this->escape($sale['categoryInfo']['title']); ?>
                        (<?php echo $this->escape($sale['category']); ?>)
                    </td>
                    <td><?php echo $this->escape($sale['time']); ?></td>
                    <td>
                        <?php if ($sale['categoryInfo']['status'] == 1) { ?>
                            <a class="btn btn-success btn-xs" title="<?php _e('View'); ?>"
                               href="<?php echo $this->escape($sale['categoryInfo']['categoryUrl']); ?>"
                               target="_blank"><i
                                        class="fa fa-eye"></i> <?php _e('View'); ?></a>
                        <?php } ?>
                        <a class="btn btn-primary btn-xs" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', ['action' => 'update', 'id' => $sale['id'], 'part' => $sale['type']]); ?>"><i
                                    class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                        <a class="btn btn-danger btn-xs" title="<?php _e('Delete'); ?>"
                           href="<?php echo $this->url('', ['action' => 'delete', 'id' => $sale['id']]); ?>"><i
                                    class="fa fa-trash"></i> <?php _e('Delete'); ?></a>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <p>
            <span class="label label-success"><?php _e('Published'); ?></span>
            <span class="label label-warning"><?php _e('Pending review'); ?></span>
            <span class="label label-warning"><?php _e('Draft'); ?></span>
            <span class="label label-warning"><?php _e('Private'); ?></span>
            <span class="label label-danger"><?php _e('Trash'); ?></span>
        </p>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <?php _e('You still do not add any category to sale system, use add sale button for add new category'); ?>
        </div>
    <?php } ?>
</div>