<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <p>
        <a class="btn btn-primary" title="<?php _e('Add Special'); ?>"
           href="<?php echo $this->url('', array('action' => 'update')); ?>"><i
                class="fa fa-user"></i> <?php _e('Add Special'); ?></a>
    </p>

    <h3><?php _e('List of specials'); ?></h3>
    <table class="table table-striped table-bordered table-condensed">
        <tr>
            <th><?php _e('ID'); ?></th>
            <th><?php _e('Product'); ?></th>
            <th><?php _e('Action'); ?></th>
        </tr>
        <?php foreach ($specials as $special) { ?>
            <?php
            if ($special['status'] == 1) {
                $labelIdClass = 'label-success';
            } elseif ($special['status'] == 2) {
                $labelIdClass = 'label-warning';
            } elseif ($special['status'] == 3) {
                $labelIdClass = 'label-warning';
            } elseif ($special['status'] == 4) {
                $labelIdClass = 'label-warning';
            } elseif ($special['status'] == 5) {
                $labelIdClass = 'label-danger';
            }
            ?>
            <tr>
                <td>
                    <span class="label <?php echo $labelIdClass; ?>">
                        <?php echo $this->escape($special['id']); ?>
                    </span>
                </td>
                <td><?php echo $this->escape($special['productTitle']); ?> (<?php echo $this->escape($special['product']); ?>)</td>
                <td>
                    <a class="btn btn-primary btn-xs" title="<?php _e('Edit'); ?>"
                       href="<?php echo $this->url('', array('action' => 'update', 'id' => $special['id'])); ?>"><i
                            class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                    <a class="btn btn-danger btn-xs" title="<?php _e('Delete'); ?>"
                       href="<?php echo $this->url('', array('action' => 'delete', 'id' => $special['id'])); ?>"><i
                            class="fa fa-trash"></i> <?php _e('Delete'); ?></a>
                </td>
            </tr>
        <?php } ?>
    </table>
    <p>
        <span class="label label-success"><?php _e('Published'); ?></span>
        <span class="label label-warning"><?php _e('Pending review'); ?></span>
        <span class="label label-warning"><?php _e('Draft'); ?></span>
        <span class="label label-warning"><?php _e('Private'); ?></span>
        <span class="label label-danger"><?php _e('Trash'); ?></span>
    </p>
</div>