<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <p>
        <a class="btn btn-primary" title="<?php _e('Add Special'); ?>" href="<?php echo $this->url('', array('action' => 'update')); ?>"><i class="fa fa-user"></i> <?php _e('Add Special'); ?></a>
    </p>
    <h3><?php _e('List of specials'); ?></h3>
    <table class="table table-striped table-bordered table-condensed">
        <tr>
            <th><?php _e('ID'); ?></th>
            <th><?php _e('Product'); ?></th>
            <th><?php _e('Action'); ?></th>
        </tr>
        <?php foreach($specials as $special) { ?>
            <tr>
                <td><?php echo $this->escape($special['id']); ?></td>
                <td><?php echo $this->escape($special['productTitle']); ?></a></td>
                <td>
                    <a class="btn btn-primary" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('action' => 'update', 'id' => $special['id'])); ?>"><i class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                    <a class="btn btn-danger" title="<?php _e('Delete'); ?>" href="<?php echo $this->url('', array('action' => 'delete', 'id' => $special['id'])); ?>"><i class="fa fa-trash"></i> <?php _e('Delete'); ?></a>
                </td>
            </tr>
        <?php } ?>
    </table>
</div>