<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <div class="well">
        <h3><?php _e('How this part work?'); ?></h3>

        <p><?php _e('Tools system, help you to manage your module, Update database and remove unused information'); ?></p>
        <ul>
            <li><strong><?php _e('Sitemap'); ?></strong> : <?php _e('Manage links on sitemap module'); ?></li>
        </ul>
    </div>
</div>