<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <div class="card card-body bg-light mb-3">
        <h1><?php _e('How this part work?'); ?></h1>

        <p><?php _e('Tools system, help you to manage your module, Update database and remove unused information'); ?></p>
        <ul>
            <li><strong><?php _e('Sitemap'); ?></strong> : <?php _e('Manage links on sitemap module'); ?></li>
        </ul>
    </div>
</div>