<?php if ($block['blockEffect']) {
    $this->jQuery();
    $this->js($this->assetModule('js/countdown.js', 'shop'));
}
// language
_b('On sale');
_b('Have discount');
_b('Recommended');
?>
<div class="shop-block">
    <div class="shop-block-sale clearfix">
        <?php foreach ($block['resources'] as $product) { ?>
            <div class="productBox h-product row" itemscope itemtype="http://schema.org/Product">
                <div class="col-md-3">
                    <?php if ($product['image']) { ?>
                        <a itemprop="url" class="u-url <?php echo $this->escape($product['ribbon_class']); ?>" title="<?php echo $this->escape($product['title']); ?>"
                           href="<?php echo $this->escape($product['productUrl']); ?>">
                            <img itemprop="image" class="img-responsive u-photo" src="<?php echo $product['thumbUrl']; ?>"
                                 alt="<?php echo $this->escape($product['title']); ?>"/>
                            <?php if ($block['show-ribbon'] && $product['ribbon']) { ?>
                                <p><span><?php echo $this->escape($product['ribbon']); ?></span></p>
                            <?php } ?>
                        </a>
                    <?php } ?>
                </div>
                <div class="col-md-9">
                    <h4 itemprop="name" class="p-name">
                        <a itemprop="url" title="<?php echo $this->escape($product['title']); ?>"
                           href="<?php echo $this->escape($product['productUrl']); ?>">
                            <?php echo $this->escape($product['title']); ?>
                        </a>
                    </h4>
                    <div class="clearfix">
                        <ul class="list-inline">
                            <li class="pull-left">
                                <div id="product-countdown-timer-<?php echo $this->escape($product['id']); ?>"></div>
                            </li>
                            <?php if (isset($product['price']) && $block['show-price'] && $block['config']['order_active'] == 1) { ?>
                                <li class="pull-right">
                                    <?php if ($product['stock_type'] == 1 || $product['stock_type'] == 5) { ?>
                                        <div class="clearfix" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                                            <div class="productPrice p-price" itemprop="price" content="<?php echo $this->escape($product['price']); ?>">
                                                <meta itemprop="priceCurrency" content="<?php echo $this->escape($product['price_currency']); ?>">
                                                <?php if ($product['price_discount'] && ($product['price_discount'] > $product['price'])) { ?>
                                                    <del class="text-danger"><?php echo $this->escape($product['price_discount_view']); ?></del>
                                                <?php } ?>
                                                <a class="btn btn-success" title="<?php echo $this->escape($product['title']); ?>" href="<?php echo $this->escape($product['productUrl']); ?>"><?php echo $this->escape($product['price_view']); ?></a>
                                            </div>
                                        </div>
                                    <?php } else {?>
                                        <span class="text-danger"><?php echo $this->escape($product['stock_type_view']); ?></span>
                                    <?php } ?>
                                </li>
                            <?php } ?>
                        </ul>
                    </div>
                    <?php $script = <<<'EOT'
$(document).ready(function($) {
	var saleCountdown = new Countdown({
		year   : %s,
		month  : %s,
		day	   : %s,
		hour   : %s,
		minute : %s,
		second : %s,
		width  : %s,
		height : %s,
		rangeHi: "%s",
		target : "product-countdown-timer-%s",
		labelText : {
			second : "%s",
			minute : "%s",
			hour   : "%s",
			day    : "%s",
			month  : "%s",
			year   : "%s"
		},
	});
});
EOT;
                    $script = sprintf(
                        $script,
                        $product['price_time']['year'],
                        $product['price_time']['month'],
                        $product['price_time']['day'],
                        $product['price_time']['hour'],
                        $product['price_time']['minute'],
                        $product['price_time']['second'],
                        250,
                        40,
                        'day',
                        $product['id'],
                        _b('Second'),
                        _b('Minute'),
                        _b('Hour'),
                        _b('Day'),
                        _b('Month'),
                        _b('Year')
                    );
                    $this->footScript()->appendScript($script);
                    ?>
                </div>
            </div>
        <?php } ?>
    </div>
    <?php if ($block['more-show'] && !empty($block['more-link'])) { ?>
        <div class="shop-block-more clearfix">
            <a title="<?php echo _b('More products'); ?>"
               href="<?php echo $block['more-link']; ?>"><?php echo _b('More products'); ?></a>
        </div>
    <?php } ?>
</div>