<?php $this->js($this->assetModule('js/jquery.countdown.min.js', 'shop')); ?>
<div class="shop-block">
    <div class="shop-block-sale clearfix">
        <?php foreach ($block['resources'] as $product) { ?>
            <div class="productBox h-product row" itemscope itemtype="http://schema.org/Product">
                <div class="col-md-3">
                    <?php if ($product['image']) { ?>
                        <a itemprop="url" class="u-url <?php echo $this->escape($product['ribbon_class']); ?>" title="<?php echo $this->escape($product['title']); ?>"
                           href="<?php echo $this->escape($product['productUrl']); ?>">
                            <img itemprop="image" class="img-responsive u-photo" src="<?php echo $product['thumbUrl']; ?>"
                                 alt="<?php echo $this->escape($product['title']); ?>"/>
                            <?php if ($product['ribbon']) { ?>
                                <p><span><?php echo $this->escape($product['ribbon']); ?></span></p>
                            <?php } ?>
                        </a>
                    <?php } ?>
                </div>
                <div class="col-md-9">
                    <h4 itemprop="name" class="p-name">
                        <a itemprop="url" title="<?php echo $this->escape($product['title']); ?>"
                           href="<?php echo $this->escape($product['productUrl']); ?>">
                            <?php echo $this->escape($product['title']); ?>
                        </a>
                    </h4>
                    <div class="clearfix alert alert-danger">
                        <ul class="list-inline product-countdown">
                            <li><?php _e('The time remaining until the end of the offer : '); ?></li>
                            <li><div class="product-countdown-timer-<?php echo $this->escape($product['id']); ?>"></div></li>
                        </ul>
                    </div>
                    <script>
                        $('.product-countdown-timer-<?php echo $this->escape($product['id']); ?>').countdown('<?php echo $this->escape($product['price_time']); ?>', function(event) {
                            var totalHours = event.offset.totalDays * 24 + event.offset.hours;
                            var $this = $(this).html(event.strftime(''
                                + '<span>' + totalHours + '</span> <?php _e('hour'); ?> '
                                + '<span>%M</span> <?php _e('minute'); ?> '
                                + '<span>%S</span> <?php _e('second'); ?>'));
                        });
                    </script>
                    <?php /* <div class="e-description clearfix" itemprop="description">
                        <?php echo $product['text_summary']; ?>
                    </div> */ ?>
                    <?php if (isset($product['price']) && $block['show-price'] && $block['config']['order_active'] == 1) { ?>
                        <?php if ($product['stock_type'] == 1 || $product['stock_type'] == 5) { ?>
                            <div class="clearfix" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                                <div class="productPrice p-price text-right" itemprop="price" content="<?php echo $this->escape($product['price']); ?>">
                                    <meta itemprop="priceCurrency" content="<?php echo $this->escape($product['price_currency']); ?>">
                                    <?php if ($product['price_discount'] && ($product['price_discount'] > $product['price'])) { ?>
                                        <del class="text-danger"><?php echo $this->escape($product['price_discount_view']); ?></del>
                                    <?php } ?>
                                    <a class="btn btn-success" title="<?php echo $this->escape($product['title']); ?>" href="<?php echo $this->escape($product['productUrl']); ?>"><?php echo $this->escape($product['price_view']); ?></a>
                                </div>
                            </div>
                        <?php } else {?>
                            <span class="text-danger"><?php echo $this->escape($product['stock_type_view']); ?></span>
                        <?php } ?>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
    </div>
    <?php if ($block['more-show'] && !empty($block['more-link'])) { ?>
        <div class="shop-block-more clearfix">
            <a title="<?php echo _b('More products'); ?>"
               href="<?php echo $block['more-link']; ?>"><?php echo _b('More products'); ?></a>
        </div>
    <?php } ?>
</div>