<div class="shop-block">
    <div class="shop-block-product clearfix">
    <?php foreach($block['resources'] as $product) { ?>
        <div class="col-sm-4 col-md-3 productBox h-product">
            <div class="thumbnail">
                <?php if($product['image']) { ?>
                <a class="u-photo" title="<?php echo $this->escape($product['title']); ?>" href="<?php echo $this->escape($product['productUrl']); ?>"><img src="<?php echo $product['thumbUrl']; ?>" alt="<?php echo $this->escape($product['title']); ?>" /></a>
                <?php } ?>
                <div class="caption">
                    <h4 class="p-name">
                        <a title="<?php echo $this->escape($product['title']); ?>" href="<?php echo $this->escape($product['productUrl']); ?>"><?php echo $this->escape($product['title']); ?></a>
                    </h4>
                    <?php if(isset($product['price']) && $block['show-price'] && $block['config']['order_method'] != 'inactive') { ?>
                    <div class="clearfix">
                        <?php if($product['stock_type'] == 1 && $product['stock'] > 0) { ?>
                        <div class="pull-left productPrice p-price">
                            <strong><?php echo $this->escape($product['price_view']); ?></strong>
                        </div>
                        <div class="pull-right">
                            <a title="<?php echo $this->escape($product['title']); ?>" href="<?php echo $this->escape($product['productUrl']); ?>" class="btn btn-danger btn-xs"><i class="fa fa-eye"></i> <?php echo _b('View'); ?></a>
                        </div>
                        <?php } elseif ($product['stock_type'] != 1) { ?>
                        <div class="label label-danger">
                            <strong><?php echo $this->escape($product['stock_type_view']); ?></strong>
                        </div>
                        <?php } else { ?>
                        <div class="label label-danger">
                            <strong><?php echo _b('Out of stock'); ?></strong>
                        </div>
                        <?php } ?>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    <?php } ?>
    </div>
    <?php if ($block['more-show'] && !empty($block['more-link'])) { ?>
    <div class="shop-block-more clearfix">
        <a title="<?php echo _b('More products'); ?>" href="<?php echo $block['more-link']; ?>"><?php _b('More products'); ?></a>
    </div>
    <?php } ?>
</div>