<?php if (isset($attribute['all']) && !empty($attribute['all'])) { ?>
    <div class="clearfix">
        <div class="product-attribute">
            <?php foreach ($attribute['all'] as $attributeSingle) { ?>
                <div class="product-attribute-head">
                    <h2><?php echo $attributeSingle['title']; ?></h2>
                </div>
                <table class="table table-striped table-bordered table-sm">
                    <?php foreach ($attributeSingle['info'] as $field) { ?>
                        <?php if (!empty($field['data'])) { ?>
                            <tr>
                                <?php if ($field['type'] == 'text' || $field['type'] == 'select') { ?>
                                    <td><?php echo $field['title']; ?></td>
                                    <td><?php echo $field['data']; ?></td>
                                <?php } elseif ($field['type'] == 'link') { ?>
                                    <td colspan="2"><a
                                                title="<?php echo $field['title']; ?>"
                                                href="<?php echo $field['data']; ?>"
                                                target="_blank"><?php echo $field['title']; ?></a></td>
                                <?php } elseif ($field['type'] == 'file') { ?>
                                    <td colspan="2"><a
                                                title="<?php echo $field['title']; ?>"
                                                href="<?php echo $field['data']; ?>"><?php echo $field['title']; ?></a>
                                    </td>
                                <?php } elseif ($field['type'] == 'currency') { ?>
                                    <td><?php echo $field['title']; ?></td>
                                    <td class="col-lg-3 col-md-9 attribute-body"><?php echo $this->currencyFormat($field['data'], "USD", "en_US"); ?></td>
                                <?php } elseif ($field['type'] == 'date') { ?>
                                    <td><?php echo $field['title']; ?></td>
                                    <td><?php echo $this->dateFormat(
                                            $field['data'], IntlDateFormatter::MEDIUM, IntlDateFormatter::MEDIUM, "en_US"
                                        ); ?></td>
                                <?php } elseif ($field['type'] == 'number') { ?>
                                    <td><?php echo $field['title']; ?></td>
                                    <td><?php echo $this->numberFormat(
                                            $field['data'], NumberFormatter::PATTERN_DECIMAL, NumberFormatter::TYPE_DEFAULT, "en_US"
                                        ); ?></td>
                                <?php } elseif ($field['type'] == 'checkbox') { ?>
                                    <?php if ($field['data']) { ?>
                                        <td colspan="2"><?php echo $field['title']; ?></td>
                                    <?php } ?>
                                <?php } ?>
                            </tr>
                        <?php } ?>
                    <?php } ?>
                </table>
            <?php } ?>
        </div>
    </div>
<?php } ?>