<?php if (isset($category) && !empty($category)) { ?>
    <div class="clearfix categoryItem row" itemscope itemtype="https://schema.org/Brand">
        <?php if (!empty($category['text_description']) || !empty($category['image'])) { ?>
            <div class="clearfix">
                <div class="col-md-12">
                    <h1 class="p-name" itemprop="name"><?php echo $this->escape($category['title']); ?></h1>
                    <hr/>
                    <br/>
                </div>
                <div class="col-md-5">
                    <?php include $this->template('front/gallery'); ?>
                </div>
                <div class="col-md-7">
                    <div class="e-description clearfix" itemprop="description">
                        <?php echo $category['text_description']; ?>
                    </div>
                </div>
            </div>
            <br/>
        <?php } else { ?>
            <div class="col-md-12">
                <div class="page-header">
                    <h1 class="p-name" itemprop="name"><?php echo $this->escape($category['title']); ?></h1>
                </div>
            </div>
        <?php } ?>
    </div>
<?php } ?>
<?php if (isset($categoryItem) && !empty($categoryItem)) { ?>
    <div class="clearfix categoryItemList">
        <ul class="list-inline">
            <li><i class="fa fa-folder"></i> <?php _e('Category'); ?> : </li>
            <?php foreach ($categoryItem as $category) { ?>
                <li itemscope itemtype="https://schema.org/Brand">
                    <a itemprop="url" title="<?php echo $this->escape($category['title']); ?>" href="<?php echo $this->escape($category['url']); ?>">
                        <span class="p-name" itemprop="name"><?php echo $this->escape($category['title']); ?></span>
                    </a>
                </li>
            <?php } ?>
        </ul>
    </div>
<?php } ?>