<?php if ($config['view_category'] && isset($categories) && !empty($categories)) { ?>
    <div class="clearfix categoryList">
        <div class="page-header">
            <h4><?php _e('Category list'); ?></h4>
        </div>
        <div class="clearfix">
            <ul class="list-group">
                <?php foreach ($categories as $categorySingle) { ?>
                    <li class="clearfix list-group-item<?php if (isset($isHomepage) && $isHomepage == 1 && !$categorySingle['image']) { ?><?php } ?><?php if (isset($categorySingle['depth']) && $categorySingle['depth'] > 0) { ?> list-group-item-depth<?php } ?>" itemscope itemtype="https://schema.org/Brand">
                        <a itemprop="url" title="<?php echo $this->escape($categorySingle['title']); ?>"
                           href="<?php echo $this->escape($categorySingle['url']); ?>">
                            <?php if ($categorySingle['image']) { ?>
                                <span class="col-xs-3">
                                <img itemprop="image" class="img-responsive" src="<?php echo $categorySingle['thumbUrl']; ?>"
                                     alt="<?php echo $this->escape($categorySingle['title']); ?>"/>
                                </span>
                            <?php } ?>
                            <span class="p-name" itemprop="name">
                                <?php echo $this->escape($categorySingle['title']); ?>
                            </span>
                        </a>
                    </li>
                <?php } ?>
            </ul>
        </div>
    </div>
    <?php if (isset($isHomepage) && $isHomepage == 1) { ?>
        <br />
    <?php } ?>
<?php } ?>