<?php if ($config['view_category'] && isset($categories) && !empty($categories)) { ?>
    <div class="clearfix categoryList">
        <div class="page-header">
            <h4><?php _e('Category list'); ?></h4>
        </div>
        <div class="clearfix">
            <ul class="list-group">
                <?php foreach ($categories as $categorySingle) { ?>
                    <li class="list-group-item">
                        <a title="<?php echo $this->escape($categorySingle['title']); ?>"
                           href="<?php echo $this->escape($categorySingle['url']); ?>">
                            <?php if ($categorySingle['image']) { ?>
                                <span class="col-xs-3">
                                <img class="img-responsive" src="<?php echo $categorySingle['thumbUrl']; ?>"
                                     alt="<?php echo $this->escape($categorySingle['title']); ?>"/>
                                </span>
                            <?php } ?>
                            <?php echo $this->escape($categorySingle['title']); ?>
                        </a>
                    </li>
                <?php } ?>
            </ul>
        </div>
    </div>
<?php } ?>