<?php if (isset($category) && !empty($category)) { ?>
    <?php
    // Set Open Graph tags for meta
    $this->doctype('HTML5');
    $this->headMeta($this->escape($categorySingle['title']), 'og:title', 'property');
    $this->headMeta($this->escape($categorySingle['categoryUrl']), 'og:url', 'property');
    if (isset($categorySingle['text_summary']) && !empty($categorySingle['text_summary'])) {
        $this->headMeta(_strip($categorySingle['text_summary']), 'og:description', 'property');
    }
    if (!empty($categorySingle['largeUrl'])) {
        $this->headMeta($this->escape($categorySingle['largeUrl']), 'og:image', 'property');
    }
    // Set twitter for meta
    $this->headMeta($this->escape($categorySingle['title']), 'og:title', 'property');
    if (isset($categorySingle['text_summary']) && !empty($categorySingle['text_summary'])) {
        $this->headMeta($this->escape($categorySingle['text_summary']), 'twitter:description');
    }
    if (isset($categorySingle['largeUrl']) && !empty($categorySingle['largeUrl'])) {
        $this->headMeta($this->escape($categorySingle['largeUrl']), 'twitter:image');
    }
    if (isset($location['largeUrl']) && !empty($location['largeUrl'])) {
        $this->headMeta($this->escape($location['largeUrl']), 'twitter:url');
    }
    ?>
    <div class="clearfix categoryItem row" itemscope itemtype="https://schema.org/Brand">
        <?php if (!empty($category['text_description']) || !empty($category['image'])) { ?>
            <div class="clearfix">
                <div class="col-md-12">
                    <div class="page-header">
                        <h1 class="p-name" itemprop="name"><?php echo $this->escape($category['title']); ?></h1>
                    </div>
                </div>
                <!-- <div class="col-md-5">
                    <?php include $this->template('front/gallery'); ?>
                </div>
                <div class="col-md-7">
                    <div class="e-description clearfix" itemprop="description">
                        <?php echo $category['text_description']; ?>
                    </div>
                </div> -->
            </div>
            <br/>
        <?php } else { ?>
            <div class="col-md-12">
                <div class="page-header">
                    <h1 class="p-name" itemprop="name"><?php echo $this->escape($category['title']); ?></h1>
                </div>
            </div>
        <?php } ?>
    </div>
<?php } ?>
<?php if (isset($categoryItem) && !empty($categoryItem)) { ?>
    <div class="clearfix categoryItemList">
        <ul class="list-inline">
            <li><i class="fa fa-folder"></i> <?php _e('Category'); ?> : </li>
            <?php foreach ($categoryItem as $category) { ?>
                <li itemscope itemtype="https://schema.org/Brand">
                    <a itemprop="url" title="<?php echo $this->escape($category['title']); ?>" href="<?php echo $this->escape($category['url']); ?>">
                        <span class="p-name" itemprop="name"><?php echo $this->escape($category['title']); ?></span>
                    </a>
                </li>
            <?php } ?>
        </ul>
    </div>
<?php } ?>