<?php
    $this->css(array(
        $this->assetModule('css/front.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ));
    $this->jQuery();
    $this->backbone();
?>
<div id="shop-cart-page" class="shop">
	<div class="clearfix">
		<div class="row-fluid">
			<div id="cart-list" class="productCart span8">
			<?php foreach($cart['product'] as $product) { ?>
			    <div data-id="<?php echo $product['id']; ?>" id="cart-product-<?php echo $this->escape($product['id']); ?>" class="media">
			    	<a class="pull-left" title="<?php echo $this->escape($product['title']); ?>" href="<?php echo $this->escape($product['productUrl']); ?>">
                		<img src="<?php echo $product['thumbUrl']; ?>" alt="<?php echo $this->escape($product['title']); ?>" class="media-object" />
                	</a>
                	<div class="media-body">
                		<h4 class="media-heading"><?php echo $this->escape($product['title']); ?></h4>
                		<div class="span7">
                			<button id="button-remove-<?php echo $this->escape($product['id']); ?>" type="button" class="btn btn-danger btn-mini js-remove" data-toggle="button" data-link="<?php echo $this->url('', array('action' => 'ajax', 'process' => 'remove', 'product' => $product['id'])); ?>"><i class="icon-ok icon-white"></i> <?php _e('Remove'); ?></button>
                		</div>
                		<div class="span4">
                			<p><strong><?php _e('Price'); ?></strong> : <span class="cart-product-price"><?php echo $this->escape($product['price_view']); ?></span></p>
                			<p><strong><?php _e('Discount'); ?></strong> : <span class="cart-product-discount">0</span></p>
                			<p>
                				<strong><?php _e('Number'); ?></strong> : <span id="cart-product-<?php echo $this->escape($product['id']); ?>-number"><?php echo $this->escape($product['number']); ?> </span>
                				<span class="btn-group">
                					<button id="button-numberplus-<?php echo $this->escape($product['id']); ?>" type="button" class="btn btn-mini js-number" data-id="<?php echo $product['id']; ?>" data-toggle="button" data-link="<?php echo $this->url('', array('action' => 'ajax', 'process' => 'number', 'product' => $product['id'], 'number' => 1)); ?>"><i class="icon-plus"></i></button>
                					<button id="button-numberminus-<?php echo $this->escape($product['id']); ?>" type="button" class="btn btn-mini js-number" data-id="<?php echo $product['id']; ?>" data-toggle="button" data-link="<?php echo $this->url('', array('action' => 'ajax', 'process' => 'number', 'product' => $product['id'], 'number' => -1)); ?>"><i class="icon-minus"></i></button>
                				</span>
                			</p>
                			<p><strong><?php _e('Total'); ?></strong> : <span id="cart-product-<?php echo $this->escape($product['id']); ?>-total"class="label label-success"><?php echo $this->escape($product['total_view']); ?></span></p>
                		</div>
                	</div>
			    </div>
        	<?php } ?>
			</div>
			<div class="infoCart span4 well well-small">
				<h3><?php _e('Invoice'); ?></h3>
				<p><strong><?php _e('Total Price'); ?></strong> : <span id="cart-total-price"><?php echo $this->escape($cart['invoice']['total']['price_view']); ?></span></p>
				<p><strong><?php _e('Total Discount'); ?></strong> : <span id="cart-total-discount"><?php echo $this->escape($cart['invoice']['total']['discount_view']); ?></span></p>
				<p><strong><?php _e('Total Number'); ?></strong> : <span id="cart-total-number"><?php echo $this->escape($cart['invoice']['total']['number']); ?></span></p>
				<p><strong><?php _e('Final Price'); ?></strong> : <span  id="cart-total-total" class="label label-success"><?php echo $this->escape($cart['invoice']['total']['total_price_view']); ?></span></p>

			</div>
		</div>
		<div class="form-actions">
			<div class="pull-left">
				<a class="btn" title="<?php _e('Back to Shoping'); ?>" href="<?php echo $this->url('', array('controller' => 'index')); ?>"><?php _e('Back to Shoping'); ?></a>
				<a class="btn" title="<?php _e('Refresh cart'); ?>" href="<?php echo $this->url('', array('action' => 'cart')); ?>"><?php _e('Refresh cart'); ?></a>
				<a class="btn" title="<?php _e('Empty cart'); ?>" href="<?php echo $this->url('', array('action' => 'empty')); ?>"><?php _e('Empty cart'); ?></a>
			</div>
			<div class="pull-right">
				<a class="btn btn-primary" title="<?php _e('Next'); ?>" href="<?php echo $this->url('', array('action' => 'index')); ?>"><?php _e('Next'); ?></a>
			</div>
		</div>
	</div>
</div>
<script>
(function($){
    var page = {
        el: $('#shop-cart-page'),
        $: function(selector) {
            return this.el.find(selector);
        },
        init: function() {
            this.$('.js-number').click(_.bind(this.numberAction, this));
            this.$('.js-remove').click(_.bind(this.removeAction, this));
        },
        removeAction: function(e) {
            var tar = $(e.target);
            if (confirm('<?php echo _a('Are you sure to delete this product from your cart? '); ?>')) {
                $.getJSON(tar.attr("data-link")).done(function(result){
                    if(result.ajaxStatus==1){
                        if (result.actionName=='remove'){
                            $('#cart-product-' + result.id).slideUp('fast');
                        }
                    }
                });
            }
        },
        numberAction: function(e) {
            var tar = $(e.target);
            this.updateAction(tar);
            $.getJSON(tar.attr("data-link")).done(function(result){
                if(result.ajaxStatus==1){
                    if (result.actionName=='number'){
                        if (result.actionStatus==1){
                            $('#cart-product-' + result.id + '-number').html(result.actionNumber);
                            $('#cart-product-' + result.id + '-total').html(result.actionTotal);
                        } else {
                            alert(result.message);
                        }
                    }
                }
            });
            this.updateAction(tar);
        },
        updateAction: function(e) {
            $.getJSON("<?php echo $this->url('', array('action' => 'cartAjax')); ?>").done(function(result){
                // Update total
                $('#cart-total-price').html(result.total.price_view);
                $('#cart-total-discount').html(result.total.discount_view);
                $('#cart-total-number').html(result.total.number);
                $('#cart-total-total').html(result.total.total_price_view);
            });
        },
    }
    page.init();
})(jQuery)
</script>