<?php
    $this->css(array(
        $this->assetModule('css/front.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ));
    $this->jQuery();
    $this->bootstrap('js/bootstrap.min.js');
    $this->backbone();
?>
<div id="shop-cart-page" class="clearfix">
	<div class="clearfix">
        <div class="clearfix cartBox">
            <div id="cart-list" class="col-md-8 cartProduct">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php _e('List of prodcuts on cart'); ?></div>
                    <table class="table">
                        <thead></thead>
		                <?php foreach($cart['product'] as $product) { ?>
                        <tr data-id="<?php echo $product['id']; ?>" id="cart-product-<?php echo $this->escape($product['id']); ?>">
                            <td class="col-md-4 cartProductTitle">
                                <h4 class="media-heading"><?php echo $this->escape($product['title']); ?></h4>
                                <a title="<?php echo $this->escape($product['title']); ?>" href="<?php echo $this->escape($product['productUrl']); ?>"><img src="<?php echo $product['thumbUrl']; ?>" alt="<?php echo $this->escape($product['title']); ?>" class="media-object" /></a>
                            </td>
                            <td class="col-md-8 cartProductInfo">
                                <p><strong><?php _e('Price'); ?></strong> : <span class="cart-product-price"><?php echo $this->escape($product['price_view']); ?></span></p>
                                <p><strong><?php _e('Discount'); ?></strong> : <span class="cart-product-discount">0</span></p>
                                <p>
                                    <strong><?php _e('Number'); ?></strong> : <span id="cart-product-<?php echo $this->escape($product['id']); ?>-number"><?php echo $this->escape($product['number']); ?> </span>
                                    <span class="btn-group">
                                        <button id="button-numberplus-<?php echo $this->escape($product['id']); ?>" type="button" class="btn btn-xs js-number" data-id="<?php echo $product['id']; ?>" data-toggle="button" data-link="<?php echo $this->url('', array('action' => 'basketAjax', 'process' => 'number', 'product' => $product['id'], 'number' => 1)); ?>"><i class="fa fa-plus"></i></button>
                                        <button id="button-numberminus-<?php echo $this->escape($product['id']); ?>" type="button" class="btn btn-xs js-number" data-id="<?php echo $product['id']; ?>" data-toggle="button" data-link="<?php echo $this->url('', array('action' => 'basketAjax', 'process' => 'number', 'product' => $product['id'], 'number' => -1)); ?>"><i class="fa fa-minus"></i></button>
                                    </span>
                                </p>
                                <p><strong><?php _e('Total'); ?></strong> : <span id="cart-product-<?php echo $this->escape($product['id']); ?>-total"class="label label-success"><?php echo $this->escape($product['total_view']); ?></span></p>
                                <p><button id="button-remove-<?php echo $this->escape($product['id']); ?>" type="button" class="btn btn-danger btn-xs js-remove" data-toggle="button" data-link="<?php echo $this->url('', array('action' => 'basketAjax', 'process' => 'remove', 'product' => $product['id'])); ?>"><i class="fa fa-ok fa fa-white"></i> <?php _e('Remove'); ?></button></p>
                            </td>
                        </tr>
                        <?php } ?>
                    </table>
                    <div class="panel-footer clearfix">
                        <div class="pull-left">
                            <a class="btn btn-primary" title="<?php _e('Back to Shoping'); ?>" href="<?php echo Pi::url($this->url('', array('controller' => 'index'))); ?>"><?php _e('Back to Shoping'); ?></a>
                            <a class="btn btn-primary" title="<?php _e('Refresh cart'); ?>" href="<?php echo Pi::url($this->url('', array('action' => 'cart'))); ?>"><?php _e('Refresh cart'); ?></a>
                            <a class="btn btn-primary" title="<?php _e('Empty cart'); ?>" href="<?php echo Pi::url($this->url('', array('action' => 'empty'))); ?>"><?php _e('Empty cart'); ?></a>
                        </div>
                        <div class="pull-right">
                            <a class="btn btn-primary" title="<?php _e('Next'); ?>" href="<?php echo Pi::url($this->url('', array('action' => 'information'))); ?>"><?php _e('Next'); ?></a>
                        </div>
                    </div>
                </div>
			</div>
            <div class="col-md-4 ">
                <div data-spy="affix" class="cartInfo">
                    <div class="panel panel-default">
                        <div class="panel-heading"><?php _e('Pre Invoice'); ?></div>
                        <div class="panel-body">
                            <p><strong><?php _e('Total Price'); ?></strong> : <span id="cart-total-price"><?php echo $this->escape($cart['invoice']['total']['price_view']); ?></span></p>
                            <p><strong><?php _e('Total Discount'); ?></strong> : <span id="cart-total-discount"><?php echo $this->escape($cart['invoice']['total']['discount_view']); ?></span></p>
                            <p><strong><?php _e('Total Number'); ?></strong> : <span id="cart-total-number"><?php echo $this->escape($cart['invoice']['total']['number']); ?></span></p>
                            <p><strong><?php _e('Total Shipping'); ?></strong> : <span id="cart-total-shipping"><?php echo $this->escape($cart['invoice']['total']['shipping_view']); ?></span></p>
                            <p><strong><?php _e('Final Price'); ?></strong> : <span  id="cart-total-total" class="label label-success"><?php echo $this->escape($cart['invoice']['total']['total_price_view']); ?></span></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
	</div>
</div>
<script>
(function($){
    var page = {
        el: $('#shop-cart-page'),
        $: function(selector) {
            return this.el.find(selector);
        },
        init: function() {
            this.$('.js-number').click(_.bind(this.numberAction, this));
            this.$('.js-remove').click(_.bind(this.removeAction, this));
        },
        removeAction: function(e) {
            var tar = $(e.target);
            if (confirm('<?php echo _e('Are you sure to delete this product from your cart? '); ?>')) {
                $.getJSON(tar.attr("data-link")).done(function(result){
                    if(result.ajaxStatus==1){
                        if (result.actionName=='remove'){
                            $('#cart-product-' + result.id).slideUp('fast');
                        }
                    }
                });
            }
            this.updateAction(tar);
        },
        numberAction: function(e) {
            var tar = $(e.target);
            this.updateAction(tar);
            $.getJSON(tar.attr("data-link")).done(function(result){
                if(result.ajaxStatus==1){
                    if (result.actionName=='number'){
                        if (result.actionStatus==1){
                            $('#cart-product-' + result.id + '-number').html(result.actionNumber);
                            $('#cart-product-' + result.id + '-total').html(result.actionTotal);
                        } else {
                            alert(result.message);
                        }
                    }
                }
            });
            this.updateAction(tar);
        },
        updateAction: function(e) {
            var url = "<?php echo Pi::url($this->url('', array('action' => 'cartAjax'))); ?>";
            $.getJSON(url).done(function(result){
                if (result.status == 1) {
                    $('#cart-total-price').html(result.data.price);
                    $('#cart-total-discount').html(result.data.discount);
                    $('#cart-total-number').html(result.data.number);
                    $('#cart-total-total').html(result.data.total);
                }
            });
        },
    }
    page.init();
})(jQuery)
</script>