<?php
    $this->css(array(
        $this->assetModule('css/front.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ));
    $this->jQuery();
    $this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div class="shop">
	<div class="clearfix">
		<div class="row-fluid">
			<div id="cart-list" class="productCart span8">
			<?php foreach($cart['product'] as $product) { ?>
			    <div id="cart-product-<?php echo $this->escape($product['id']); ?>" class="media">
			    	<a class="pull-left" title="<?php echo $this->escape($product['title']); ?>" href="<?php echo $this->escape($product['productUrl']); ?>">
                		<img src="<?php echo $product['thumbUrl']; ?>" alt="<?php echo $this->escape($product['title']); ?>" class="media-object" />
                	</a>
                	<div class="media-body">
                		<h4 class="media-heading"><?php echo $this->escape($product['title']); ?></h4>
                		<div class="span7">
                			<button id="button-remove-<?php echo $this->escape($product['id']); ?>" type="button" class="btn btn-danger btn-mini" data-toggle="button" data-link="<?php echo $this->url('', array('action' => 'ajax', 'process' => 'remove', 'product' => $product['id'])); ?>"><i class="icon-ok icon-white"></i> <?php _e('Remove'); ?></button>
                		</div>
                		<div class="span4">
                			<p><strong><?php _e('Price'); ?></strong> : <?php echo $this->escape($product['price_view']); ?></p>
                			<p><strong><?php _e('Discount'); ?></strong> : 0 </p>
                			<p>
                				<strong><?php _e('Number'); ?></strong> : <span id="cart-product-<?php echo $this->escape($product['id']); ?>-number"><?php echo $this->escape($product['number']); ?> </span>
                				<span class="btn-group">
                					<button id="button-numberplus-<?php echo $this->escape($product['id']); ?>" type="button" class="btn btn-mini" data-toggle="button" data-link="<?php echo $this->url('', array('action' => 'ajax', 'process' => 'number', 'product' => $product['id'], 'number' => 1)); ?>"><i class="icon-plus"></i></button>
                					<button id="button-numberminus-<?php echo $this->escape($product['id']); ?>" type="button" class="btn btn-mini" data-toggle="button" data-link="<?php echo $this->url('', array('action' => 'ajax', 'process' => 'number', 'product' => $product['id'], 'number' => -1)); ?>"><i class="icon-minus"></i></button>
                				</span>
                			</p>
                			<p><strong><?php _e('Total'); ?></strong> : <span class="label label-success"><?php echo $this->escape($product['total_view']); ?></span></p>
                		</div>
                	</div>
			    </div>
        	<?php } ?>
			</div>
			<div class="infoCart span4 well well-small">
				<h3><?php _e('Invoice'); ?></h3>
				<p><strong><?php _e('Total Price'); ?></strong> : <?php echo $this->escape($cart['invoice']['total']['price_view']); ?></p>
				<p><strong><?php _e('Total Discount'); ?></strong> : <?php echo $this->escape($cart['invoice']['total']['discount_view']); ?> </p>
				<p><strong><?php _e('Total Number'); ?></strong> : <?php echo $this->escape($cart['invoice']['total']['number']); ?></p>
				<p><strong><?php _e('Final Price'); ?></strong> : <span class="label label-success"><?php echo $this->escape($cart['invoice']['total']['total_price_view']); ?></span></p>

			</div>
		</div>
		<div class="form-actions">
			<div class="pull-left">
				<a class="btn" title="<?php _e('Back to Shoping'); ?>" href="<?php echo $this->url('', array('controller' => 'index')); ?>"><?php _e('Back to Shoping'); ?></a>
				<a class="btn" title="<?php _e('Refresh cart'); ?>" href="<?php echo $this->url('', array('action' => 'cart')); ?>"><?php _e('Refresh cart'); ?></a>
				<a class="btn" title="<?php _e('Empty cart'); ?>" href="<?php echo $this->url('', array('action' => 'empty')); ?>"><?php _e('Empty cart'); ?></a>
			</div>
			<div class="pull-right">
				<a class="btn btn-primary" title="<?php _e('Next'); ?>" href="#"><?php _e('Next'); ?></a>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" >
(function($){
    $("#cart-list").on("click","button",function(){
        systemMessage.wait("<?php _e('In process'); ?>");
        $.getJSON($(this).attr("data-link")).done(function(result){
            if(result.ajaxStatus==1){
            	if (result.actionName=='remove'){
            		$('#cart-product-' + result.id).slideUp('fast');
            	}
            	if (result.actionName=='number'){
            		if (result.actionStatus==1){
            			$('#cart-product-' + result.id + '-number').html(result.actionNumber);
            		}
            	}
                systemMessage.succ(result.message);
            }else{
                systemMessage.fail(result.message);
            }
        });
    });
})(jQuery)
</script>