<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix row company-dashboard">
    <div class="col-md-3 col-12">
        <?php $sideActive = 'shopDashboard'; ?>
        <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
    </div>
    <div class="col-md-9 col-12">
        <h1 class="mb-3"><?php echo $this->escape($title); ?></h1>

        <div class="clearfix row mb-3">
            <div class="col-xl-3 col-sm-6 py-2">
                <div class="card bg-success text-white h-100">
                    <div class="card-body bg-success">
                        <div class="rotate">
                            <i class="fa fa-user fa-4x"></i>
                        </div>
                        <h4 class="display-6"><?php _e('List of videos'); ?></h4>
                        <h6 class="text-uppercase text-right">
                            <a href="<?php echo Pi::url($this->url('', ['controller' => 'dashboard', 'action' => 'list'])); ?>" class="text-white">
                                <?php _e('View'); ?>
                            </a>
                        </h6>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 py-2">
                <div class="card text-white bg-danger h-100">
                    <div class="card-body bg-danger">
                        <div class="rotate">
                            <i class="fa fa-list fa-4x"></i>
                        </div>
                        <h4 class="display-6"><?php _e('Add new video'); ?></h4>
                        <h6 class="text-uppercase text-right">
                            <a href="<?php echo Pi::url($this->url('', ['controller' => 'dashboard', 'action' => 'add'])); ?>" class="text-white">
                                <?php _e('View'); ?>
                            </a>
                        </h6>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 py-2">
                <div class="card text-white bg-info h-100">
                    <div class="card-body bg-info">
                        <div class="rotate">
                            <i class="fa fa-twitter fa-4x"></i>
                        </div>
                        <h4 class="display-6"><?php _e('List of orders'); ?></h4>
                        <h6 class="text-uppercase text-right">
                            <a href="<?php echo Pi::url($this->url('', ['controller' => 'dashboard', 'action' => 'sale'])); ?>" class="text-white">
                                <?php _e('View'); ?>
                            </a>
                        </h6>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 py-2">
                <div class="card text-white bg-warning h-100">
                    <div class="card-body">
                        <div class="rotate">
                            <i class="fa fa-share fa-4x"></i>
                        </div>
                        <h4 class="display-6"><?php _e('Company dashboard'); ?></h4>
                        <h6 class="text-uppercase text-right">
                            <a href="<?php echo Pi::url($this->url('', ['module' => 'company'])); ?>" class="text-white">
                                <?php _e('View'); ?>
                            </a>
                        </h6>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>