<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix row">
    <div class="col-md-3 col-12">
        <?php $sideActive = 'shopDashboard'; ?>
        <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
    </div>
    <div class="col-md-9 col-12">
        <h1 class="mb-3"><?php echo $this->escape($title); ?></h1>
        <?php if (isset($orderList) && !empty($orderList)) { ?>
            <table class="table table-striped table-bordered table-hover table-sm mt-3 mb-3">
                <tr>
                    <th class="text-center"><?php _e('Code'); ?></th>
                    <th class="text-center"><?php _e('Product / service'); ?></th>
                    <th class="text-center"><?php _e('Time'); ?></th>
                    <th class="text-center"><?php _e('Order status'); ?></th>
                    <th class="text-center"><?php _e('Price incl. VAT'); ?></th>
                    <th class="text-center"><?php _e('To paid incl. VAT'); ?></th>
                </tr>
                <?php foreach ($orderList as $order) { ?>
                    <tr>
                        <td class="text-center"><?php echo $this->escape($order['code']); ?></td>
                        <td class="text-center">
                            <?php $productsList = [];
                            foreach ($order['products'] as $product) {
                                $productsList[] = $product['details']['title'];
                            }
                            echo implode('<br/>', $productsList); ?>
                        </td>
                        <td class="text-center"><?php echo $this->escape($order['time_create_view']); ?></td>
                        <td class="text-center">
                            <span class="badge <?php echo $this->escape($order['shortLabel']); ?>"><?php echo $this->escape($order['shortStatus']); ?></span>
                        </td>
                        <td class="text-center"><?php echo $this->escape($order['total_price_view']); ?></td>
                        <td class="text-center"><?php echo $this->escape($order['to_paid_view']); ?></td>
                    </tr>
                <?php } ?>
            </table>
        <?php } else { ?>
            <div class="alert alert-danger 3 mt-3" role="alert">
                <?php _e('You did not yet place an order yet'); ?>
            </div>
        <?php } ?>
    </div>
</div>