<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix row">
    <div class="col-md-3 col-12">
        <?php $sideActive = 'shopDashboard'; ?>
        <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
    </div>
    <div class="col-md-9 col-12">
        <h1 class="mb-3"><?php echo $this->escape($title); ?></h1>
        <?php if (isset($productList) && !empty($productList)) { ?>
            <table class="table table-striped table-bordered table-hover table-sm mt-3 mb-3 text-center">
                <tr>
                    <th><?php _e('Image'); ?></th>
                    <th><?php _e('Title'); ?></th>
                    <th><?php _e('Hits'); ?></th>
                    <th><?php _e('Price'); ?></th>
                    <th><?php _e('Sale'); ?></th>
                    <th><?php _e('Action'); ?></th>
                </tr>
                <?php foreach ($productList as $product) { ?>
                    <?php if ($product['status'] == 1) {
                        $htmlClass = '';
                    } elseif ($product['status'] == 5) {
                        $htmlClass = 'table-danger';
                    } else {
                        $htmlClass = 'table-warning';
                    } ?>
                    <tr class="<?php echo $htmlClass; ?>">
                        <td>
                            <img style="height: 75px" class="img-fluid" src="<?php echo $this->escape($video['thumbUrl']); ?>" alt="<?php echo $this->escape($video['title']); ?>">
                        </td>
                        <td><?php echo $this->escape($product['title']); ?></td>
                        <td><?php echo $this->escape(_number($product['hits'])); ?> <?php _e('Views'); ?></td>
                        <td><?php echo $this->escape($product['price_view']); ?></td>
                        <td><?php echo $this->escape(_number($product['sold'])); ?> <?php _e('Sold'); ?></td>
                        <td>
                            <a class="btn btn-primary btn-sm" title="<?php _e('Manage'); ?>" href="<?php echo $this->url('', ['action' => 'manage', 'slug' => $product['slug']]); ?>" target="_blank">
                                <i class="fas fa-edit"></i> <?php _e('Manage'); ?>
                            </a>
                            <?php if ($product['status'] == 1) { ?>
                                <a class="btn btn-success btn-sm" title="<?php _e('View'); ?>" href="<?php echo $product['productUrl']; ?>" target="_blank">
                                    <i class="fas fa-eye"></i> <?php _e('View'); ?>
                                </a>
                            <?php } ?>
                        </td>
                    </tr>
                <?php } ?>
            </table>
        <?php } else { ?>
            <div class="alert alert-danger 3 mt-3" role="alert">
                <?php _e('Product list is empty, perhaps you still didn\'t add any product or your selected filter didn\'t have any result'); ?>
            </div>
        <?php } ?>
    </div>
</div>