<?php
// Get local
$locale = Pi::service('i18n')->getLocale();
$rtl    = (in_array($locale, ['fa', 'ar'])) ? 'true' : 'false';

$iconOwlLeft = '<i class="owl-prev fas fa-angle-left"></i>';
$iconOwlRight = '<i class="owl-next fas fa-angle-right"></i>';
$script1
    = <<<'EOT'
    $('.gallery').each(function() {
    	$(this).magnificPopup({
       		delegate: 'a',
       		type: 'image',
       		gallery: {
      			enabled:true
       		}
    	});
	});
EOT;
$script2
    = <<<'EOT'
    $(document).ready(function($) {
		$('.owl-carousel').owlCarousel({
    		loop:false,
    		rtl:%s,
    		margin:3,
    		nav:true,
    		autoplay:true,
    		dots:false,
    		autoplayTimeout:6000,
    		autoplayHoverPause:true,
    		navText: ['%s', '%s'],
    		responsive:{
        		0:{items:2},
        		600:{items:2},
        		1000:{items:3}
    		}
		})
    });
EOT;
$script2 = sprintf($script2, $rtl, $iconOwlLeft, $iconOwlRight);
$this->jQuery(
    [
        'extension/jquery.magnific-popup.min.js',
        'extension/magnific-popup.css',
        'extension/owl.carousel.min.js',
        'extension/owl.carousel.css',
    ]
);
$this->footScript()->appendScript($script1);
$this->footScript()->appendScript($script2);
?>
<div class="product-image gallery clearfix card">
    <?php if (isset($productSingle['main_image']) && !empty($productSingle['main_image'])) { ?>
        <div class="product-image-main text-center clearfix u-photo">
            <a class="u-photo <?php echo $this->escape($productSingle['ribbon_class']); ?>"
               href="<?php echo $this->escape($productSingle['largeUrl']); ?>"
               title="<?php echo $this->escape($productSingle['title']); ?>">
                <img class="card-img-top img-fluid" itemprop="image"
                     src="<?php echo $this->escape($productSingle['mediumUrl']); ?>"
                     alt="<?php echo $this->escape($productSingle['title']); ?>"/>
                <?php if ($productSingle['ribbon']) { ?>
                    <p><span><?php echo $this->escape($productSingle['ribbon']); ?></span></p>
                <?php } ?>
            </a>
        </div>
    <?php } elseif (isset($category['image']) && !empty($category['image'])) { ?>
        <div class="product-image-main text-center clearfix u-photo">
            <a class="u-photo" href="<?php echo $this->escape($category['largeUrl']); ?>"
               title="<?php echo $this->escape($category['title']); ?>">
                <img class="card-img-top img-fluid" itemprop="image" src="<?php echo $this->escape($category['mediumUrl']); ?>"
                     alt="<?php echo $this->escape($category['title']); ?>"/>
            </a>
        </div>
    <?php } ?>
    <?php if (isset($productSingle['additional_images']) && !empty($productSingle['additional_images'])) { ?>
        <?php $galleryImages = Pi::api('doc', 'media')->getGalleryLinkData($productSingle['additional_images'], [intval($config['image_itemh']), intval($config['image_thumbh'])], null, null, false, [], 'shop') ?>
        <?php if ($galleryImages) { ?>
        <div class="owl-carousel product-image-attach text-center clearfix">
            <?php foreach ($galleryImages as $key => $galleryImage) { ?>
                <a class="u-photo" href="<?php echo $galleryImage['resized_url'][intval($config['image_itemh'])]; ?>" title="<?php echo $this->escape($galleryImage['title']); ?><?php if ($galleryImage['copyright']) echo ' - ' . $galleryImage['copyright'] ?>">
                    <img class="card-img-top img-fluid" itemprop="image" src="<?php echo $galleryImage['resized_url'][intval($config['image_thumbh'])]; ?>" alt="<?php echo $this->escape($galleryImage['title']); ?>"/>
                </a>
            <?php } ?>
        </div>
    <?php } ?>
    <?php } ?>
</div>
