<?php
// Get local
$locale = Pi::service('i18n')->getLocale();
$rtl = (in_array($locale, array('fa', 'ar'))) ? 'true' : 'false';

$iconOwlLeft = '<i class="owl-prev fa fa-angle-left"></i>';
$iconOwlRight = '<i class="owl-next fa fa-angle-right"></i>';
$script1 = <<<'EOT'
    $('.gallery').each(function() {
    	$(this).magnificPopup({
       		delegate: 'a',
       		type: 'image',
       		gallery: {
      			enabled:true
       		}
    	});
	});
EOT;
$script2 = <<<'EOT'
    $(document).ready(function($) {
		$('.owl-carousel').owlCarousel({
    		loop:false,
    		rtl:%s,
    		margin:3,
    		nav:true,
    		autoplay:true,
    		dots:false,
    		autoplayTimeout:6000,
    		autoplayHoverPause:true,
    		navText: ['%s', '%s'],
    		responsive:{
        		0:{items:2},
        		600:{items:2},
        		1000:{items:3}
    		}
		})
    });
EOT;
$script2 = sprintf($script2, $rtl, $iconOwlLeft, $iconOwlRight);
$this->jQuery(array(
    'extension/jquery.magnific-popup.min.js',
    'extension/magnific-popup.css',
    'extension/owl.carousel.min.js',
    'extension/owl.carousel.css',
));
$this->footScript()->appendScript($script1);
$this->footScript()->appendScript($script2);
?>
<div class="product-image gallery clearfix thumbnail">
    <?php if (isset($productItem['image']) && !empty($productItem['image'])) { ?>
        <div class="product-image-main text-center clearfix u-photo">
            <a class="u-photo <?php echo $this->escape($productItem['ribbon_class']); ?>" href="<?php echo $this->escape($productItem['largeUrl']); ?>"
               title="<?php echo $this->escape($productItem['title']); ?>">
                <img class="img-responsive" itemprop="image" src="<?php echo $this->escape($productItem['mediumUrl']); ?>"
                     alt="<?php echo $this->escape($productItem['title']); ?>"/>
                <?php if ($productItem['ribbon']) { ?>
                    <p><span><?php echo $this->escape($productItem['ribbon']); ?></span></p>
                <?php } ?>
            </a>
        </div>
    <?php } elseif (isset($category['image']) && !empty($category['image'])) { ?>
        <div class="product-image-main text-center clearfix u-photo">
            <a class="u-photo" href="<?php echo $this->escape($category['largeUrl']); ?>"
               title="<?php echo $this->escape($category['title']); ?>">
                <img class="img-responsive" itemprop="image" src="<?php echo $this->escape($category['mediumUrl']); ?>"
                     alt="<?php echo $this->escape($category['title']); ?>"/>
            </a>
        </div>
    <?php } ?>
    <?php if (isset($attach['image']) && !empty($attach['image'])) { ?>
        <div class="owl-carousel product-image-attach text-center clearfix">
            <?php foreach ($attach['image'] as $image) { ?>
                <a class="u-photo" href="<?php echo $this->escape($image['largeUrl']); ?>"
                   title="<?php echo $this->escape($image['title']); ?>">
                    <img class="img-responsive" itemprop="image" src="<?php echo $this->escape($image['mediumUrl']); ?>"
                         alt="<?php echo $this->escape($image['title']); ?>"/>
                </a>
            <?php } ?>
        </div>
    <?php } ?>
</div>