<?php
$scriptMenu
            = <<<'EOT'
$(function() {
    var json = '%s';
    $('#category-tree-view').treeview({
        levels: 1,
        data: json,
        enableLinks: true,
        expandIcon: 'fa fa-plus',
		collapseIcon: 'fa fa-minus',
		emptyIcon: 'fa',
		checkedIcon: 'fa fa-check-square-o',
		uncheckedIcon: 'fa fa-square-o',
    });
});
EOT;
$scriptMenu = sprintf(
    $scriptMenu,
    $categoriesJson
);

// Load header files
$this->jQuery();
$this->js($this->assetModule('js/bootstrap-treeview.min.js'));
$this->css($this->assetModule('css/front.css'));
$this->footScript()->appendScript($scriptMenu);
?>
<div class="clearfix shop-homepage-widget">
    <div class="clearfix row">
        <div class="col-md-3 col-12">
            <div class="clearfix category-list">
                <div class="page-header">
                    <h4><?php _e('Category list'); ?></h4>
                </div>
                <div class="clearfix">
                    <div id="category-tree-view"></div>
                </div>
            </div>
        </div>
        <div class="shop-widget col-md-9 col-12">
            <div class="page-header">
                <h1><?php echo $productTitleH1; ?></h1>
            </div>
            <?php if (!empty($config['text_description_index'])) { ?>
                <?php echo $config['text_description_index']; ?>
            <?php } ?>
            <div class="clearfix shop-widget-list">
                <div class="shop-widget-single">
                    <?php echo $this->widget('search-search'); ?>
                </div>
            </div>
            <?php if (!empty($config['homepage_widget'])) { ?>
                <?php $blocks = explode("|", $config['homepage_widget']); ?>
                <div class="clearfix shop-block-list">
                    <?php foreach ($blocks as $block) { ?>
                        <?php $block = $this->block($block); ?>
                        <div class="shop-block-single">
                            <div class="pi-block">
                                <div class="pi-block-title">
                                    <h3><?php echo $block['title']; ?></h3>
                                </div>
                                <div class="pi-block-content">
                                    <?php echo $block['content']; ?>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            <?php } ?>
        </div>
    </div>
</div>