<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix shop-homepage-category">
    <div class="mb-3">
        <h1><?php echo $productTitleH1; ?></h1>
    </div>
    <?php if (isset($brandList) && !empty($brandList)) { ?>
        <div class="category-list clearfix">
            <?php foreach ($brandList as $category) { ?>
                <div class="col-lg-3 col-md-3 col-12" itemscope itemtype="https://schema.org/Brand">
                    <div class="card">
                        <?php if ($category['image']) { ?>
                            <a itemprop="url" href="<?php echo $this->escape($category['categoryUrl']); ?>" title="<?php echo $this->escape($category['title']); ?>">
                                <img itemprop="image" src="<?php echo $this->escape($category['mediumUrl']); ?>" alt="<?php echo $this->escape($category['title']); ?>" class="card-img-top">
                            </a>
                        <?php } ?>
                        <div class="card-body">
                            <h3 class="p-name card-title" itemprop="name">
                                <a href="<?php echo $this->escape($category['categoryUrl']); ?>" title="<?php echo $this->escape($category['title']); ?>">
                                    <?php echo $this->escape($category['title']); ?>
                                </a>
                            </h3>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
    <?php } ?>
</div>