<?php if (isset($productList) && !empty($productList)) { ?>
<div class="productList clearfix">
	<?php if (isset($productTitleH1) && !empty($productTitleH1)) { ?>
	<div class="page-header">
		<h1><?php echo $productTitleH1; ?></h1>
	</div>
	<?php } elseif (isset($productTitleH2) && !empty($productTitleH2)) { ?>
	<div class="page-header">
		<h2><?php echo $productTitleH2; ?></h2>
	</div>
	<?php } ?>
	<?php if (!empty($config['text_description_index']) && isset($showIndexDesc) && $showIndexDesc == 1 && isset($page) && $page == 1) { ?>
	<div class="well shopIndexDescription">
		<?php echo $config['text_description_index']; ?>
	</div>
	<?php } ?>
	<?php foreach($productList as $product) { ?>
	<?php include $this->template('front/box'); ?>
	<?php } ?>
</div>
<div class="clearfix"></div>
<?php } ?>