<?php if(isset($productItem['price']) && $config['view_price']) { ?>
<div class="productPrice well clearfix">
    <?php if($productItem['stock'] > 0) { ?>
        <div class="pull-left">
        <?php if ($productItem['price_discount'] && ($productItem['price_discount'] > $productItem['price'])) { ?>
            <strong class="text-danger">
             <del><?php echo $this->escape($productItem['price_discount_view']); ?></del>
            </strong>
        <?php } ?>
            <strong class="text-success">
            <?php echo $this->escape($productItem['price_view']); ?>
            </strong>
            <span><a title="<?php echo $this->escape($productItem['title']); ?>" href="<?php echo $this->escape($productItem['cartUrl']); ?>" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> <?php _e('Add To cart'); ?></a></span>
        </div>
        <div class="pull-right">
            <span class="label label-info">
            <?php echo $this->escape($productItem['stock']); ?> <?php _e('in stock'); ?>
            </span>
        </div>
    <?php } else { ?>
        <div class="text-error"><strong><?php _e('Finished'); ?></strong></div>
    <?php } ?>
</div>
<?php } ?>