<?php if (isset($questionValid) && $questionValid == 'notValid') { ?>
<?php $this->css($this->assetModule('css/front.css')); ?>
    <div class="page-header">
        <h1><?php _e('Ask question about product'); ?></h1>
    </div>
    <p><?php echo $this->escape($questionMessage); ?></p>
    <?php echo $this->form($questionForm, 'vertical');?>
<?php } elseif (isset($config['view_question']) && $config['view_question']) { ?>
    <div class="clearfix">
        <button type="button" class="btn btn-primary btn-xl" data-toggle="modal" data-target="#questionModal"><?php _e('Ask question'); ?></button>
        <div class="modal fade" id="questionModal" tabindex="-1" role="dialog" aria-labelledby="questionModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="questionModalLabel"><?php _e('Ask question about product'); ?></h4>
                    </div>
                    <div class="modal-body">
                        <p><?php echo $this->escape($questionMessage); ?></p>
                        <?php echo $this->form($questionForm, 'vertical');?>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>