<?php if(isset($productItem['price']) && $config['order_active']) { ?>
    <div class="productPrice clearfix">
        <?php if ($config['order_stock'] == 'never') { ?>
            <div class="clearfix">
                <div class="col-md-8 col-sm-6 col-xs-12">
                    <?php include $this->template('front/product-order'); ?>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <strong><?php _e('Price'); ?> : </strong>
                    <?php if ($productItem['price_discount'] && ($productItem['price_discount'] > $productItem['price'])) { ?>
                        <div class="text-danger">
                            <del><?php echo $this->escape($productItem['price_discount_view']); ?></del>
                        </div>
                    <?php } ?>
                    <span class="p-price"><?php echo $this->escape($productItem['price_view']); ?></span>
                </div>
            </div>
        <?php } elseif ($config['order_stock'] == 'manual') { ?>
            <?php if($productItem['stock_type'] == 1) { ?>
                <div class="clearfix">
                    <div class="col-md-8 col-sm-6 col-xs-12">
                        <?php include $this->template('front/product-order'); ?>
                    </div>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <div class="clearfix">
                            <strong><?php _e('Stock status'); ?> : </strong>
                            <span class="text-success"><?php _e('In stock'); ?></span>
                        </div>
                        <strong><?php _e('Price'); ?> : </strong>
                        <?php if ($productItem['price_discount'] && ($productItem['price_discount'] > $productItem['price'])) { ?>
                            <div class="text-danger">
                                <del><?php echo $this->escape($productItem['price_discount_view']); ?></del>
                            </div>
                        <?php } ?>
                        <span class="p-price"><?php echo $this->escape($productItem['price_view']); ?></span>
                    </div>
                </div>
            <?php } else { ?>
                <div class="clearfix">
                    <strong><?php _e('Stock status'); ?> : </strong>
                    <span class="text-danger"><?php echo $this->escape($productItem['stock_type_view']); ?></span>
                </div>
            <?php } ?>
        <?php } elseif ($config['order_stock'] == 'product') { ?>
            <?php if($productItem['stock'] > 0) { ?>
                <div class="clearfix">
                    <div class="col-md-8 col-sm-6 col-xs-12">
                        <?php include $this->template('front/product-order'); ?>
                    </div>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <div class="clearfix">
                            <strong><?php _e('Stock status'); ?> : </strong>
                            <span class="text-success"><?php _e('In stock'); ?></span>
                        </div>
                        <strong><?php _e('Price'); ?> : </strong>
                        <?php if ($productItem['price_discount'] && ($productItem['price_discount'] > $productItem['price'])) { ?>
                            <div class="text-danger">
                                <del><?php echo $this->escape($productItem['price_discount_view']); ?></del>
                            </div>
                        <?php } ?>
                        <span class="p-price"><?php echo $this->escape($productItem['price_view']); ?></span>
                    </div>
                </div>
            <?php } else { ?>
                <div class="clearfix">
                    <strong><?php _e('Stock status'); ?> : </strong>
                    <span class="text-danger"><?php _e('Out of stock'); ?></span>
                </div>
            <?php } ?>
        <?php } elseif ($config['order_stock'] == 'property') { ?>
            <div class="clearfix">
                <div class="col-md-8 col-sm-6 col-xs-12">
                    <?php include $this->template('front/product-order'); ?>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <strong><?php _e('Price'); ?> : </strong>
                    <?php if ($productItem['price_discount'] && ($productItem['price_discount'] > $productItem['price'])) { ?>
                        <div class="text-danger">
                            <del><?php echo $this->escape($productItem['price_discount_view']); ?></del>
                        </div>
                    <?php } ?>
                    <span class="p-price"><?php echo $this->escape($productItem['price_view']); ?></span>
                </div>
            </div>
        <?php } ?>
    </div>
<?php } ?>