<?php if (isset($productRelated) && !empty($productRelated)) { ?>
    <?php
    $this->jQuery(array(
        'extension/owl.carousel.min.js',
        'extension/owl.carousel.css',
    ));
    $this->js($this->assetModule('js/owl-carousel-config-list.js'));
    $shopListBoxSize = 'col-sm-12 col-md-12';
    ?>
    <div class="product-related clearfix">
        <div class="page-header">
            <h2><?php _e('Related Products'); ?></h2>
        </div>
        <div class="product-list clearfix">
            <div class="owl-carousel-list clearfix">
                <?php foreach ($productRelated as $product) { ?>
                    <?php include $this->template('front/product-box'); ?>
                <?php } ?>
            </div>
        </div>
    </div>
<?php } ?>
