<?php
    $this->css($this->assetModule('css/front.css'));
	$this->jQuery();
	$this->js($this->assetModule('js/lightbox.js'));
	$this->footScript()->appendScript("$(function() {
		$('.gallery a').lightBox({
	        imageLoading: '" . $this->assetModule('image/lightbox-ico-loading.gif') . "',
	        imageBtnClose:'" . $this->assetModule('image/lightbox-btn-close.gif') . "',
	        imageBtnNext:'" . $this->assetModule('image/lightbox-btn-next.gif') . "',
	        imageBtnPrev:'" . $this->assetModule('image/lightbox-btn-prev.gif') . "',
	        imageBlank:'" . $this->assetModule('image/lightbox-blank.gif') . "',
	        overlayOpacity: 0.6,
		    containerResizeSpeed: 350,
		});
	});");
	$this->css($this->assetModule('css/lightbox.css'));
?>
<div class="shop">
	<div class="productItem row-fluid">
		<div class="productTitle span12"><h3><?php echo $this->escape($productItem['title']); ?></h3></div>
		<div class="productInformation clearfix">
			<div class="productImage gallery span4">
				<a href="<?php echo $productItem['largeUrl']; ?>" title="<?php echo $this->escape($productItem['title']); ?>"><img class="img-polaroid" src="<?php echo $productItem['mediumUrl']; ?>" alt="<?php echo $this->escape($productItem['title']); ?>" /></a>
			</div>
			<div class="span8">
                <?php include $this->template('front/price'); ?>
				<?php include $this->template('front/extra'); ?>
				<div class="productSocial">
		    	<?php if($config['social_facebook']) { ?>
		    		<span class="productFacebook"><?php echo $this->facebook(); ?></span>
		    		<?php } ?>
		    		<?php if($config['social_twitter']) { ?>
		    		<span class="productTwitter"><?php echo $this->twitter(); ?></span>
		    		<?php } ?>
		    		<?php if($config['social_gplus']) { ?>
		    		<span class="productPlusone"><?php echo $this->plusone(); ?></span>
		    		<?php } ?>
	    		</div>
			</div>
		</div>
		<div class="productBody">
			<?php include $this->template('front/category'); ?>
			<?php include $this->template('front/tag'); ?>
			<div class="productText well">
				<strong><?php _e('Description'); ?></strong>
				<div class="productSummary"><?php echo $productItem['summary']; ?></div>
				<div class="productDescription"><?php echo $productItem['description']; ?></div>
			</div>
		</div>
	</div>
	<?php include $this->template('front/attach'); ?>
	<?php include $this->template('front/review'); ?>
	<?php include $this->template('front/related'); ?>
	<?php include $this->template('front/list'); ?>
</div>