<?php
// Load angular custom js
$script = <<<'EOT'
var app = angular.module('shop', ['angularUtils.directives.dirPagination']);
app.controller('listdata',function($scope, $http){
    $scope.products = [];
    $http.get("%s").success(function(response){
        $scope.products = response;
    });
    $scope.sort = function(keyname){
        $scope.sortKey = keyname;
        //$scope.reverse = !$scope.reverse;
    }
});
EOT;
$script = sprintf(
    $script,
    $filterUrl
);
// Load header files
$this->jQuery();
$this->angular();
$this->js($this->assetModule('js/dirPagination.js'));
$this->css($this->assetModule('css/front.css'));
$this->footScript()->appendScript($script);
// Set box site
switch ($config['view_column']) {
    case 1:
        $shopBoxSize = 'col-xs-12 col-sm-12 col-md-12';
        break;

    case 2:
        $shopBoxSize = 'col-xs-12 col-sm-12 col-md-6';
        break;

    case 3:
        $shopBoxSize = 'col-xs-12 col-sm-12 col-md-4';
        break;

    case 4:
        $shopBoxSize = 'col-xs-12 col-sm-12 col-md-3';
        break;

    case 5:
        $shopBoxSize = 'col-xs-12 col-sm-12 col-md-2';
        break;
}
?>
<div class="clearfix row">
    <div class="col-sm-12 col-md-3">
        <?php include $this->template('front/category-side'); ?>
        <div class="shop-search-form clearfix">
            <div class="page-header">
                <h4><?php _e('Search'); ?></h4>
            </div>
            <form>
                <div class="form-group">
                    <label><?php _e('Title'); ?></label>
                    <input type="text" ng-model="filterTitle" class="form-control">
                </div>
                <div class="form-group">
                    <label><?php _e('Marketable'); ?></label>
                    <select ng-model="filterMarketable" class="form-control">
                        <option value=""><?php _e('All'); ?></option>
                        <option value="1"><?php _e('Marketable'); ?></option>
                        <option value="0"><?php _e('Not marketable'); ?></option>
                    </select>
                </div>
                <?php $filterNameArray = array(); ?>
                <?php foreach ($filterList as $singleFilter) { ?>
                    <?php if ($singleFilter['type'] == 'select') { ?>
                        <?php
                        $filterName = 'filter' . $singleFilter['name'];
                        $filterNameArray[] = array(
                            'fieldName' => $singleFilter['name'],
                            'filterName' => $filterName
                        );
                        ?>
                        <div class="form-group">
                            <label><?php echo $singleFilter['title']; ?></label>
                            <select ng-model="<?php echo $filterName; ?>" class="form-control">
                                <option value=""><?php _e('All'); ?></option>
                                <?php foreach ($singleFilter['value']['data'] as $valueData) { ?>
                                    <?php if (!empty($valueData)) { ?>
                                        <option ng-click="sort('<?php echo $valueData; ?>')"><?php echo $valueData; ?></option>
                                    <?php } ?>
                                <?php } ?>
                            </select>
                        </div>
                    <?php } elseif ($singleFilter['type'] == 'text') { ?>
                        <div class="form-group">
                            <?php
                            $filterName = 'filter' . $singleFilter['name'];
                            $filterNameArray[] = array(
                                'fieldName' => $singleFilter['name'],
                                'filterName' => $filterName
                            );
                            ?>
                            <label><?php echo $singleFilter['title']; ?></label>
                            <input type="text" ng-model="<?php echo $filterName; ?>" class="form-control">
                        </div>
                    <?php } ?>
                <?php } ?>
                <!-- <div class="form-group">
                    <label>Sort</label>
                    <select class="form-control">
                        <option ng-click="sort('-id')">ID</option>
                        <option ng-click="sort('title')">Title</option>
                        <option ng-click="sort('-price')">Price</option>
                    </select>
                </div> -->
            </form>
        </div>
    </div>
    <div class="col-sm-12 col-md-9" ng-controller="listdata">
        <?php include $this->template('front/category'); ?>
        <?php include $this->template('front/special'); ?>
        <div class="clearfix">
            <div class="productList clearfix">
                <?php if (isset($productTitleH1) && !empty($productTitleH1)) { ?>
                    <div class="page-header">
                        <h1><?php echo $productTitleH1; ?></h1>
                    </div>
                <?php } elseif (isset($productTitleH2) && !empty($productTitleH2)) { ?>
                    <div class="page-header">
                        <h2><?php echo $productTitleH2; ?></h2>
                    </div>
                <?php } ?>
                <?php if (!empty($config['text_description_index']) && isset($showIndexDesc) && $showIndexDesc == 1 && isset($page) && $page == 1) { ?>
                    <div class="well shopIndexDescription">
                        <?php echo $config['text_description_index']; ?>
                    </div>
                <?php } ?>
                <div dir-paginate="product in products|orderBy:sortKey|filter: {<?php if (!empty($filterNameArray)) { ?><?php foreach ($filterNameArray as $filterNameSingle) { ?><?php echo $filterNameSingle['fieldName'] ?> : <?php echo $filterNameSingle['filterName'] ?>,<?php } ?><?php } ?> title : filterTitle, marketable : filterMarketable } |itemsPerPage:<?php echo $config['view_perpage']; ?>"
                     class="<?php echo $shopBoxSize; ?> productBox h-product" itemscope itemtype="http://schema.org/Product">
                    <div class="thumbnail">
                        <a itemprop="url" class="u-photo" title="{{product.title}}"
                           href="{{product.productUrl}}"><img
                                itemprop="image" src="{{product.thumbUrl}}"
                                alt="{{product.title}}"/></a>
                        <div class="caption">
                            <h3 class="p-name" itemprop="name">
                                <a title="{{product.title}}"
                                   href="{{product.productUrl}}">
                                    {{product.title}}
                                </a>
                            </h3>
                            <?php if ($config['order_active']) { ?>
                                <div class="clearfix" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                                    <?php if ($config['order_stock'] == 'never') { ?>
                                        <div class="clearfix">
                                            <div class="clearfix">
                                                <strong><?php _e('Stock status'); ?> : </strong>
                                                <span class="text-success" itemprop="availability" href="http://schema.org/InStock"><?php _e('In stock'); ?></span>
                                            </div>
                                            <strong><?php _e('Price'); ?> : </strong>
                                            <div ng-if="{{product.price_discount_has}} == 1">
                                                <span class="text-danger">
                                                    <del>{{product.price_discount_view}}</del>
                                                </span>
                                            </div>
                                            <span class="p-price" itemprop="price" content="{{product.price}}">{{product.price_view}}</span>
                                            <meta itemprop="priceCurrency" content="{{product.price_currency}}">
                                        </div>
                                    <?php } elseif ($config['order_stock'] == 'manual') { ?>
                                        <div ng-if="product.stock_type == 1">
                                            <div class="clearfix">
                                                <div class="clearfix">
                                                    <strong><?php _e('Stock status'); ?> : </strong>
                                                    <span class="text-success" itemprop="availability" href="http://schema.org/InStock"><?php _e('In stock'); ?></span>
                                                </div>
                                                <strong><?php _e('Price'); ?> : </strong>
                                                <div ng-if="product.price_discount_has == 1">
                                                    <span class="text-danger">
                                                        <del>{{product.price_discount_view}}</del>
                                                    </span>
                                                </div>
                                                <span class="p-price" itemprop="price" content="{{product.price}}">{{product.price_view}}</span>
                                                <meta itemprop="priceCurrency" content="{{product.price_currency}}">
                                            </div>
                                        </div>
                                        <div ng-if="product.stock_type != 1">
                                            <div class="clearfix">
                                                <strong><?php _e('Stock status'); ?> : </strong>
                                                <span class="text-danger">{{product.stock_type_view}}</span>
                                            </div>
                                        </div>
                                    <?php } elseif ($config['order_stock'] == 'product') { ?>
                                        <div ng-if="product.stock > 0">
                                            <div class="clearfix">
                                                <div class="clearfix">
                                                    <strong><?php _e('Stock status'); ?> : </strong>
                                                    <span class="text-success" itemprop="availability" href="http://schema.org/InStock"><?php _e('In stock'); ?></span>
                                                </div>
                                                <strong><?php _e('Price'); ?> : </strong>
                                                <div ng-if="product.price_discount_has == 1">
                                                    <span class="text-danger">
                                                        <del>{{product.price_discount_view}}</del>
                                                    </span>
                                                </div>
                                                <span class="p-price" itemprop="price" content="{{product.price}}">{{product.price_view}}</span>
                                                <meta itemprop="priceCurrency" content="{{product.price_currency}}">
                                            </div>
                                        </div>
                                        <div ng-if="product.stock == 0">
                                            <div class="clearfix">
                                                <strong><?php _e('Stock status'); ?> : </strong>
                                                <span class="text-danger"><?php _e('Out of stock'); ?></span>
                                            </div>
                                        </div>
                                    <?php } elseif ($config['order_stock'] == 'property') { ?>
                                        <div class="clearfix">
                                            <strong><?php _e('Price'); ?> : </strong>
                                            <div ng-if="product.price_discount_has == 1">
                                                <span class="text-danger">
                                                    <del>{{product.price_discount_view}}</del>
                                                </span>
                                            </div>
                                            <span class="p-price" itemprop="price" content="{{product.price}}">{{product.price_view}}</span>
                                            <meta itemprop="priceCurrency" content="{{product.price_currency}}">
                                        </div>
                                    <?php } ?>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="paginator">
                <dir-pagination-controls
                    max-size="<?php echo $config['view_perpage']; ?>"
                    direction-links="true"
                    boundary-links="true">
                </dir-pagination-controls>
            </div>
        </div>
    </div>
</div>