<?php
$this->css($this->assetModule('css/front.css'));
// Set Open Graph tags for meta
$this->doctype('HTML5');
$this->headMeta($this->escape($productItem['title']), 'og:title', 'property');
$this->headMeta($this->escape($productItem['productUrl']), 'og:url', 'property');
if (isset($productItem['text_summary']) && !empty($productItem['text_summary'])) {
    $this->headMeta(_strip($productItem['text_summary']), 'og:description', 'property');
}
if (isset($productItem['largeUrl']) && !empty($productItem['largeUrl'])) {
    $this->headMeta($this->escape($productItem['largeUrl']), 'og:image', 'property');
}
// Set twitter for meta
$this->headMeta($this->escape($productItem['title']), 'twitter:title');
if (isset($productItem['text_summary']) && !empty($productItem['text_summary'])) {
    $this->headMeta(_strip($productItem['text_summary']), 'twitter:description');
}
if (isset($productItem['largeUrl']) && !empty($productItem['largeUrl'])) {
    $this->headMeta($this->escape($productItem['largeUrl']), 'twitter:image');
}
?>
<div class="clearfix">
    <div class="product-page h-product clearfix" itemscope itemtype="https://schema.org/Product">
        <div class="col-xs-4">
            <?php include $this->template('front/gallery'); ?>
        </div>
        <div class="col-xs-8">
            <div class="product-title clearfix">
                <h1 class="p-name pull-left" itemprop="name">
                    <?php echo $this->escape($productItem['title']); ?>
                </h1>
                <?php if (!empty($productItem['subtitle'])) { ?>
                <h2 class="pull-right">
                    <?php echo $this->escape($productItem['subtitle']); ?>
                </h2>
                <?php } ?>
            </div>
            <div class="product-info-box productSummary e-description clearfix" itemprop="description">
                <?php echo $productItem['text_summary_view']; ?>
            </div>
            <div class="product-price-box clearfix">
                <?php include $this->template('front/product-price'); ?>
            </div>
            <div class="product-info-box clearfix">
                <?php include $this->template('front/attribute'); ?>
            </div>
            <div class="clearfix product-info-list">
                <ul class="list-inline">
                    <?php if (!empty($vote)) { ?>
                        <li class="col-xs-2">
                            <?php include $this->template('votebar.phtml', 'front', 'vote'); ?>
                        </li>
                    <?php } ?>
                    <?php if (!empty($favourite)) { ?>
                        <li class="col-xs-2">
                            <?php include $this->template('favouritebar.phtml', 'front', 'favourite'); ?>
                        </li>
                    <?php } ?>
                    <?php if ($config['view_question']) { ?>
                        <li class="col-xs-2">
                            <?php include $this->template('front/product-question'); ?>
                        </li>
                    <?php } ?>
                    <?php if ($config['social_sharing']) { ?>
                        <li class="col-xs-6">
                            <div class="socialSharing">
                                <?php echo $this->socialSharing(
                                    $config['social_sharing'],
                                    $this->escape($productItem['title']),
                                    $this->escape($productItem['productUrl']),
                                    $this->escape($productItem['largeUrl'])
                                ); ?>
                            </div>
                        </li>
                    <?php } ?>
                </ul>
            </div>
        </div>
        <div class="col-xs-12">
            <div class="product-info-box productDescription p-review clearfix" itemprop="description">
                <?php echo $productItem['text_description']; ?>
            </div>
            <?php if ($config['view_description_product'] && !empty($categorySingle['text_description'])) { ?>
                <div class="product-info-box categoryDescription p-review clearfix" itemprop="description">
                    <?php echo $categorySingle['text_description']; ?>
                </div>
            <?php } ?>
            <div class="product-info-box clearfix">
                <div class="p-brand p-category" itemprop="brand category">
                    <?php include $this->template('front/category'); ?>
                </div>
                <div class="p-category" itemprop="category">
                    <?php include $this->template('front/tag'); ?>
                </div>
            </div>
            <?php if (isset($videoServiceList) && !empty($videoServiceList)) { ?>
                <div class="productMedia">
                    <?php include $this->template('video-service.phtml', 'front', 'video'); ?>
                </div>
            <?php } ?>
            <div class="productMedia">
                <?php include $this->template('front/attach-audio'); ?>
                <?php include $this->template('front/attribute-audio'); ?>
                <?php include $this->template('front/attach-video'); ?>
                <?php include $this->template('front/attribute-video'); ?>
            </div>
            <div class="productAttach">
                <?php include $this->template('front/attach'); ?>
            </div>
        </div>
    </div>
    <?php include $this->template('front/product-list-related'); ?>
    <?php include $this->template('front/product-list-category'); ?>
</div>