<?php if (isset($saleList) && !empty($saleList)) { ?>
    <?php
    /* $this->jQuery(array(
        'extension/owl.carousel.min.js',
        'extension/owl.carousel.css',
    ));
    $this->js($this->assetModule('js/owl-carousel-config-list.js')); */
    $shopListBoxSize = 'col-md-3 col-12';
    ?>
    <div class="product-sale clearfix">
        <div class="page-header">
            <h2><?php _e('Sale products'); ?></h2>
        </div>
        <div class="product-list clearfix">
            <div class="owl-carousel-list clearfix">
                <?php foreach ($saleList as $product) { ?>
                    <?php include $this->template('front/product-box'); ?>
                <?php } ?>
            </div>
        </div>
    </div>
<?php } ?>

