<?php if (isset($productCategory) && !empty($productCategory)) { ?>
    <?php
    /* $this->jQuery(array(
        'extension/owl.carousel.min.js',
        'extension/owl.carousel.css',
    ));
    $this->js($this->assetModule('js/owl-carousel-config-list.js')); */
    $shopListBoxSize = 'col-lg-3 col-md-3 col-12';
    ?>
    <div class="product-category clearfix">
        <div class="mb-3">
            <h2><?php _e('Products on this category'); ?></h2>
        </div>
        <div class="product-list row">
            <?php foreach ($productCategory as $product) { ?>
                <?php include $this->template('front/product-box'); ?>
            <?php } ?>
        </div>
    </div>
<?php } ?>