<?php if (!isset($shopListBoxSize) || empty($shopListBoxSize)) {
    $shopListBoxSize = 'col-md-4';
} ?>
<div class="<?php echo $shopListBoxSize; ?> product-box h-product" itemscope itemtype="https://schema.org/Product">
    <div class="thumbnail">
        <?php if ($product['image']) { ?>
            <a itemprop="url" class="u-url <?php echo $this->escape($product['ribbon_class']); ?>" title="<?php echo $this->escape($product['title']); ?>"
               href="<?php echo $this->escape($product['productUrl']); ?>"><img
                    itemprop="image" class="img-responsive u-photo" src="<?php echo $product['thumbUrl']; ?>"
                    alt="<?php echo $this->escape($product['title']); ?>"/>
                <?php if ($product['ribbon']) { ?>
                    <p><span><?php echo $this->escape($product['ribbon']); ?></span></p>
                <?php } ?>
            </a>
        <?php } ?>
        <div class="caption">
            <h3 class="p-name" itemprop="name">
                <a title="<?php echo $this->escape($product['title']); ?>"
                   href="<?php echo $this->escape($product['productUrl']); ?>">
                    <?php echo $this->escape($product['title']); ?>
                </a>
            </h3>
            <?php if (isset($product['price']) && $config['order_active']) { ?>
                <div class="clearfix" itemprop="offers" itemscope itemtype="https://schema.org/Offer">
                    <div class="clearfix">
                        <?php if (!empty($product['price_title'])) { ?>
                            <strong><?php echo $this->escape($config['view_price_title']); ?> : </strong>
                            <span><?php echo $this->escape($product['price_title']); ?></span>
                        <?php } ?>
                        <?php if (isset($product['price_discount']) && ($product['price_discount'] > $product['price'])) { ?>
                            <span class="text-danger">
                                    <del><?php echo $this->escape($product['price_discount_view']); ?></del>
                                </span>
                        <?php } ?>
                        <span class="p-price" itemprop="price" content="<?php echo $this->escape($product['price']); ?>"><?php echo $this->escape($product['price_view']); ?></span>
                        <?php if(isset($product['price_currency'])) { ?>
                            <meta itemprop="priceCurrency" content="<?php echo $this->escape($product['price_currency']); ?>">
                        <?php } ?>
                    </div>
                    <?php /* if ($config['order_stock'] == 'never') { ?>
                        <div class="clearfix">
                            <?php if (!empty($product['price_title'])) { ?>
                                <strong><?php echo $this->escape($config['view_price_title']); ?> : </strong>
                                <span><?php echo $this->escape($product['price_title']); ?></span>
                            <?php } ?>
                            <div class="clearfix">
                                <span class="text-success" itemprop="availability" href="https://schema.org/InStock"><?php _e('In stock'); ?></span>
                            </div>
                            <?php if (isset($product['price_discount']) && ($product['price_discount'] > $product['price'])) { ?>
                                <span class="text-danger">
                                    <del><?php echo $this->escape($product['price_discount_view']); ?></del>
                                </span>
                            <?php } ?>
                            <span class="p-price" itemprop="price" content="<?php echo $this->escape($product['price']); ?>"><?php echo $this->escape($product['price_view']); ?></span>
                            <?php if(isset($product['price_currency'])) { ?>
                                <meta itemprop="priceCurrency" content="<?php echo $this->escape($product['price_currency']); ?>">
                            <?php } ?>
                        </div>
                    <?php } elseif ($config['order_stock'] == 'manual') { ?>
                        <?php if ($product['stock_type'] == 1 || $product['stock_type'] == 5) { ?>
                            <div class="clearfix">
                                <?php if (!empty($product['price_title'])) { ?>
                                    <strong><?php echo $this->escape($config['view_price_title']); ?> : </strong>
                                    <span><?php echo $this->escape($product['price_title']); ?></span>
                                <?php } ?>
                                <div class="clearfix">
                                    <span class="text-success" itemprop="availability" href="https://schema.org/InStock"><?php echo $this->escape($product['stock_type_view']); ?></span>
                                </div>
                                <?php if (isset($product['price_discount']) && ($product['price_discount'] > $product['price'])) { ?>
                                    <span class="text-danger">
                                        <del><?php echo $this->escape($product['price_discount_view']); ?></del>
                                    </span>
                                <?php } ?>
                                <span class="p-price" itemprop="price" content="<?php echo $this->escape($product['price']); ?>"><?php echo $this->escape($product['price_view']); ?></span>
                                <?php if(isset($product['price_currency'])) { ?>
                                    <meta itemprop="priceCurrency" content="<?php echo $this->escape($product['price_currency']); ?>">
                                <?php } ?>
                            </div>
                        <?php } else { ?>
                            <div class="clearfix">
                                <span class="text-danger"><?php echo $this->escape($product['stock_type_view']); ?></span>
                            </div>
                        <?php } ?>
                    <?php } elseif ($config['order_stock'] == 'product') { ?>
                        <?php if ($product['stock'] > 0) { ?>
                            <div class="clearfix">
                                <?php if (!empty($product['price_title'])) { ?>
                                    <strong><?php echo $this->escape($config['view_price_title']); ?> : </strong>
                                    <span><?php echo $this->escape($product['price_title']); ?></span>
                                <?php } ?>
                                <div class="clearfix">
                                    <span class="text-success" itemprop="availability" href="https://schema.org/InStock"><?php _e('In stock'); ?></span>
                                </div>
                                <?php if (isset($product['price_discount']) && ($product['price_discount'] > $product['price'])) { ?>
                                    <span class="text-danger">
                                        <del><?php echo $this->escape($product['price_discount_view']); ?></del>
                                    </span>
                                <?php } ?>
                                <span class="p-price" itemprop="price" content="<?php echo $this->escape($product['price']); ?>"><?php echo $this->escape($product['price_view']); ?></span>
                                <?php if(isset($product['price_currency'])) { ?>
                                    <meta itemprop="priceCurrency" content="<?php echo $this->escape($product['price_currency']); ?>">
                                <?php } ?>
                            </div>
                        <?php } else { ?>
                            <div class="clearfix">
                                <span class="text-danger"><?php _e('Out of stock'); ?></span>
                            </div>
                        <?php } ?>
                    <?php } elseif ($config['order_stock'] == 'property') { ?>
                        <div class="clearfix">
                            <?php if (isset($product['price_discount']) && ($product['price_discount'] > $product['price'])) { ?>
                                <span class="text-danger">
                                    <del><?php echo $this->escape($product['price_discount_view']); ?></del>
                                </span>
                            <?php } ?>
                            <span class="p-price" itemprop="price" content="<?php echo $this->escape($product['price']); ?>"><?php echo $this->escape($product['price_view']); ?></span>
                            <?php if(isset($product['price_currency'])) { ?>
                                <meta itemprop="priceCurrency" content="<?php echo $this->escape($product['price_currency']); ?>">
                            <?php } ?>
                        </div>
                    <?php } */ ?>
                </div>
            <?php } ?>
        </div>
    </div>
</div>