<?php
    $this->css($this->assetModule('css/front.css'));
	$this->jQuery();
	$this->js($this->assetModule('js/jquery.magnific-popup.min.js'));
	$this->footScript()->appendScript("$('.gallery').each(function() {
    	$(this).magnificPopup({
        	delegate: 'a',
        	type: 'image',
        	gallery: {
          	enabled:true
        	}
    	});
	});");
	$this->css($this->assetModule('css/magnific-popup.css'));
?>
<div class="shop">
	<div class="productItem">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title"><?php echo $this->escape($productItem['title']); ?></h3>
			</div>
			<div class="panel-body">
				<div class="productInformation clearfix">
					<div class="productImage gallery col-md-4">
						<a href="<?php echo $productItem['largeUrl']; ?>" title="<?php echo $this->escape($productItem['title']); ?>"><img src="<?php echo $productItem['mediumUrl']; ?>" alt="<?php echo $this->escape($productItem['title']); ?>" /></a>
					</div>
					<div class="col-md-4">
						<?php include $this->template('front/extra'); ?>
					</div>
					<div class="col-md-4">
                		<?php include $this->template('front/price'); ?>
                		<?php if (!empty($vote)) { include $this->template('module/vote:front/votebar'); } ?>
                		<?php if (!empty($favourite)) { include $this->template('module/favourite:front/favouritebar'); } ?>
					</div>
				</div>
				<div class="productBody">
					<div class="productText">
						<strong><?php _e('Description'); ?></strong>
						<div class="productSummary"><?php echo $productItem['summary']; ?></div>
						<div class="productDescription"><?php echo $productItem['description']; ?></div>
						<?php include $this->template('front/category'); ?>
			    		<?php include $this->template('front/tag'); ?>
			    		<div class="social-list">
							<ul class="list-inline">
								<?php if($config['social_facebook']) { ?><li class="social-facebook"><?php echo $this->facebook(); ?></li><?php } ?>
								<?php if($config['social_twitter']) { ?><li class="social-twitter"><?php echo $this->twitter(); ?></li><?php } ?>
								<?php if($config['social_gplus']) { ?><li class="social-gplus"><?php echo $this->plusone(); ?></li><?php } ?>
							</ul>
	    				</div>
					</div>
				</div>
        	</div>
		</div>
	</div>
	<?php include $this->template('front/attach'); ?>
	<?php include $this->template('front/review'); ?>
	<?php include $this->template('front/related'); ?>
	<?php include $this->template('front/list'); ?>
</div>