<?php
// Load header files
$this->jQuery();
$this->angular(array(
    'angular-route.js',
    'ui-bootstrap-custom-tpls-0.7.0.js',
    'pi.js',
    'i18n'
));
$this->js($this->assetModule('js/bootstrap-treeview.min.js'));
$this->js($this->assetModule('js/rzslider.min.js'));
$this->css(array(
    $this->assetModule('css/front.css'),
    $this->assetModule('css/rzslider.min.css'),
));
?>
<div class="row clearfix pi-item-angular">
    <div class="ajax-spinner">
        <img src="<?php echo $this->assetModule('image/spinner.gif'); ?>" class="ajax-spinner-loader"/>
    </div>
    <div class="col-md-12 col-xs-12">
        <?php include $this->template('front/category'); ?>
    </div>
    <div ng-view></div>
</div>
<script>
    angular
        .module('shop', ['ngRoute', 'ui.bootstrap', 'pi', 'rzModule'])
        .constant('config', {
            pageType: '<?php echo $pageType; ?>',
            urlRoot: '<?php echo Pi::url($this->url('', array('controller' => 'json', 'action' => 'var'))); ?>'.replace(/var\/?$/, ''),
            urlCompare: '<?php echo Pi::url($this->url('', array('controller' => 'compare'))); ?>',
            assetRoot: '<?php echo $this->assetModule('ng-template/front/', '', false); ?>',
            categoryJson: '<?php echo $categoriesJson; ?>',
            categorySlug: '<?php echo isset($category) ? $category['slug'] : '' ?>',
            tagTerm: '<?php echo isset($tag) ? $tag : '' ?>',
            priceFilter: '<?php echo $config['view_price_filter']; ?>',
            t: {
                COMPARE_MESSAGE_1: '<?php _e('You put this product on compare list before'); ?>',
                COMPARE_MESSAGE_2: '<?php _e('You can add just 5 products on compare list'); ?>',
                SEARCH: '<?php _e('Search on this group'); ?>',
                TITLE: '<?php _e('Title'); ?>',
                ALL: '<?php _e('All'); ?>',
                MARKETABLE: '<?php _e('Marketable'); ?>',
                NOT_MARKETABLE: '<?php _e('Not marketable'); ?>',
                CATEGORY_LIST: '<?php _e('Category list'); ?>',
                COMPARE_PRODUCTS: '<?php _e('Compare products'); ?>',
                COMPARE: '<?php _e('Compare'); ?>',
                CLOSE: '<?php _e('Close'); ?>',
                NONE_PRODUCT: '<?php _e('No product'); ?>',
                MIN_PRICE : '<?php _e('From'); ?>',
                MAX_PRICE : '<?php _e('To'); ?>',
                PRICE_SYMBOL : '<?php _e('$'); ?>',
                ADD_TO_CART : '<?php _e('Add to cart'); ?>',
            },
       });
</script>
<script src="<?php echo $this->assetModule('js/product-list.js'); ?>"></script>