<?php if (isset($productSingle['price']) && $config['order_active']) { ?>
    <div class="clearfix row" itemprop="offers" itemscope itemtype="https://schema.org/Offer">
        <?php if (isset($productSingle['price_sale']) && $productSingle['price_sale']) { ?>
            <?php $this->js($this->assetModule('js/countdown.js')); ?>
            <div class="col-lg-12 col-md-12 col-12">
                <ul class="list-inline bg-info product-countdown clearfix">
                    <li class="list-inline-item"><?php _e('The time remaining until the end of the offer : '); ?></li>
                    <li class="list-inline-item pull-right">
                        <div id="saleCountdown"></div>
                    </li>
                </ul>
                <?php $script
                    = <<<'EOT'
$(document).ready(function($) {
	var saleCountdown = new Countdown({
		year   : %s,
		month  : %s,
		day	   : %s,
		hour   : %s,
		minute : %s,
		second : %s,
		width  : %s,
		height : %s,
		rangeHi: "%s",
		target : "%s",
		labelText : {
			second : "%s",
			minute : "%s",
			hour   : "%s",
			day    : "%s",
			month  : "%s",
			year   : "%s"
		},
	});
});
EOT;
                $script = sprintf(
                    $script,
                    $productSingle['price_time']['year'],
                    $productSingle['price_time']['month'],
                    $productSingle['price_time']['day'],
                    $productSingle['price_time']['hour'],
                    $productSingle['price_time']['minute'],
                    $productSingle['price_time']['second'],
                    300,
                    40,
                    'day',
                    'saleCountdown',
                    __('Second'),
                    __('Minute'),
                    __('Hour'),
                    __('Day'),
                    __('Month'),
                    __('Year')
                );
                $this->footScript()->appendScript($script);
                ?>
            </div>
        <?php } ?>
        <?php if ($config['order_stock'] == 'never') { ?>
            <div class="clearfix row">
                <div class="col-lg-5 col-md-5 col-12">
                    <ul class="list-unstyled">
                        </li>
                        <?php if (!empty($productSingle['brand'])) { ?>
                            <li>
                                <div class="product-brand">
                                    <strong><?php _e('Brand'); ?> : </strong>
                                    <a itemprop="brand" href="<?php echo $this->escape($category['brandUrl']); ?>"
                                       title="<?php echo $this->escape($category['brandTitle']); ?>">
                                        <?php echo $this->escape($category['brandTitle']); ?>
                                    </a>
                                </div>
                            </li>
                        <?php } ?>
                        <li>
                            <div class="product-stock">
                                <strong><?php _e('Stock status'); ?> : </strong>
                                <span class="text-success" itemprop="availability"
                                      href="https://schema.org/InStock"><?php _e('In stock'); ?></span>
                            </div>
                        </li>
                        <?php if ($productSingle['code']) { ?>
                            <li>
                                <div class="product-code">
                                    <strong> <?php _e('Product code'); ?> : </strong>
                                    <?php echo $this->escape($productSingle['code']); ?>
                                </div>
                            </li>
                        <?php } ?>
                        <li>
                            <div class="product-input-code">
                                <strong> <?php _e('Input product code'); ?> : </strong>
                                <?php echo $this->escape($productSingle['id']); ?>
                            </div>
                        </li>
                        <?php if (!empty($productSingle['price_title'])) { ?>
                            <li>
                                <div class="product-price-title">
                                    <strong><?php echo $this->escape($config['view_price_title']); ?> : </strong>
                                    <span><?php echo $this->escape($productSingle['price_title']); ?></span>
                                </div>
                            </li>
                        <?php } ?>
                        <li>
                            <div class="product-price-info">
                                <strong><?php _e('Price'); ?> : </strong>
                                <?php if ($productSingle['price_discount'] && ($productSingle['price_discount'] > $productSingle['price'])) { ?>
                                    <span class="text-danger">
                                        <del><?php echo $this->escape($productSingle['price_discount_view']); ?></del>
                                    </span>
                                <?php } ?>
                                <span class="p-price product-price" itemprop="price"
                                      content="<?php echo $this->escape($productSingle['price']); ?>"><?php echo $this->escape(
                                        $productSingle['price_view']
                                    ); ?></span>
                            </div>
                        </li>
                    </ul>
                    <meta itemprop="priceCurrency"
                          content="<?php echo $this->escape($productSingle['price_currency']); ?>">
                </div>
                <div class="col-lg-7 col-md-7 col-12">
                    <?php include $this->template('front/product-order'); ?>
                </div>
            </div>
        <?php } elseif ($config['order_stock'] == 'manual') { ?>
            <?php if ($productSingle['stock_type'] == 1 || $productSingle['stock_type'] == 5) { ?>
                <div class="clearfix row">
                    <div class="col-lg-5 col-md-5 col-12">
                        <ul class="list-unstyled">
                            <?php if (!empty($productSingle['brand'])) { ?>
                                <li>
                                    <div class="product-brand">
                                        <strong><?php _e('Brand'); ?> : </strong>
                                        <a itemprop="brand" href="<?php echo $this->escape($category['brandUrl']); ?>"
                                           title="<?php echo $this->escape($category['brandTitle']); ?>">
                                            <?php echo $this->escape($category['brandTitle']); ?>
                                        </a>
                                    </div>
                                </li>
                            <?php } ?>
                            <li>
                                <div class="product-stock">
                                    <strong><?php _e('Stock status'); ?> : </strong>
                                    <?php if ($productSingle['stock_type'] == 1) { ?>
                                        <span class="text-success" itemprop="availability"
                                              href="https://schema.org/InStock"><?php echo $this->escape($productSingle['stock_type_view']); ?></span>
                                    <?php } elseif ($productSingle['stock_type'] == 5) { ?>
                                        <span class="text-danger" itemprop="availability"
                                              href="https://schema.org/InStock"><?php echo $this->escape($productSingle['stock_type_view']); ?></span>
                                    <?php } ?>
                                </div>
                            </li>
                            <?php if ($productSingle['code']) { ?>
                                <li>
                                    <div class="product-code">
                                        <strong> <?php _e('Product code'); ?> : </strong>
                                        <?php echo $this->escape($productSingle['code']); ?>
                                    </div>
                                </li>
                            <?php } ?>
                            <li>
                                <div class="product-input-code">
                                    <strong> <?php _e('Input product code'); ?> : </strong>
                                    <?php echo $this->escape($productSingle['id']); ?>
                                </div>
                            </li>
                            <?php if (!empty($productSingle['price_title'])) { ?>
                                <li>
                                    <div class="product-price-title">
                                        <strong><?php echo $this->escape($config['view_price_title']); ?> : </strong>
                                        <span><?php echo $this->escape($productSingle['price_title']); ?></span>
                                    </div>
                                </li>
                            <?php } ?>
                            <li>
                                <div class="product-price-info">
                                    <strong><?php _e('Price'); ?> : </strong>
                                    <?php if ($productSingle['price_discount'] && ($productSingle['price_discount'] > $productSingle['price'])) { ?>
                                        <span class="text-danger">
                                            <del><?php echo $this->escape($productSingle['price_discount_view']); ?></del>
                                        </span>
                                    <?php } ?>
                                    <span class="p-price product-price" itemprop="price"
                                          content="<?php echo $this->escape($productSingle['price']); ?>">
                                        <?php echo $this->escape($productSingle['price_view']); ?>
                                    </span>
                                </div>
                            </li>
                        </ul>
                        <meta itemprop="priceCurrency"
                              content="<?php echo $this->escape($productSingle['price_currency']); ?>">
                    </div>
                    <div class="col-lg-7 col-md-7 col-12">
                        <?php include $this->template('front/product-order'); ?>
                    </div>
                </div>
            <?php } else { ?>
                <ul class="list-unstyled">
                    <?php if (!empty($productSingle['brand'])) { ?>
                        <li>
                            <div class="product-brand">
                                <strong><?php _e('Brand'); ?> : </strong>
                                <a itemprop="brand" href="<?php echo $this->escape($category['brandUrl']); ?>"
                                   title="<?php echo $this->escape($category['brandTitle']); ?>">
                                    <?php echo $this->escape($category['brandTitle']); ?>
                                </a>
                            </div>
                        </li>
                    <?php } ?>
                    <li>
                        <div class="product-stock">
                            <strong><?php _e('Stock status'); ?> : </strong>
                            <span class="text-danger"><?php echo $this->escape($productSingle['stock_type_view']); ?></span>
                        </div>
                    </li>
                    <?php if ($productSingle['code']) { ?>
                        <li>
                            <div class="product-code">
                                <strong> <?php _e('Product code'); ?> : </strong>
                                <?php echo $this->escape($productSingle['code']); ?>
                            </div>
                        </li>
                    <?php } ?>
                    <li>
                        <div class="product-input-code">
                            <strong> <?php _e('Input product code'); ?> : </strong>
                            <?php echo $this->escape($productSingle['id']); ?>
                        </div>
                    </li>
                    <?php if (!empty($productSingle['price_title'])) { ?>
                        <li>
                            <div class="product-price-title">
                                <strong><?php echo $this->escape($config['view_price_title']); ?> : </strong>
                                <span><?php echo $this->escape($productSingle['price_title']); ?></span>
                            </div>
                        </li>
                    <?php } ?>
                    <li>
                        <div class="product-price-info">
                            <strong><?php _e('Price'); ?> : </strong>
                            <?php if ($productSingle['price_discount'] && ($productSingle['price_discount'] > $productSingle['price'])) { ?>
                                <span class="text-danger">
                                    <del><?php echo $this->escape($productSingle['price_discount_view']); ?></del>
                                </span>
                            <?php } ?>
                            <span class="p-price product-price" itemprop="price"
                                  content="<?php echo $this->escape($productSingle['price']); ?>">
                                <?php echo $this->escape($productSingle['price_view']); ?>
                            </span>
                        </div>
                    </li>
                </ul>
            <?php } ?>
        <?php } elseif ($config['order_stock'] == 'product') { ?>
            <?php if ($productSingle['stock'] > 0) { ?>
                <div class="clearfix row">
                    <div class="col-lg-5 col-md-5 col-12">
                        <ul class="list-unstyled">
                            <?php if (!empty($productSingle['brand'])) { ?>
                                <li>
                                    <div class="product-brand">
                                        <strong><?php _e('Brand'); ?> : </strong>
                                        <a itemprop="brand" href="<?php echo $this->escape($category['brandUrl']); ?>"
                                           title="<?php echo $this->escape($category['brandTitle']); ?>">
                                            <?php echo $this->escape($category['brandTitle']); ?>
                                        </a>
                                    </div>
                                </li>
                            <?php } ?>
                            <li>
                                <div class="product-stock">
                                    <strong><?php _e('Stock status'); ?> : </strong>
                                    <span class="text-success" itemprop="availability"
                                          href="https://schema.org/InStock"><?php _e('In stock'); ?></span>
                                </div>
                            </li>
                            <?php if ($productSingle['code']) { ?>
                                <li>
                                    <div class="product-code">
                                        <strong> <?php _e('Product code'); ?> : </strong>
                                        <?php echo $this->escape($productSingle['code']); ?>
                                    </div>
                                </li>
                            <?php } ?>
                            <li>
                                <div class="product-input-code">
                                    <strong> <?php _e('Input product code'); ?> : </strong>
                                    <?php echo $this->escape($productSingle['id']); ?>
                                </div>
                            </li>
                            <?php if (!empty($productSingle['price_title'])) { ?>
                                <li>
                                    <div class="product-price-title">
                                        <strong><?php echo $this->escape($config['view_price_title']); ?> : </strong>
                                        <span><?php echo $this->escape($productSingle['price_title']); ?></span>
                                    </div>
                                </li>
                            <?php } ?>
                            <li>
                                <div class="product-price-info">
                                    <strong><?php _e('Price'); ?> : </strong>
                                    <?php if ($productSingle['price_discount'] && ($productSingle['price_discount'] > $productSingle['price'])) { ?>
                                        <span class="text-danger">
                                            <del><?php echo $this->escape($productSingle['price_discount_view']); ?></del>
                                        </span>
                                    <?php } ?>
                                    <span class="p-price product-price" itemprop="price"
                                          content="<?php echo $this->escape($productSingle['price']); ?>">
                                        <?php echo $this->escape($productSingle['price_view']); ?>
                                    </span>
                                </div>
                            </li>
                        </ul>
                        <meta itemprop="priceCurrency"
                              content="<?php echo $this->escape($productSingle['price_currency']); ?>">
                    </div>
                    <div class="col-lg-7 col-md-7 col-12">
                        <?php include $this->template('front/product-order'); ?>
                    </div>
                </div>
            <?php } else { ?>
                <ul class="list-unstyled">
                    <?php if (!empty($productSingle['brand'])) { ?>
                        <li>
                            <div class="product-brand">
                                <strong><?php _e('Brand'); ?> : </strong>
                                <a itemprop="brand" href="<?php echo $this->escape($category['brandUrl']); ?>"
                                   title="<?php echo $this->escape($category['brandTitle']); ?>">
                                    <?php echo $this->escape($category['brandTitle']); ?>
                                </a>
                            </div>
                        </li>
                    <?php } ?>
                    <li>
                        <div class="product-stock">
                            <strong><?php _e('Stock status'); ?> : </strong>
                            <span class="text-danger"><?php _e('Out of stock'); ?></span>
                        </div>
                    </li>
                    <?php if ($productSingle['code']) { ?>
                        <li>
                            <div class="product-code">
                                <strong> <?php _e('Product code'); ?> : </strong>
                                <?php echo $this->escape($productSingle['code']); ?>
                            </div>
                        </li>
                    <?php } ?>
                    <li>
                        <div class="product-input-code">
                            <strong> <?php _e('Input product code'); ?> : </strong>
                            <?php echo $this->escape($productSingle['id']); ?>
                        </div>
                    </li>
                    <?php if (!empty($productSingle['price_title'])) { ?>
                        <li>
                            <div class="product-price-title">
                                <strong><?php echo $this->escape($config['view_price_title']); ?> : </strong>
                                <span><?php echo $this->escape($productSingle['price_title']); ?></span>
                            </div>
                        </li>
                    <?php } ?>
                    <li>
                        <div class="product-price-info">
                            <strong><?php _e('Price'); ?> : </strong>
                            <?php if ($productSingle['price_discount'] && ($productSingle['price_discount'] > $productSingle['price'])) { ?>
                                <span class="text-danger">
                                     <del><?php echo $this->escape($productSingle['price_discount_view']); ?></del>
                                </span>
                            <?php } ?>
                            <span class="p-price product-price" itemprop="price"
                                  content="<?php echo $this->escape($productSingle['price']); ?>">
                                <?php echo $this->escape($productSingle['price_view']); ?>
                            </span>
                        </div>
                    </li>
                </ul>
            <?php } ?>
        <?php } elseif ($config['order_stock'] == 'property') { ?>
            <div class="clearfix row">
                <div class="col-lg-5 col-md-5 col-12">
                    <ul class="list-unstyled">
                        <?php if (!empty($productSingle['brand'])) { ?>
                            <li>
                                <div class="product-brand">
                                    <strong><?php _e('Brand'); ?> : </strong>
                                    <a itemprop="brand" href="<?php echo $this->escape($category['brandUrl']); ?>"
                                       title="<?php echo $this->escape($category['brandTitle']); ?>">
                                        <?php echo $this->escape($category['brandTitle']); ?>
                                    </a>
                                </div>
                            </li>
                        <?php } ?>
                        <?php if ($productSingle['code']) { ?>
                            <li>
                                <div class="product-code">
                                    <strong> <?php _e('Product code'); ?> : </strong>
                                    <?php echo $this->escape($productSingle['code']); ?>
                                </div>
                            </li>
                        <?php } ?>
                        <li>
                            <div class="product-input-code">
                                <strong> <?php _e('Input product code'); ?> : </strong>
                                <?php echo $this->escape($productSingle['id']); ?>
                            </div>
                        </li>
                        <li>
                            <div class="product-price-info">
                                <strong><?php _e('Price'); ?> : </strong>
                                <?php if ($productSingle['price_discount'] && ($productSingle['price_discount'] > $productSingle['price'])) { ?>
                                    <span class="text-danger">
                                        <del><?php echo $this->escape($productSingle['price_discount_view']); ?></del>
                                    </span>
                                <?php } ?>
                                <span class="p-price product-price" itemprop="price"
                                      content="<?php echo $this->escape($productSingle['price']); ?>">
                                <?php echo $this->escape($productSingle['price_view']); ?>
                            </span>
                            </div>
                        </li>
                    </ul>
                    <meta itemprop="priceCurrency"
                          content="<?php echo $this->escape($productSingle['price_currency']); ?>">
                </div>
                <div class="col-lg-7 col-md-7 col-12">
                    <?php include $this->template('front/product-order'); ?>
                </div>
            </div>
        <?php } ?>
    </div>
<?php } ?>
