<?php
$this->css($this->assetModule('css/front.css'));
// Set Open Graph tags for meta
$this->doctype('HTML5');
$this->headMeta($this->escape($productItem['title']), 'og:title', 'property');
$this->headMeta($this->escape($productItem['productUrl']), 'og:url', 'property');
if (isset($productItem['text_summary']) && !empty($productItem['text_summary'])) {
    $this->headMeta(_strip($productItem['text_summary']), 'og:description', 'property');
}
if (isset($productItem['largeUrl']) && !empty($productItem['largeUrl'])) {
    $this->headMeta($this->escape($productItem['largeUrl']), 'og:image', 'property');
}
// Set twitter for meta
$this->headMeta($this->escape($productItem['title']), 'twitter:title');
if (isset($productItem['text_summary']) && !empty($productItem['text_summary'])) {
    $this->headMeta(_strip($productItem['text_summary']), 'twitter:description');
}
if (isset($productItem['largeUrl']) && !empty($productItem['largeUrl'])) {
    $this->headMeta($this->escape($productItem['largeUrl']), 'twitter:image');
}
?>
<div class="clearfix">
    <div class="product-page h-product clearfix" itemscope itemtype="http://schema.org/Product">
        <div class="col-md-4">
            <?php include $this->template('front/gallery'); ?>
        </div>
        <div class="col-md-8">
            <div class="productTitle clearfix">
                <h1 class="p-name" itemprop="name">
                    <?php echo $this->escape($productItem['title']); ?>
                </h1>
            </div>
            <div class="productInfoBox productSummary e-description clearfix" itemprop="description">
                <?php echo $productItem['text_summary']; ?>
            </div>
            <div class="productInfoBox clearfix">
                <div class="productPriceBox">
                    <?php include $this->template('front/product-price'); ?>
                </div>
            </div>
            <div class="clearfix productInfoList">
                <ul class="list-inline">
                    <?php if (!empty($vote)) { ?>
                        <li class="col-md-2">
                            <?php include $this->template('votebar.phtml', 'front', 'vote'); ?>
                        </li>
                    <?php } ?>
                    <?php if (!empty($favourite)) { ?>
                        <li class="col-md-2">
                            <?php include $this->template('favouritebar.phtml', 'front', 'favourite'); ?>
                        </li>
                    <?php } ?>
                    <?php if ($config['view_question']) { ?>
                        <li class="col-md-2">
                            <?php include $this->template('front/product-question'); ?>
                        </li>
                    <?php } ?>
                    <?php if ($config['social_sharing']) { ?>
                        <li class="col-md-6">
                            <div class="socialSharing">
                                <?php echo $this->socialSharing(
                                    $config['social_sharing'],
                                    $this->escape($productItem['title']),
                                    $this->escape($productItem['productUrl']),
                                    $this->escape($productItem['largeUrl'])
                                ); ?>
                            </div>
                        </li>
                    <?php } ?>
                </ul>
            </div>
        </div>
        <div class="col-md-12">
            <div class="productInfoBox clearfix">
                <?php include $this->template('front/attribute'); ?>
            </div>
            <div class="productInfoBox productDescription p-review clearfix" itemprop="description">
                <h2><?php _e('Description'); ?></h2>
                <?php echo $productItem['text_description']; ?>
            </div>
            <div class="productInfoBox clearfix">
                <div class="p-brand p-category" itemprop="brand category">
                    <?php include $this->template('front/category'); ?>
                </div>
                <div class="p-category" itemprop="category">
                    <?php include $this->template('front/tag'); ?>
                </div>
            </div>
            <div class="productMedia">
                <?php include $this->template('front/attach-audio'); ?>
                <?php include $this->template('front/attribute-audio'); ?>
                <?php include $this->template('front/attach-video'); ?>
                <?php include $this->template('front/attribute-video'); ?>
            </div>
            <div class="productAttach">
                <?php include $this->template('front/attach'); ?>
            </div>
        </div>
    </div>
    <?php include $this->template('front/related'); ?>
    <?php //include $this->template('front/list'); ?>
</div>