<?php
$this->css($this->assetModule('css/front.css'));
$this->jQuery();
// Set Open Graph tags for meta
$this->doctype('HTML5');
$this->headMeta(__('Compare products'), 'og:title', 'property');
$this->headMeta($this->escape($url), 'og:url', 'property');
$this->headMeta(_strip($title), 'og:description', 'property');
if (isset($mainProduct['thumbUrl']) && !empty($mainProduct['thumbUrl'])) {
    $this->headMeta($this->escape($mainProduct['thumbUrl']), 'og:image', 'property');
}
// Set twitter for meta
$this->headMeta(__('Compare products'), 'twitter:title');
$this->headMeta(_strip($title), 'twitter:description');
if (isset($mainProduct['thumbUrl']) && !empty($mainProduct['thumbUrl'])) {
    $this->headMeta($this->escape($mainProduct['thumbUrl']), 'twitter:image');
}
// Set class
switch (count($products)) {
    case 1:
        $widthClass = 'product-compare-width-1 pull-left';
        break;

    case 2:
        $widthClass = 'product-compare-width-2 pull-left';
        break;

    case 3:
        $widthClass = 'product-compare-width-3 pull-left';
        break;

    case 4:
        $widthClass = 'product-compare-width-4 pull-left';
        break;

    case 5:
        $widthClass = 'product-compare-width-5 pull-left';
        break;
}
//
$script = <<<'EOT'
    (function ($) {
        $(".product-compare-remove").click(function() {
            var url = "%s";
            url = url.replace('/' + $(this).attr("data-slug"), '')
            window.location.href = url;
        });
    })(jQuery)
EOT;
$script = sprintf($script, $url);
$this->footScript()->appendScript($script);
?>
<div class="product-compare clearfix">
    <h1><?php _e('Compare products'); ?></h1>
    <?php if (isset($products) && !empty($products)) { ?>
        <div class="product-compare-header clearfix">
            <div class="col-md-2 col-12"></div>
            <div class="col-md-10 col-12">
                <div class="row">
                    <?php foreach ($products as $product) { ?>
                        <div class="<?php echo $widthClass; ?>">
                            <div class="col-md-12 col-12">
                                <div class="thumbnail text-center">
                                    <i class="fa fa-times-circle product-compare-remove"
                                       data-slug="<?php echo $this->escape($product['slug']); ?>"></i>
                                    <a target="_blank" href="<?php echo $this->escape($product['productUrl']); ?>"
                                       title="<?php echo $this->escape($product['title']); ?>">
                                        <img class="img-fluid"
                                             src="<?php echo $this->escape($product['thumbUrl']); ?>"
                                             alt="<?php echo $this->escape($product['title']); ?>">
                                    </a>
                                    <div class="caption">
                                        <h2>
                                            <a target="_blank"
                                               href="<?php echo $this->escape($product['productUrl']); ?>"
                                               title="<?php echo $this->escape($product['title']); ?>">
                                                <?php echo $this->escape($product['title']); ?>
                                            </a>
                                        </h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
        <div class="product-compare-box clearfix">
            <div class="col-md-2 col-12 product-compare-box-title">
                <ul class="list-unstyled row">
                    <li><?php _e('Stock'); ?></li>
                    <li><?php _e('Price'); ?></li>
                    <?php foreach ($product['attribute'] as $attribute) { ?>
                        <li class="product-compare-box-category"><?php echo $this->escape($attribute['title']); ?></li>
                        <?php foreach ($attribute['info'] as $attributeSingle) { ?>
                            <?php if ($attributeSingle['search'] == 1) { ?>
                                <li><?php echo $this->escape($attributeSingle['title']); ?></li>
                            <?php } ?>
                        <?php } ?>
                    <?php } ?>
                </ul>
            </div>
            <div class="col-md-10 col-12 product-compare-box-info">
                <div class="row">
                    <?php foreach ($products as $product) { ?>
                        <div class="<?php echo $widthClass; ?>">
                            <ul class="list-unstyled row">
                                <li><?php echo $this->escape($product['stock_type_view']); ?></li>
                                <li><?php echo $this->escape($product['price_view']); ?></li>
                                <?php foreach ($product['attribute'] as $attribute) { ?>
                                    <li class="product-compare-box-category"></li>
                                    <?php foreach ($attribute['info'] as $attributeSingle) { ?>
                                        <?php if ($attributeSingle['search'] == 1) { ?>
                                            <li><?php echo $this->escape($attributeSingle['data']); ?></li>
                                        <?php } ?>
                                    <?php } ?>
                                <?php } ?>
                            </ul>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    <?php } else { ?>
        <div class="alert alert-danger">
            <?php _e('Your compare list is empty, back to product list and select products to compare'); ?>
        </div>
    <?php } ?>
</div>