<?php
// Load angular custom js
$script = <<<'EOT'
var app = angular.module('shop', ['angularUtils.directives.dirPagination']);
var compareCount = 0;
var compareList = [];
app.controller('listdata',function($scope, $http){
    $scope.products = [];
    $('.shop-spinner').show();
    $http.get("%s").success(function(response){
        $scope.products = response;
        $('.ajax-spinner').hide();
    });
    $scope.sortKey = "%s";
    $scope.reverse = true;
    $scope.sort = function(keyname){
        $scope.sortKey = keyname;
        $scope.reverse = !$scope.reverse;
    }
    // compare products
    $(document).on("click", ".product-compare-add", function() {
        if (compareCount < 5) {
            if(jQuery.inArray($(this).attr("data-slug"), compareList) !== -1) {
                $('#compareModal .modal-body').html('%s');
                $('#compareModal').modal('show');
            } else {
                compareList.push($(this).attr("data-slug"));
                compareCount = compareCount + 1;

                var url = $('.product-compare-button a').attr('href');
                url = url + '/' + $(this).attr("data-slug");

                $('.product-compare-button a').attr("href", url);
                $(".product-compare-list").removeClass("hide");
                $(".product-compare-list .clearfix").append("<div class='col-xs-2'><div class='thumbnail'><img src='" + $(this).attr("data-image") + "' alt='" + $(this).attr("data-title") + "'><div class='caption'><h4>" + $(this).attr("data-title") + "</h4></div></div></div>");
            }
        } else {
            $('#compareModal .modal-body').html('%s');
            $('#compareModal').modal('show');
        }
    });
});
EOT;
$script = sprintf(
    $script,
    $filterUrl,
    'time_create',
    __('You put this product on compare list before'),
    __('You can add just 5 products on compare list')
);

$scriptMenu = <<<'EOT'
$(function() {
    var json = '%s';
    $('#category-tree-view').treeview({
        levels: 1,
        data: json,
        enableLinks: true,
        expandIcon: 'fa fa-plus',
		collapseIcon: 'fa fa-minus',
		emptyIcon: 'fa',
		checkedIcon: 'fa fa-check-square-o',
		uncheckedIcon: 'fa fa-square-o',
    });
});
EOT;
$scriptMenu = sprintf(
    $scriptMenu,
    $categoriesJson
);

// Load header files
$this->jQuery();
$this->angular();
$this->js(array(
    $this->assetModule('js/dirPagination.js'),
    $this->assetModule('js/bootstrap-treeview.min.js')
));
$this->css($this->assetModule('css/front.css'));
$this->footScript()->appendScript($script);
$this->footScript()->appendScript($scriptMenu);
// Set box site
switch ($config['view_column']) {
    case 1:
        $shopBoxSize = 'col-xs-12';
        break;

    case 2:
        $shopBoxSize = 'col-xs-6';
        break;

    case 3:
        $shopBoxSize = 'col-xs-4';
        break;

    case 4:
        $shopBoxSize = 'col-xs-3';
        break;

    case 5:
        $shopBoxSize = 'col-xs-2';
        break;
}
?>
<div class="clearfix row">
    <div class="ajax-spinner">
        <img src="<?php echo $this->assetModule('image/spinner.gif'); ?>" class="ajax-spinner-loader"/>
    </div>
    <div class="col-xs-12">
        <?php include $this->template('front/category'); ?>
    </div>
    <div class="col-xs-3">
        <div class="shop-search-form clearfix">
            <div class="page-header">
                <h4><?php _e('Search on this group'); ?></h4>
            </div>
            <form>
                <div class="form-group">
                    <label><?php _e('Title'); ?></label>
                    <input type="text" ng-model="filterTitle" class="form-control">
                </div>
                <div class="form-group">
                    <label><?php _e('Marketable'); ?></label>
                    <select ng-model="filterMarketable" class="form-control">
                        <option value=""><?php _e('All'); ?></option>
                        <option value="1"><?php _e('Marketable'); ?></option>
                        <option value="0"><?php _e('Not marketable'); ?></option>
                    </select>
                </div>
                <?php $filterNameArray = array(); ?>
                <?php foreach ($filterList as $singleFilter) { ?>
                    <?php if ($singleFilter['type'] == 'select') { ?>
                        <?php
                        $filterName = 'filter' . $singleFilter['name'];
                        $filterNameArray[] = array(
                            'fieldName' => $singleFilter['name'],
                            'filterName' => $filterName
                        );
                        ?>
                        <div class="form-group">
                            <label><?php echo $singleFilter['title']; ?></label>
                            <select ng-model="<?php echo $filterName; ?>" class="form-control">
                                <option value=""><?php _e('All'); ?></option>
                                <?php foreach ($singleFilter['value']['data'] as $valueData) { ?>
                                    <?php if (!empty($valueData)) { ?>
                                        <option ng-click="sort('<?php echo $valueData; ?>')"><?php echo $valueData; ?></option>
                                    <?php } ?>
                                <?php } ?>
                            </select>
                        </div>
                    <?php } elseif ($singleFilter['type'] == 'text') { ?>
                        <div class="form-group">
                            <?php
                            $filterName = 'filter' . $singleFilter['name'];
                            $filterNameArray[] = array(
                                'fieldName' => $singleFilter['name'],
                                'filterName' => $filterName
                            );
                            ?>
                            <label><?php echo $singleFilter['title']; ?></label>
                            <input type="text" ng-model="<?php echo $filterName; ?>" class="form-control">
                        </div>
                    <?php } ?>
                <?php } ?>
            </form>
        </div>
        <div class="clearfix category-list">
            <div class="page-header">
                <h4><?php _e('Category list'); ?></h4>
            </div>
            <div class="clearfix">
                <div id="category-tree-view"></div>
            </div>
        </div>
    </div>
    <div class="col-xs-9" ng-controller="listdata">
        <?php include $this->template('front/product-list-sale'); ?>
        <div class="product-compare-list hide">
            <div class="clearfix">
                <div class="col-xs-2">
                    <div class="product-compare-button text-center">
                        <a href="<?php echo Pi::url($this->url('', array('controller' => 'compare'))); ?>" title="<?php _e("Compare products"); ?>" class="btn btn-success btn-xs">
                            <?php _e("Compare products"); ?>
                        </a>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="compareModal" tabindex="-1" role="dialog" aria-labelledby="compareModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="<?php _e('Close'); ?>">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <h4 class="modal-title" id="compareModalLabel"><?php _e('Compare products'); ?></h4>
                        </div>
                        <div class="modal-body"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix">
            <div class="product-list clearfix">
                <?php if (isset($productTitleH1) && !empty($productTitleH1)) { ?>
                    <div class="page-header">
                        <h1><?php echo $productTitleH1; ?></h1>
                    </div>
                <?php } elseif (isset($productTitleH2) && !empty($productTitleH2)) { ?>
                    <div class="page-header">
                        <h2><?php echo $productTitleH2; ?></h2>
                    </div>
                <?php } ?>
                <?php if (!empty($config['text_description_index']) && isset($showIndexDesc) && $showIndexDesc == 1 && isset($page) && $page == 1) { ?>
                    <div class="well shopIndexDescription">
                        <?php echo $config['text_description_index']; ?>
                    </div>
                <?php } ?>
                <div class="clearfix product-sort">
                    <ul class="list-inline">
                        <li><?php _e('Sort by'); ?> :</li>
                        <li class="product-sort-type" ng-click="sort('time_create')"><?php _e('Time'); ?> <i class="fa sort-icon" ng-show="sortKey=='time_create'" ng-class="{'fa-caret-up':reverse,'fa-caret-down':!reverse}"></i></li>
                        <li class="product-sort-type" ng-click="sort('hits')"><?php _e('Hits'); ?> <i class="fa sort-icon" ng-show="sortKey=='hits'" ng-class="{'fa-caret-up':reverse,'fa-caret-down':!reverse}"></i></li>
                        <li class="product-sort-type" ng-click="sort('favourite')"><?php _e('Favourite'); ?> <i class="fa sort-icon" ng-show="sortKey=='favourite'" ng-class="{'fa-caret-up':reverse,'fa-caret-down':!reverse}"></i></li>
                        <li class="product-sort-type" ng-click="sort('sold')"><?php _e('Sold'); ?> <i class="fa sort-icon" ng-show="sortKey=='sold'" ng-class="{'fa-caret-up':reverse,'fa-caret-down':!reverse}"></i></li>
                        <li class="product-sort-type" ng-click="sort('price')"><?php _e('Price'); ?> <i class="fa sort-icon" ng-show="sortKey=='price'" ng-class="{'fa-caret-up':reverse,'fa-caret-down':!reverse}"></i></li>
                        <li class="product-sort-type" ng-click="sort('title')"><?php _e('Title'); ?>  <i class="fa sort-icon" ng-show="sortKey=='title'" ng-class="{'fa-caret-up':reverse,'fa-caret-down':!reverse}"></i></li>
                        <li class="product-sort-type" ng-click="sortKey=''"><?php _e('Default'); ?></li>
                    </ul>
                </div>
                <div class="row">
                    <div dir-paginate="product in products|orderBy:sortKey:reverse|filter: {<?php if (!empty($filterNameArray)) { ?><?php foreach ($filterNameArray as $filterNameSingle) { ?><?php echo $filterNameSingle['fieldName'] ?> : <?php echo $filterNameSingle['filterName'] ?>,<?php } ?><?php } ?> title : filterTitle, marketable : filterMarketable } |itemsPerPage:<?php echo $config['view_perpage']; ?>"
                         class="<?php echo $shopBoxSize; ?> product-box h-product" itemscope itemtype="https://schema.org/Product">
                        <div class="thumbnail" ng-mouseover="hoverCompare = true" ng-mouseleave="hoverCompare = false">
                            <div ng-show="hoverCompare"
                                 ng-click="changeClass()"
                                 ng-class="class"
                                 data-title="{{product.title}}"
                                 data-slug="{{product.slug}}"
                                 data-image="{{product.thumbUrl}}"
                                 class="product-compare-add">
                                <i class="fa fa-plus"></i> <?php _e('Compare'); ?>
                            </div>
                            <a class="u-url {{product.ribbon_class}}" itemprop="url" title="{{product.title}}" href="{{product.productUrl}}" target="_blank">
                                <img itemprop="image" class="img-responsive u-photo" src="{{product.thumbUrl}}" alt="{{product.title}}"/>
                                <p ng-if="product.ribbon">
                                    <span>{{product.ribbon}}</span>
                                </p>
                            </a>
                            <div class="caption">
                                <h3 class="p-name" itemprop="name">
                                    <a title="{{product.title}}" href="{{product.productUrl}}" target="_blank">
                                        {{product.title}}
                                    </a>
                                </h3>
                                <?php if ($config['order_active']) { ?>
                                    <div class="clearfix" itemprop="offers" itemscope itemtype="https://schema.org/Offer">
                                        <?php if ($config['order_stock'] == 'never') { ?>
                                            <div class="clearfix">
                                                <div class="clearfix">
                                                    <strong><?php _e('Stock status'); ?> : </strong>
                                                    <span class="text-success" itemprop="availability" href="https://schema.org/InStock"><?php _e('In stock'); ?></span>
                                                </div>
                                                <div ng-if="{{product.price_discount_has}} == 1">
                                                <span class="text-danger">
                                                    <del>{{product.price_discount_view}}</del>
                                                </span>
                                                </div>
                                                <span class="p-price" itemprop="price" content="{{product.price}}">{{product.price_view}}</span>
                                                <meta itemprop="priceCurrency" content="{{product.price_currency}}">
                                            </div>
                                        <?php } elseif ($config['order_stock'] == 'manual') { ?>
                                            <div ng-switch on="product.stock_type">
                                                <div ng-switch-when="1">
                                                    <div class="clearfix">
                                                        <div class="clearfix">
                                                            <strong><?php _e('Stock status'); ?> : </strong>
                                                            <span class="text-success" itemprop="availability" href="https://schema.org/InStock"><?php _e('In stock'); ?></span>
                                                        </div>
                                                        <div ng-if="product.price_discount_has == 1">
                                                    <span class="text-danger">
                                                        <del>{{product.price_discount_view}}</del>
                                                    </span>
                                                        </div>
                                                        <span class="p-price" itemprop="price" content="{{product.price}}">{{product.price_view}}</span>
                                                        <meta itemprop="priceCurrency" content="{{product.price_currency}}">
                                                    </div>
                                                </div>
                                                <div ng-switch-when="2">
                                                    <div class="clearfix">
                                                        <strong><?php _e('Stock status'); ?> : </strong>
                                                        <span class="text-danger">{{product.stock_type_view}}</span>
                                                    </div>
                                                </div>
                                                <div ng-switch-when="3">
                                                    <div class="clearfix">
                                                        <strong><?php _e('Stock status'); ?> : </strong>
                                                        <span class="text-danger">{{product.stock_type_view}}</span>
                                                    </div>
                                                </div>
                                                <div ng-switch-when="4">
                                                    <div class="clearfix">
                                                        <strong><?php _e('Stock status'); ?> : </strong>
                                                        <span class="text-danger">{{product.stock_type_view}}</span>
                                                    </div>
                                                </div>
                                                <div ng-switch-when="5">
                                                    <div class="clearfix">
                                                        <div class="clearfix">
                                                            <strong><?php _e('Stock status'); ?> : </strong>
                                                            <span class="text-danger" itemprop="availability" href="https://schema.org/InStock">{{product.stock_type_view}}</span>
                                                        </div>
                                                    <span ng-if="product.price_discount_has == 1">
                                                        <span class="text-danger small">
                                                            <del>{{product.price_discount_view}}</del>
                                                        </span>
                                                    </span>
                                                        <span class="p-price" itemprop="price" content="{{product.price}}">{{product.price_view}}</span>
                                                        <meta itemprop="priceCurrency" content="{{product.price_currency}}">
                                                    </div>
                                                </div>
                                            </div>
                                        <?php } elseif ($config['order_stock'] == 'product') { ?>
                                            <div ng-if="product.stock > 0">
                                                <div class="clearfix">
                                                    <div class="clearfix">
                                                        <strong><?php _e('Stock status'); ?> : </strong>
                                                        <span class="text-success" itemprop="availability" href="https://schema.org/InStock"><?php _e('In stock'); ?></span>
                                                    </div>
                                                    <div ng-if="product.price_discount_has == 1">
                                                    <span class="text-danger">
                                                        <del>{{product.price_discount_view}}</del>
                                                    </span>
                                                    </div>
                                                    <span class="p-price" itemprop="price" content="{{product.price}}">{{product.price_view}}</span>
                                                    <meta itemprop="priceCurrency" content="{{product.price_currency}}">
                                                </div>
                                            </div>
                                            <div ng-if="product.stock == 0">
                                                <div class="clearfix">
                                                    <strong><?php _e('Stock status'); ?> : </strong>
                                                    <span class="text-danger"><?php _e('Out of stock'); ?></span>
                                                </div>
                                            </div>
                                        <?php } elseif ($config['order_stock'] == 'property') { ?>
                                            <div class="clearfix">
                                                <div ng-if="product.price_discount_has == 1">
                                                <span class="text-danger">
                                                    <del>{{product.price_discount_view}}</del>
                                                </span>
                                                </div>
                                                <span class="p-price" itemprop="price" content="{{product.price}}">{{product.price_view}}</span>
                                                <meta itemprop="priceCurrency" content="{{product.price_currency}}">
                                            </div>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="paginator">
                <dir-pagination-controls
                    max-size="<?php echo $config['view_perpage']; ?>"
                    direction-links="true"
                    boundary-links="true">
                </dir-pagination-controls>
            </div>
        </div>
    </div>
</div>