<?php
$script = <<<'EOT'
    $(document).ready(function($) {
        $(".property-value-radio").change(function() {
            $(".product-price").html($(this).attr("data-price-view"));
        });
        $(".property-value-select").change(function() {
            $(".product-price").html($(".property-value-select option:selected").attr("data-price-view"));
        });
    });
EOT;
$this->footScript()->appendScript($script);
?>
<form action="<?php echo $this->escape($productItem['cartUrl']); ?>" method="post">
    <input name="id" type="hidden" value="<?php echo $this->escape($productItem['id']); ?>">
    <?php foreach ($property['list'] as $propertyList) { ?>
        <?php if (!empty($property['value'][$propertyList['id']])) { ?>
            <div class="form-group clearfix">
                <label class="control-label"><?php echo $this->escape($propertyList['title']); ?></label>
                <?php if ($propertyList['type'] == 'checkbox') { ?>
                    <div class="col-md-9 col-xs-12">
                        <?php foreach ($property['value'][$propertyList['id']] as $key => $propertyValue) { ?>
                            <?php if ($config['order_stock'] != 'property') { ?>
                                <label class="radio-inline input-sm">
                                    <input type="radio" class="property-value-radio"
                                        <?php if ($propertyList['influence_price']) { ?>
                                            data-key="<?php echo $this->escape($propertyValue['unique_key']); ?>"
                                            data-price="<?php echo $this->escape($propertyValue['price']); ?>"
                                            data-price-view="<?php echo $this->escape($propertyValue['price_view']); ?>"
                                            <?php if ($propertyValue['price'] == 0) { ?>
                                                disabled="disabled"
                                            <?php } ?>
                                        <?php } ?>
                                        <?php if ($propertyValue['select']) { ?>
                                            checked="checked"
                                        <?php } ?>
                                           name="property[<?php echo $this->escape($propertyList['id']); ?>]"
                                           value="<?php echo $this->escape($propertyValue['unique_key']); ?>"> <?php echo $this->escape($propertyValue['name']); ?>
                                </label>
                            <?php } elseif ($config['order_stock'] == 'property' && $propertyValue['stock'] > 0) { ?>
                                <label class="radio-inline input-sm">
                                    <input type="radio" class="property-value-radio"
                                        <?php if ($propertyList['influence_price']) { ?>
                                            data-key="<?php echo $this->escape($propertyValue['unique_key']); ?>"
                                            data-price="<?php echo $this->escape($propertyValue['price']); ?>"
                                            data-price-view="<?php echo $this->escape($propertyValue['price_view']); ?>"
                                        <?php } ?>
                                        <?php if ($propertyValue['select']) { ?>
                                            checked="checked"
                                        <?php } ?>
                                           name="property[<?php echo $this->escape($propertyList['id']); ?>]"
                                           value="<?php echo $this->escape($propertyValue['unique_key']); ?>"> <?php echo $this->escape($propertyValue['name']); ?>
                                </label>
                            <?php } ?>
                        <?php } ?>
                    </div>
                <?php } elseif ($propertyList['type'] == 'selectbox') { ?>
                    <div class="col-md-4 col-xs-12">
                        <select name="property[<?php echo $this->escape($propertyList['id']); ?>]"
                                class="form-control input-sm property-value-select">
                            <?php foreach ($property['value'][$propertyList['id']] as $key => $propertyValue) { ?>
                                <?php if ($config['order_stock'] != 'property') { ?>
                                    <option value="<?php echo $this->escape($propertyValue['unique_key']); ?>"
                                        <?php if ($propertyList['influence_price']) { ?>
                                            data-key="<?php echo $this->escape($propertyValue['unique_key']); ?>"
                                            data-price="<?php echo $this->escape($propertyValue['price']); ?>"
                                            data-price-view="<?php echo $this->escape($propertyValue['price_view']); ?>"
                                            <?php if ($propertyValue['price'] == 0) { ?>
                                                disabled="disabled"
                                            <?php } ?>
                                        <?php } ?>
                                        <?php if ($propertyValue['select']) { ?>
                                            selected="selected"
                                        <?php } ?>>
                                        <?php echo $this->escape($propertyValue['name']); ?>
                                    </option>
                                <?php } elseif ($config['order_stock'] == 'property' && $propertyValue['stock'] > 0) { ?>
                                    <option value="<?php echo $this->escape($propertyValue['unique_key']); ?>"
                                        <?php if ($propertyList['influence_price']) { ?>
                                            data-key="<?php echo $this->escape($propertyValue['unique_key']); ?>"
                                            data-price="<?php echo $this->escape($propertyValue['price']); ?>"
                                            data-price-view="<?php echo $this->escape($propertyValue['price_view']); ?>"
                                        <?php } ?>
                                        <?php if ($propertyValue['select']) { ?>
                                            selected="selected"
                                        <?php } ?>>
                                        <?php echo $this->escape($propertyValue['name']); ?>
                                    </option>
                                <?php } ?>
                            <?php } ?>
                        </select>
                    </div>
                <?php } ?>
            </div>
        <?php } ?>
    <?php } ?>
    <button type="submit" class="btn btn-success btn-lg">
        <i class="fa fa-shopping-cart"></i> <?php _e('Add to cart'); ?>
    </button>
</form>