<?php
    $this->css($this->assetModule('css/front.css'));
?>
<div class="productProperty">
<?php if (!empty($productItem['property_1'])) { ?>
	<div class="productPropertyItem">
		<strong><?php echo $this->escape($config['property_1_title']); ?></strong>
		<span><?php echo $this->escape($productItem['property_1']); ?></span>
	</div>
<?php } ?>
<?php if (!empty($productItem['property_2'])) { ?>
	<div class="productPropertyItem">
		<strong><?php echo $this->escape($config['property_2_title']); ?></strong>
		<span><?php echo $this->escape($productItem['property_2']); ?></span>
	</div>
<?php } ?>
<?php if (!empty($productItem['property_3'])) { ?>
	<div class="productPropertyItem">
		<strong><?php echo $this->escape($config['property_3_title']); ?></strong>
		<span><?php echo $this->escape($productItem['property_3']); ?></span>
	</div>
<?php } ?>
<?php if (!empty($productItem['property_4'])) { ?>
	<div class="productPropertyItem">
		<strong><?php echo $this->escape($config['property_4_title']); ?></strong>
		<span><?php echo $this->escape($productItem['property_4']); ?></span>
	</div>
<?php } ?>
<?php if (!empty($productItem['property_5'])) { ?>
	<div class="productPropertyItem">
		<strong><?php echo $this->escape($config['property_5_title']); ?></strong>
		<span><?php echo $this->escape($productItem['property_5']); ?></span>
	</div>
<?php } ?>
<?php if (!empty($productItem['property_6'])) { ?>
	<div class="productPropertyItem">
		<strong><?php echo $this->escape($config['property_6_title']); ?></strong>
		<span><?php echo $this->escape($productItem['property_6']); ?></span>
	</div>
<?php } ?>
<?php if (!empty($productItem['property_7'])) { ?>
	<div class="productPropertyItem">
		<strong><?php echo $this->escape($config['property_7_title']); ?></strong>
		<span><?php echo $this->escape($productItem['property_7']); ?></span>
	</div>
<?php } ?>
<?php if (!empty($productItem['property_8'])) { ?>
	<div class="productPropertyItem">
		<strong><?php echo $this->escape($config['property_8_title']); ?></strong>
		<span><?php echo $this->escape($productItem['property_8']); ?></span>
	</div>
<?php } ?>
<?php if (!empty($productItem['property_9'])) { ?>
	<div class="productPropertyItem">
		<strong><?php echo $this->escape($config['property_9_title']); ?></strong>
		<span><?php echo $this->escape($productItem['property_9']); ?></span>
	</div>
<?php } ?>
<?php if (!empty($productItem['property_10'])) { ?>
	<div class="productPropertyItem">
		<strong><?php echo $this->escape($config['property_10_title']); ?></strong>
		<span><?php echo $this->escape($productItem['property_10']); ?></span>
	</div>
<?php } ?>
</div>