<?php if (isset($specialList) && !empty($specialList)) { ?>
    <div class="productList clearfix">
        <div class="page-header">
            <h4><?php _e('Special products'); ?></h4>
        </div>
        <div class="specialList clearfix">
            <?php foreach ($specialList as $product) { ?>
                <?php include $this->template('front/product-box'); ?>
            <?php } ?>
        </div>
    </div>
<?php } ?>