<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="shop">
	<div class="order">
		<h3><?php echo $this->escape($order['code']); ?></h3>
        <div class="well">
			<h3><?php _e('Customer'); ?></h3>
			<ul class="clearfix list-unstyled">
        		<li class="col-md-4"><strong><?php _e('Order Name'); ?></strong> : <?php echo $this->escape($order['first_name']); ?> <?php echo $this->escape($order['last_name']); ?></li>
        		<li class="col-md-4"><strong><?php _e('User Name'); ?></strong> : <?php echo $this->escape($order['user']['identity']); ?> ( <?php echo $this->escape($order['user']['name']); ?> ) <span class="label label-info"><?php echo $this->escape($order['user']['id']); ?></span></li>
        		<li class="col-md-4"><strong><?php _e('Order Email'); ?></strong> : <?php echo $this->escape($order['email']); ?></li>
        		<li class="col-md-4"><strong><?php _e('Email'); ?></strong> : <?php echo $this->escape($order['user']['email']); ?></li>
        		<li class="col-md-4"><strong><?php _e('Phone'); ?></strong> : <?php echo $this->escape($order['phone']); ?></li>
        		<li class="col-md-4"><strong><?php _e('Mobile'); ?></strong> : <?php echo $this->escape($order['mobile']); ?></li>
        		<li class="col-md-4"><strong><?php _e('Company'); ?></strong> : <?php echo $this->escape($order['company']); ?></li>
        		<li class="col-md-4"><strong><?php _e('Country'); ?></strong> : <?php echo $this->escape($order['country']); ?></li>
        		<li class="col-md-4"><strong><?php _e('City'); ?></strong> : <?php echo $this->escape($order['city']); ?></li>
        		<li class="col-md-4"><strong><?php _e('Zip code'); ?></strong> : <?php echo $this->escape($order['zip_code']); ?></li>
        		<li class="col-md-8"><strong><?php _e('Address'); ?></strong> : <?php echo $this->escape($order['address']); ?></li>
			</ul>
		</div>
		<div class="well">
			<h3><?php _e('Order'); ?></h3>
			<ul class="clearfix list-unstyled">
        		<li class="col-md-3"><strong><?php _e('Status'); ?></strong> : <?php echo $this->escape($order['orderTitle']); ?></li>
        		<li class="col-md-3"><strong><?php _e('Time'); ?></strong> : <?php echo $this->escape($order['time_create_view']); ?></li>
        		<li class="col-md-3"><strong><?php _e('Finish'); ?></strong> : <?php echo $this->escape($order['time_finish_view']); ?></li>
			</ul>
		</div>
		<div class="well">
			<h3><?php _e('Payment'); ?></h3>
			<ul class="clearfix list-unstyled">
        		<li class="col-md-3"><strong><?php _e('Status'); ?></strong> : <?php echo $this->escape($order['paymentTitle']); ?></li>
        		<li class="col-md-3"><strong><?php _e('Time'); ?></strong> : <?php echo $this->escape($order['time_payment_view']); ?></li>
        		<li class="col-md-3"><strong><?php _e('Method'); ?></strong> : <?php echo $this->escape($order['payment_method']); ?></li>
        		<li class="col-md-3"><strong><?php _e('Adapter'); ?></strong> : <?php echo $this->escape($order['payment_adapter']); ?></li>
			</ul>
		</div>
		<div class="well">
			<h3><?php _e('Delivery'); ?></h3>
			<ul class="clearfix list-unstyled">
        		<li class="col-md-3"><strong><?php _e('Status'); ?></strong> : <?php echo $this->escape($order['deliveryTitle']); ?></li>
        		<li class="col-md-3"><strong><?php _e('Time'); ?></strong> : <?php echo $this->escape($order['time_delivery_view']); ?></li>
        		<li class="col-md-3"><strong><?php _e('Method'); ?></strong> : </li>
        		<li class="col-md-3"><strong><?php _e('Packing'); ?></strong> : </li>
			</ul>
		</div>
		<div class="well">
			<h3><?php _e('Price'); ?></h3>
			<ul class="clearfix list-unstyled">
        		<li class="col-md-4"><strong><?php _e('Price'); ?></strong> : <?php echo $this->escape($order['product_price_view']); ?></li>
        		<li class="col-md-4"><strong><?php _e('Discount'); ?></strong> : <?php echo $this->escape($order['discount_price_view']); ?></li>
        		<li class="col-md-4"><strong><?php _e('Shipping'); ?></strong> : <?php echo $this->escape($order['shipping_price_view']); ?></li>
        		<li class="col-md-4"><strong><?php _e('Packing'); ?></strong> : <?php echo $this->escape($order['packing_price_view']); ?></li>
        		<li class="col-md-4"><strong><?php _e('Total'); ?></strong> : <?php echo $this->escape($order['total_price_view']); ?></li>
        		<li class="col-md-4"><strong><?php _e('Paid'); ?></strong> : <?php echo $this->escape($order['paid_price_view']); ?></li>
			</ul>
		</div>
    	<div class="well clearfix">
			<h3><?php _e('Products'); ?></h3>
    		<?php foreach($order['product'] as $product) { ?>
            <div class="media">
                <a class="pull-left" title="<?php echo $this->escape($product['details']['title']); ?>" href="<?php echo $this->escape($product['details']['productUrl']); ?>">
                    <img src="<?php echo $this->escape($product['details']['thumbUrl']); ?>" alt="<?php echo $this->escape($product['details']['title']); ?>" />
                </a>
                <div class="media-body">
                    <h3 class="media-heading"><a title="<?php echo $this->escape($product['details']['title']); ?>" href="<?php echo $this->escape($product['details']['productUrl']); ?>"><?php echo $this->escape($product['details']['title']); ?></a></h3>
                    <ul class="list-unstyled">
                    	<li><strong><?php _e('Current Price'); ?></strong> : <?php echo $this->escape($product['details']['price_view']); ?></li>
                    	<li><strong><?php _e('Order price'); ?></strong> : <?php echo $this->escape($product['product_price']); ?></li>
                    	<li><strong><?php _e('Order discount'); ?></strong> : <?php echo $this->escape($product['discount_price']); ?></li>
                    	<li><strong><?php _e('Order number'); ?></strong> : <?php echo $this->escape($product['number']); ?></li>
                    	<li><strong><?php _e('Order total'); ?></strong> : <?php echo $this->escape($product['total_price']); ?></li>
                    </ul>
                </div>
            </div>
    		<?php } ?>
    	</div>
	</div>
</div>