<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
	<div class="well">
		<h1><?php echo $this->escape($user['first_name']); ?> <?php echo $this->escape($user['last_name']); ?></h1>
		<ul class="clearfix list-unstyled">
			<li class="col-md-5"><strong><?php _e('Order Name'); ?></strong> : <?php echo $this->escape($user['first_name']); ?> <?php echo $this->escape($user['last_name']); ?></li>
			<li class="col-md-5"><strong><?php _e('User Name'); ?></strong> : <?php echo $this->escape($user['user']['identity']); ?> ( <?php echo $this->escape($user['user']['name']); ?> ) <span class="label label-info"><?php echo $this->escape($user['user']['id']); ?></span></li>
			<li class="col-md-5"><strong><?php _e('Order Email'); ?></strong> : <?php echo $this->escape($user['email']); ?></li>
			<li class="col-md-5"><strong><?php _e('Email'); ?></strong> : <?php echo $this->escape($user['user']['email']); ?></li>
			<li class="col-md-5"><strong><?php _e('Phone'); ?></strong> : <?php echo $this->escape($user['phone']); ?></li>
			<li class="col-md-5"><strong><?php _e('Mobile'); ?></strong> : <?php echo $this->escape($user['mobile']); ?></li>
			<li class="col-md-5"><strong><?php _e('Company'); ?></strong> : <?php echo $this->escape($user['company']); ?></li>
        	<li class="col-md-5"><strong><?php _e('Country'); ?></strong> : <?php echo $this->escape($user['country']); ?></li>
        	<li class="col-md-5"><strong><?php _e('City'); ?></strong> : <?php echo $this->escape($user['city']); ?></li>
        	<li class="col-md-5"><strong><?php _e('Zip code'); ?></strong> : <?php echo $this->escape($user['zip_code']); ?></li>
        	<li class="col-md-12"><strong><?php _e('Address'); ?></strong> : <?php echo $this->escape($user['address']); ?></li>
		</ul>
	</div>
	<?php foreach($orders as $order) { ?>
		<div class="well">
			<div class="clearfix">
				<div class="col-md-3"><h5><a title="<?php _e('View order'); ?>" href="<?php echo $this->url('', array('action' => 'order', 'id' => $order['id'])); ?>"><?php echo $this->escape($order['code']); ?></a></h5></div>
				<div class="col-md-9">
					<span class="<?php echo $this->escape($order['orderClass']); ?>"><?php echo $this->escape($order['orderTitle']); ?></span>
					<span class="<?php echo $this->escape($order['paymentClass']); ?>"><?php echo $this->escape($order['paymentTitle']); ?></span>
					<span class="<?php echo $this->escape($order['deliveryClass']); ?>"><?php echo $this->escape($order['deliveryTitle']); ?></span>
				</div>
			</div>
			<div class="clearfix">
			<?php foreach($order['product'] as $product) { ?>
			    <div class="text-center"> 
			    	<a title="<?php echo $product['details']['title']; ?>" href="<?php echo $product['details']['productUrl']; ?>"><img class="col-md-1" src="<?php echo $product['details']['thumbUrl']; ?>" alt="<?php echo $product['details']['title']; ?>" /></a>
			    </div>
			<?php } ?>
			</div>
		</div>
	<?php } ?>
</div>